const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {mkdirSync}=require('node:fs');
const base=process.argv[2]||'http://127.0.0.1:8878/_site/slides/';
const output=process.argv[3]||'/tmp/gigawatt-presenter-notes';
(async()=>{
  mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:900}});
  const audience=await context.newPage();const errors=[];
  context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  audience.on('pageerror',e=>errors.push(e.message));
  await audience.goto(new URL('rack-energy.html?teach=1#vrm-switching',base).href);
  const [presenter]=await Promise.all([audience.waitForEvent('popup'),audience.getByRole('button',{name:'Presenter',exact:true}).click()]);
  await presenter.setViewportSize({width:1440,height:900});
  await presenter.waitForFunction(()=>document.querySelector('#workspace').dataset.notes==='true');
  await presenter.locator('#notes-content').getByText(/same 40 A average/).waitFor();
  await presenter.frameLocator('#preview').locator('#scene[data-scene="vrm-phase-counts"]').waitFor();
  const sizes=await presenter.evaluate(()=>[...document.querySelector('#presenter-content').children].map(e=>e.getBoundingClientRect().width));
  assert.ok(Math.abs(sizes[0]-sizes[1])<1);
  assert.equal(await audience.locator('#notes-content').count(),0);
  assert.equal(await presenter.frameLocator('#preview').locator('#notes-content').count(),0);
  assert.equal(await audience.locator('html').getAttribute('data-presenter-active'),'');
  assert.equal(await presenter.locator('#notes-content a').count(),0);
  await presenter.screenshot({path:`${output}/split-1440.png`});
  await presenter.setViewportSize({width:1280,height:720});
  await presenter.screenshot({path:`${output}/split-1280.png`});
  await presenter.locator('#slides').selectOption('0');
  await presenter.waitForFunction(()=>document.querySelector('#workspace').dataset.notes==='false');
  await presenter.frameLocator('#preview').locator('#scene[data-scene="rack-density-roadmap"]').waitFor();
  assert.equal(await presenter.locator('#speaker-notes').isVisible(),false);
  assert.equal(await presenter.locator('#notes-content').innerText(),'');
  assert.equal(Math.round((await presenter.locator('#next-shell').boundingBox()).width),1280);
  await presenter.screenshot({path:`${output}/no-notes-1280.png`});
  await presenter.locator('#slides').selectOption('11');
  await presenter.locator('#notes-content').getByText(/same 40 A average/).waitFor();
  await audience.reload();
  await presenter.waitForFunction(()=>!document.querySelector('#slides').disabled);
  await presenter.locator('#notes-content').getByText(/same 40 A average/).waitFor();
  await audience.goto(new URL('operations.html?teach=1',base).href);
  await presenter.locator('#chapter').getByText(/14\./).waitFor();
  assert.equal(await presenter.locator('#workspace').getAttribute('data-notes'),'true','notes resolve on a first slide with no URL hash');
  await audience.goto(new URL('grid-queues.html?teach=1#btm-gap',base).href);
  await presenter.locator('#chapter').getByText(/17\./).waitFor();
  await presenter.locator('#end').waitFor({state:'visible'});
  assert.equal(await presenter.locator('#workspace').getAttribute('data-notes'),'true');
  assert.equal(await presenter.locator('#next').isDisabled(),true);
  await presenter.screenshot({path:`${output}/final-slide.png`});
  await presenter.emulateMedia({colorScheme:'dark'});
  await presenter.screenshot({path:`${output}/dark-notes.png`});
  await presenter.getByRole('button',{name:'Exit presenter'}).click();
  await audience.waitForFunction(()=>!('presenterActive' in document.documentElement.dataset));
  assert.equal(await audience.locator('.toolbar').isVisible(),true);
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Presenter browser checks passed: split, no notes, preview isolation, navigation, reload, chapter change, final slide and Exit.');
})().catch(error=>{console.error(error);process.exit(1);});
