import {backstopScenes} from './capacity-backstop.js';
const business='d15-capacity-ledger',economics='d15-cost-per-service',delivery='d15-upgrade-and-evidence';
const s=(id,label,title,reference,objective,explanation,extra={})=>({id,label,title,reference,objective,pedagogical_role:'mechanism',explanation:[explanation],...extra});
export const sources=Object.freeze({
 filing:'https://www.sec.gov/Archives/edgar/data/1769628/000176962826000104/crwv-20251231.htm',
 bare:'https://www.coreweave.com/products/bare-metal',
 managed:'https://www.coreweave.com/products/dedicated-inference',
 sunk:'https://docs.coreweave.com/products/sunk/deploy_sunk/create-sunk-cluster',
 anthropic:'https://www.coreweave.com/news/coreweave-announces-multi-year-agreement-with-anthropic',
 cursor:'https://fireworks.ai/blog/cursor',
 spot:'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html',
 pricing:'https://gpu-index.semianalysis.com/',
 plan:'https://www.crusoe.ai/resources/newsroom/crusoe-expands-ai-data-center-campus-in-abilene-to-1-2-gigawatts',
 live:'https://www.crusoe.ai/resources/newsroom/crusoe-announces-flagship-abilene-data-center-is-live',
 oracle:'https://www.oracle.com/data-centers/'
});
export const learningContract=Object.freeze({driving_question:'How does a GPU cloud turn installed hardware into a business?',fixed_boundary:'Provider capacity revenue, customer service scope, and dated Abilene delivery reports.',changed_variable:'Contract duration, rental price, billable occupancy and electricity cost.',primary_payoff:'Explain who carries demand, price, operating and delivery risk.',misconception:'Bare metal means unmanaged; a high hourly quote guarantees a profitable fleet.',closing_question:'How did the published Abilene construction targets compare with reported delivery?'});
export const initialState={occupancy:.5};
export const scenes=[
 s('hardware-prices-meme','AI demand and hardware prices','AI demand and hardware prices',economics,'D15.3','User-supplied meme about AI demand and component purchase prices. It opens the chapter with the demand behind the business; component purchase prices are distinct from GPU rental rates.',{pedagogical_role:'transition',imageOnly:true}),
 s('capacity-purpose','GPU cloud economics','GPU cloud economics',business,'D15.1','Begin with a real provider. CoreWeave’s 2025 annual report describes capacity access sold on committed and on-demand terms. More than 98 percent of 2025 revenue came from committed contracts. This is the commercial layer above the equipment and facilities studied earlier; it is not a universal invoice for completed training jobs.',{sources:[sources.filing]}),
 s('what-is-sold','What the customer buys','GPU capacity and model APIs have different billing units.',business,'D15.1','A capacity customer buys access to GPUs and associated infrastructure; the agreement may reserve a cluster or charge for usage. A model API can instead bill tokens. CoreWeave currently lists both GPU-hour dedicated inference and token-billed serverless inference. The AI lab may track its internal cost per training run or token even when its supplier invoices capacity. Neither billing method implies ownership of the hardware.',{sources:[sources.managed,sources.filing]}),
 s('service-boundary','Who runs inference?','There are two ways to skin the cat.',business,'D15.1','Compare two serving choices: the customer operates the inference runtime, scaling and updates on CoreWeave GPU infrastructure, or CoreWeave operates those services through Dedicated Inference. The customer supplies its model and application in either arrangement. Bare metal means the operating system runs directly on dedicated physical hardware without a hypervisor. It does not prohibit Kubernetes, Slurm or managed software: CoreWeave runs Kubernetes on bare metal. Customer-operated inference on CKS is not necessarily a completely unmanaged server rental. This slide compares operating responsibilities, not hardware ownership.',{sources:[sources.bare,sources.managed,sources.sunk]}),
 s('service-examples','Anthropic and Cursor','Anthropic and Cursor',business,'D15.1','The left side grounds GPU-capacity purchasing in CoreWeave’s April 10, 2026 agreement supporting Claude development and deployment. The announcement says Anthropic will run production workloads on CoreWeave’s platform; it does not disclose a bare-metal purchase or the precise division of serving responsibilities. Use Anthropic as a potential customer-operated example, not proof of that contract’s software boundary. The right side is the documented Fast Apply example from June 2024: Cursor trained a specialized model and Fireworks deployed it on its inference engine through a completion API. This proves managed serving for that example, not that Fireworks runs every Cursor model. CoreWeave’s preceding product comparison offers the same choice of customer-operated and managed serving.',{pedagogical_role:'case-study',sources:[sources.anthropic,sources.cursor,sources.managed]}),
 s('rental-products','On-demand, Spot, committed','Spot rents spare capacity at the current price.',business,'D15.2','Separate flexible on-demand access, an explicitly interruptible cloud Spot product, and a capacity commitment. AWS can reclaim EC2 Spot capacity. A short-term bilateral rental price or a spot-contract market index does not by itself establish that interruption right. Quote comparisons must hold GPU, region, network, service scope and start date fixed.',{sources:[sources.spot,sources.pricing]}),
 s('contract-tenor','One, three or five years','A longer contract trades repricing opportunities for committed revenue.',economics,'D15.2','The timeline shows one-, three- and five-year terms over the same five-year window. Dotted segments are future business that has not been sold, not guaranteed renewal. A long contract can reduce demand and repricing exposure but leaves delivery and customer-credit risk. Customers gain capacity assurance and may negotiate a discount in exchange for commitment and prepayment. A longer duration does not universally imply a lower quoted rate. SemiAnalysis publishes these tenors; missing public quotes are not filled with invented rates.',{sources:[sources.pricing,sources.filing]}),
 s('rental-market','H100 rental market','H100 rental prices rose into April 2026.',economics,'D15.2','Use three dated public observations for one-year H100 rental contracts: October 2025, January 2026 and April 2026. The bars show the 25th–75th percentile ranges, not daily spot prices or current September quotes. The public table specifies a typical 25 percent prepayment. The point is renewal exposure: an older GPU’s rental price need not fall monotonically. Do not compare this range directly with the separately weighted composite index.',{sources:[sources.pricing]}),
 s('billable-occupancy','The empty-GPU risk','A higher rental rate can earn less across the fleet.',economics,'D15.3','Original one-year revenue example: the same 1,024 GPUs, 8,760 hours and service scope. Full-fleet commitment pays 2.50 dollars per GPU-hour regardless of customer usage; the uncommitted pool receives 4 dollars only for rented hours. Billable occupancy is rented hours divided by available hours, not GPU compute utilization. At 50 percent occupancy, the pool earns 17.94 million versus 22.43 million committed. At 62.5 percent revenue is equal; at 80 percent the pool earns 28.70 million. This comparison is before costs and assumes delivery, collectability and no credits.',{controls:[{key:'occupancy',label:'Pool hours rented',options:[[.5,'50%'],[.625,'62.5%'],[.8,'80%']]}]}),
 s('contract-financing','Why providers sign long deals','Committed revenue can help finance the GPUs.',economics,'D15.4','CoreWeave reports using asset-level debt supported by take-or-pay customer contracts. Read the arrows as funding and repayment relationships: lenders fund the provider’s hardware; customers pay for access; provider cash services the debt. The contract improves visibility, but the provider still must deliver, operate and collect. Take-or-pay describes a payment obligation for available contracted capacity, not a guarantee that any customer will always pay.',{sources:[sources.filing]}),
 ...backstopScenes,
 s('gpu-hour-cost','The GPU-hour cost','Electricity is one part of the GPU-hour cost.',economics,'D15.3','Unrented GPUs can remain powered in low-power or idle states; shutdown policy depends on the operator. Rented hours also do not imply full compute utilization. The example assumes average allocated site power of 1 kW while rented and 0.2 kW while unrented but powered, including shared equipment and cooling. These are illustrative allocations, not measured GPU specifications. Over 100 calendar hours at 80 percent occupancy, rented consumption is 80 kWh and idle consumption 4 kWh. Allocate all 84 kWh to 80 billed hours: 1.05 kWh per rented GPU-hour. At 80 dollars/MWh the cost is 0.084 dollars; at 160 it is 0.168. An all-in fixed fee exposes the provider to an unhedged electricity-price increase; contractual reimbursement can pass that expense to the customer. Other cost categories remain.',{sources:['https://docs.nvidia.com/datacenter/dps/versions/latest/guides/reference/apis/v1/devices.html','https://docs.nvidia.com/deploy/nvidia-smi/']}),
 s('abilene-roles','Abilene’s commercial chain','Who builds and operates Abilene?',delivery,'D15.5','Use the original Oracle/OpenAI campus, not the separate adjacent Microsoft development. Crusoe builds the campus, Oracle delivers OCI hardware and cloud service, and OpenAI runs workloads. The allocation makes clear that facility capacity and GPU cloud capacity are different commercial layers. Keep financing, ownership and confidential contract terms outside what these public project announcements establish.',{sources:[sources.live]}),
 s('abilene-ledger','Abilene: plan versus delivery','Abilene: the plan and the reported delivery',delivery,'D15.5','Compare the March 18 2025 plan with later reports. The initial two buildings were targeted for energization in the first half of 2025; the September 30 update reports energization within a year of June 2024, with first GB200 racks arriving in June 2025. The six-building expansion targeted construction completion in mid-2026. Oracle reports 75 percent of capacity delivered by September 2026 with the rest in subsequent quarters. Construction completion and customer delivery are different milestones: these reports do not quantify a matched schedule slip or establish operating megawatts by multiplying 75 percent by 1.2 GW.',{sources:[sources.plan,sources.live,sources.oracle]})
];
export const sceneAliases=Object.freeze({'power-boundaries':'what-is-sold','site-headroom':'what-is-sold','capacity-ledger':'what-is-sold','next-constraint':'what-is-sold','tied-constraints':'what-is-sold','useful-output':'service-boundary','ownership-boundary':'what-is-sold','energy-exposure':'gpu-hour-cost','cash-flow-timing':'contract-tenor','present-cost':'contract-tenor','cost-per-result':'billable-occupancy','upgrade-paths':'contract-financing','delivery-window':'contract-financing','upgrade-decision':'contract-financing','abilene-campus':'abilene-roles','separate-campuses':'abilene-roles','evidence-decision':'abilene-ledger'});
export function resolveSceneId(hash){let id;try{id=decodeURIComponent(hash.replace(/^#/,''));}catch{id='';}id=sceneAliases[id]||id;return scenes.some(scene=>scene.id===id)?id:scenes[0].id;}
