const ledger='d15-capacity-ledger',cost='d15-cost-per-service',decision='d15-upgrade-and-evidence';
const c=(key,label,options)=>({key,label,options});
const s=(id,label,title,reference,objective,explanation,extra={})=>({id,label,title,reference,objective,pedagogical_role:'mechanism',explanation:[explanation],...extra});
export const sources=Object.freeze({
 plan:'https://www.crusoe.ai/resources/newsroom/crusoe-expands-ai-data-center-campus-in-abilene-to-1-2-gigawatts',
 live:'https://www.crusoe.ai/resources/newsroom/crusoe-announces-flagship-abilene-data-center-is-live',
 scope:'https://www.crusoe.ai/resources/newsroom/crusoes-contracted-ai-infrastructure-capacity-approaches-5-gigawatts-across-data-centers-and-cloud',
 oracle:'https://www.oracle.com/data-centers/',
 nist:'https://nvlpubs.nist.gov/nistpubs/hb/2025/NIST.HB.135e2025.pdf',
 gao:'https://www.gao.gov/products/gao-16-89g'
});
export const learningContract=Object.freeze({driving_question:'Which change delivers more useful work, by when, and at what cost?',fixed_boundary:'The reader’s 100 MW teaching system; separately, equal facilities service over three years and a dated Abilene evidence ledger.',changed_variable:'Accepted paths, physical constraints, energy price, accepted output and delivery date.',primary_payoff:'Choose a feasible intervention using scoped costs and useful output within the delivery window.',misconception:'More announced MW or a cheaper asset automatically means more useful service for less money.',closing_question:'Which dated Abilene facts can enter the model, and which measurements would complete a forecast?'});
export const initialState={stage:'current',tieUpgrade:'none',workState:'productive',energyPrice:80,discountRate:.08,outputMillions:10,coolingDelay:1,demand:1,upgradeChoice:'',showUpgrade:false,evidenceClaim:'',evidenceNeed:'',showEvidence:false};
export const sceneAliases=Object.freeze({'power-boundaries':'site-headroom','capacity-ledger':'next-constraint','present-cost':'cash-flow-timing','upgrade-decision':'delivery-window'});
export function resolveSceneId(hash){let id;try{id=decodeURIComponent(hash.replace(/^#/,''));}catch{id='';}id=sceneAliases[id]||id;return scenes.some(scene=>scene.id===id)?id:scenes[0].id;}
export const scenes=[
 s('capacity-purpose','The investment question','Which change delivers more useful work, by when, and at what cost?',decision,'D15.4','Open with the two proposals that return later: a four-million-dollar network improvement available now and a six-million-dollar cooling improvement after one year. Ask what must be known before choosing. First use a separate 100 MW example to find the binding constraint, then compare equal facilities service costs, then return to the supplied workload gains and delivery dates. These are separate exercises, not estimates for Abilene.',{pedagogical_role:'problem'}),
 s('site-headroom','The site power budget','Spare site power cannot finish an acceptance test.',ledger,'D15.1','In this 100 MW teaching system, 520 complete rack paths have passed acceptance. At 100 kW per compute rack, compute takes 52 MW and shared network/storage takes another 5 MW: total IT is 57 MW. Plant adds 11.4 MW of load-dependent overhead and 5 MW fixed overhead. Site input is 73.4 MW, leaving 26.6 MW unused. Shared IT and fixed facility overhead happen to be equal but belong to different boundaries. These are modeled powers at the stated operating point, not metered demand. The reader retains the conversion algebra.'),
 s('next-constraint','Follow the next constraint','Removing one limit reveals the next.',ledger,'D15.1','Every bar describes how many of the same compute racks that boundary can support, after shared loads, reserve and maintenance deductions. Site, electrical, cooling, network, space and accepted-path ceilings start at 741, 650, 550, 600, 750 and 520. Populations are nested; non-nested populations require asset-level intersections. Acceptance 700 exposes cooling at 550; cooling 70 MW total IT exposes network at 600; network 800 exposes the electrical/cooling tie at 650. The reader retains each conversion.',{controls:[c('stage','Cumulative changes',[['current','Current'],['acceptance','Accept 700'],['cooling','+ Cooling 70 MW'],['network','+ Network 800']])]}),
 s('tied-constraints','Upgrade the tied limits','An electrical upgrade alone adds no usable racks.',ledger,'D15.1','Starting configuration: acceptance 700, networking 800, electrical 70 MW IT, cooling 70 MW IT. Electrical-only 80 MW leaves cooling at 650 racks; raising both to 80 MW moves the limit to 700 accepted paths. The site ceiling is still 741. The exercise evaluates complete capacities, not installation feasibility.',{controls:[c('tieUpgrade','At the 650-rack tie',[['none','No upgrade'],['electrical','Electrical → 80 MW'],['both','Electrical + cooling → 80 MW']])]}),
 s('useful-output','Capacity and progress','A powered rack can spend its time waiting.',ledger,'D15.3','Installed MW counts infrastructure, busy accelerator time counts equipment activity, and accepted results count a workload meeting its quality and timing requirement. The schematic waits for data then produces accepted work without changing powered rack count. No rate is inferred from the drawing or MW.',{controls:[c('workState','Workload condition',[['productive','Data ready'],['waiting','Waiting for data']])]}),
 s('ownership-boundary','Compare the same service','Who pays for each part of the service?',cost,'D15.2','Separate exercise: three years of identical facilities service, with identical customer compute hardware excluded from both sides. Own: twenty million initial capital, three million annual non-energy operations, energy priced at the current selected tariff, five million terminal residual. Contract: eleven million annually including the same service and energy. The base tariff is 80 dollars/MWh. Energy price carries through the ownership table, payment timeline and cost per result. These loads and prices do not describe the preceding 100 MW campus.',{pedagogical_role:'comparison'}),
 s('energy-exposure','Expose the energy assumption','A fixed service fee moves the energy-price exposure.',cost,'D15.2','Ownership energy is 50,000 MWh per year times 80 dollars per MWh, or four million dollars. Compare higher flat energy prices while the stipulated three-year service fee remains fixed at eleven million, including energy. Real tariffs, pass-throughs and escalation can change this allocation; this exercise supplies none.',{controls:[c('energyPrice','Flat energy price',[[80,'$80/MWh'],[120,'$120/MWh'],[160,'$160/MWh']])]}),
 s('cash-flow-timing','Payments and total cost','Pay now, pay each year, recover value at the end.',cost,'D15.2','Same three-year facilities comparison and selected energy price. Capital is paid now; operating and contract costs are paid at each year end; five million is recovered at the end of year three. Present cost expresses these payments in today’s dollars: a future receipt is worth less today at a positive discount rate. Show rounded totals and leave the factor calculation in the reader. At the base 80 dollars/MWh and 8% rate, ownership is 34.1 million and the contract 28.3 million. Selected rate carries into cost per result. Taxes, inflation and financing cash flows are excluded.',{pedagogical_role:'balance',controls:[c('discountRate','Annual discount rate',[[0,'0%'],[.08,'8%']])],sources:[sources.nist]}),
 s('cost-per-result','Use the useful denominator','Less accepted output makes the same bill more expensive.',cost,'D15.3','Keep the selected energy price and discount rate from the preceding comparison. Divide present facilities cost by undiscounted accepted results across the same three-year horizon. An accepted result means a job completed to the required quality and deadline. Ten million such results versus eight million raises each cost per result by 25%. Both alternatives have the same output condition. This is present cost per physical result, not revenue NPV or a discounted-output levelized metric. Identical compute hardware remains excluded.',{controls:[c('outputMillions','Accepted results in three years',[[10,'10 million'],[8,'8 million']])]}),
 s('upgrade-paths','Trace the two improvements','Each upgrade needs a route to accepted work.',decision,'D15.4','Separate original intervention brief: feasibility, acceptance and equal output quality are stipulated for both options. Network capital four million yields +80 acceptable results per operating hour immediately; cooling capital six million yields +150 after one year. 8,000 usable hours/year, three-year horizon, all increments demanded. These rates are supplied workload outcomes, not conversions of the 100 MW ledger.',{pedagogical_role:'comparison'}),
 s('delivery-window','Choose, then change the date','Which upgrade buys more extra results per dollar?',decision,'D15.4','Ask for a prediction before revealing the capital-per-result comparison. Network supplies 1.92 million extra results over three years for four million dollars. Cooling after one year supplies 2.4 million for six million: network costs less per result. Move cooling to now and ask again: cooling supplies 3.6 million and wins. Changing delivery or demand clears the previous prediction and answer. This capital-only screen excludes energy, recurring costs, discounting and residuals; it is not the preceding full facilities comparison. Halving demand doubles both ratios without changing the ranking.',{pedagogical_role:'transfer',controls:[c('coolingDelay','Cooling available',[[0,'Now'],[1,'After 1 year'],[2,'After 2 years']]),c('demand','Extra output demanded',[[1,'100%'],[.5,'50%']])],sources:[sources.gao]}),
 s('abilene-campus','Return to Abilene','What does “75% delivered” put in the ledger?',decision,'D15.5','Oracle’s Abilene section, reviewed September 16 2026, states 75% of total capacity delivered as of September 2026, with the remainder in subsequent quarters. It does not define a numeric delivery denominator suitable for calculating MW or complete buildings. The local original photograph is Oracle’s Abilene data-hall aerial captioned July 15 2026; it does not establish energization. The section-specific September update is newer than the generic January footer.',{pedagogical_role:'problem',sources:[sources.oracle]}),
 s('abilene-ledger','The dated capacity ledger','Keep the project, date and capacity state together.',decision,'D15.5','Primary sources checked September 16 2026. Crusoe March 18 2025: planned eight-building campus, total power capacity 1.2 GW. Crusoe September 30 2025: first two buildings energized within one year of June 2024 construction start; first phase live on OCI; early training/inference workloads running. Oracle September 2026: 75% total capacity delivered, denominator undefined. These overlap; they must not be added. Neither full accepted-service MW nor measured demand or output is quantified by these claims.',{pedagogical_role:'comparison',sources:[sources.plan,sources.live,sources.oracle]}),
 s('separate-campuses','Keep the projects separate','The adjacent 900 MW project has a different customer.',decision,'D15.5','Crusoe June 9 2026 distinguishes the original 1.2 GW Oracle campus, with two buildings then operational and six under construction, from the second 900 MW Microsoft campus, where ground had recently broken. Both figures are project capacities, not measured IT demand. The June building status is a dated record, not a current inventory. The later Oracle percentage belongs to the original Oracle campus; it cannot be applied to the adjacent Microsoft project.',{pedagogical_role:'counterexample',sources:[sources.scope,sources.oracle]}),
 s('evidence-decision','Complete the forecast','Which facts belong, and what must be measured?',decision,'D15.5','First classify the supported claim: 1.2 GW is the reported campus plan, not a measured operating IT load. Multiplying a delivered percentage by that figure requires a matched denominator that the claims do not define. Then name a forecast quantity and explain which evidence is needed before revealing guidance: IT power requires meters at a defined electrical boundary and time; useful output requires accepted workload results, quality and elapsed time for the same service; cost per result requires those results plus the included costs over the same horizon. The earlier teaching inputs cannot supply missing Abilene observations.',{pedagogical_role:'transfer',sources:[sources.oracle,sources.scope]})
];
