const ledger='d15-capacity-ledger',cost='d15-cost-per-service',decision='d15-upgrade-and-evidence';
const c=(key,label,options)=>({key,label,options});
const s=(id,label,title,reference,objective,explanation,extra={})=>({id,label,title,reference,objective,pedagogical_role:'mechanism',explanation:[explanation],...extra});
export const sources=Object.freeze({
 plan:'https://www.crusoe.ai/resources/newsroom/crusoe-expands-ai-data-center-campus-in-abilene-to-1-2-gigawatts',
 live:'https://www.crusoe.ai/resources/newsroom/crusoe-announces-flagship-abilene-data-center-is-live',
 scope:'https://www.crusoe.ai/resources/newsroom/crusoes-contracted-ai-infrastructure-capacity-approaches-5-gigawatts-across-data-centers-and-cloud',
 oracle:'https://www.oracle.com/data-centers/',
 nist:'https://nvlpubs.nist.gov/nistpubs/hb/2025/NIST.HB.135e2025.pdf',
 gao:'https://www.gao.gov/products/gao-16-89g'
});
export const learningContract=Object.freeze({driving_question:'Which constraint limits useful service, and which change is worth making?',fixed_boundary:'The reader’s 100 MW teaching system; separately, equal facilities service over three years and a dated Abilene evidence ledger.',changed_variable:'Accepted paths, physical constraints, energy price, accepted output and delivery date.',primary_payoff:'Choose a feasible intervention using scoped costs and useful output within the delivery window.',misconception:'More announced MW or a cheaper asset automatically means more useful service for less money.',closing_question:'Which dated Abilene facts can enter the model, and which values still need evidence?'});
export const initialState={stage:'current',tieUpgrade:'none',workState:'productive',energyPrice:80,discountRate:.08,outputMillions:10,coolingDelay:1,demand:1,upgradeChoice:'',showUpgrade:false,evidenceChoice:'',showEvidence:false};
export const scenes=[
 s('capacity-purpose','The investment question','Which change buys more useful service?',ledger,'D15.1','The 100 MW utility boundary is only one limit. This original scenario contains 750 usable positions but 520 accepted end-to-end service paths. The sequence connects feasible racks to accepted workload results, scoped cost and delivery date.',{pedagogical_role:'problem'}),
 s('power-boundaries','One power account','Two different 5 MW loads belong in different places.',ledger,'D15.1','Each compute equivalent is 100 kW. Shared network and storage are a separate 5 MW inside total IT. The facility model is Psite = 1.2 PIT + 5 MW: twenty percent load-dependent overhead plus five MW of fixed facility overhead. This is an original affine operating model, not annual PUE or a named-site estimate.'),
 s('capacity-ledger','Reconcile the limits','Every limit must describe the same racks.',ledger,'D15.1','Site 100 MW, electrical 70 MW total IT, thermal 60 MW total IT heat, network 600 equivalents, space 750, accepted paths 520. Convert power ceilings after removing the correct overhead and shared IT. Whole-equivalent ceilings are 741, 650, 550, 600, 750 and 520. Populations are nested; reserve and maintenance deductions are already included. For non-nested populations use asset-level intersections.',{pedagogical_role:'balance'}),
 s('site-headroom','Headroom at the wrong boundary','26.6 MW of site headroom cannot complete an acceptance test.',ledger,'D15.1','At the envelope of 520 compute equivalents, compute takes 52 MW, shared IT 5 MW, load-dependent overhead 11.4 MW and fixed facility overhead 5 MW. Total site input is 73.4 MW. These modeled powers apply at the stated rack operating point; capacity is not a measurement of demand.'),
 s('next-constraint','Follow the next constraint','Removing one limit reveals the next.',ledger,'D15.1','Expanded acceptance permits 700 paths, but the ceiling only rises from 520 to 550 because cooling binds. Cooling from 60 to 70 MW total IT then raises the ceiling to 600, where networking binds. Network 800 raises it to 650, tied between electrical and thermal capacities.',{controls:[c('stage','Cumulative changes',[['current','Current'],['acceptance','Accept 700'],['cooling','+ Cooling 70 MW'],['network','+ Network 800']])]}),
 s('tied-constraints','Upgrade the tied limits','An electrical upgrade alone adds no usable racks.',ledger,'D15.1','Starting configuration: acceptance 700, networking 800, electrical 70 MW IT, cooling 70 MW IT. Electrical-only 80 MW leaves cooling at 650 racks; raising both to 80 MW moves the limit to 700 accepted paths. The site ceiling is still 741. The exercise evaluates complete capacities, not installation feasibility.',{controls:[c('tieUpgrade','At the 650-rack tie',[['none','No upgrade'],['electrical','Electrical → 80 MW'],['both','Electrical + cooling → 80 MW']])]}),
 s('useful-output','Capacity and progress','A powered rack can spend its time waiting.',ledger,'D15.3','Installed MW counts infrastructure, busy accelerator time counts equipment activity, and accepted results count a workload meeting its quality and timing requirement. The schematic waits for data then produces accepted work without changing powered rack count. No rate is inferred from the drawing or MW.',{controls:[c('workState','Workload condition',[['productive','Data ready'],['waiting','Waiting for data']])]}),
 s('ownership-boundary','Compare the same service','Who pays for each part of the service?',cost,'D15.2','Separate exercise: three years of identical facilities service for one customer, with identical customer compute hardware excluded from both sides. Own: twenty million initial capital, three million annual non-energy operations, four million annual energy, five million terminal residual. Contract: eleven million annually including the same facilities service and energy. No invented relationship to the preceding 100 MW campus or its energy use.',{pedagogical_role:'comparison'}),
 s('energy-exposure','Expose the energy assumption','A fixed service fee moves the energy-price exposure.',cost,'D15.2','Ownership energy is 50,000 MWh per year times 80 dollars per MWh, or four million dollars. Compare higher flat energy prices while the stipulated three-year service fee remains fixed at eleven million, including energy. Real tariffs, pass-throughs and escalation can change this allocation; this exercise supplies none.',{controls:[c('energyPrice','Flat energy price',[[80,'$80/MWh'],[120,'$120/MWh'],[160,'$160/MWh']])]}),
 s('cash-flow-timing','Put payments on one clock','Pay now, pay each year, recover value at the end.',cost,'D15.2','Amounts in millions of dollars. Initial cost at time zero; operating and contract payments at each year end; residual receipt at end of year three. Introduce present value as future cash divided by (1+r)^t. The 8% rate is a teaching input. This unlevered comparison excludes taxes, inflation and financing cash flows; no loan principal or interest is added.',{pedagogical_role:'balance',sources:[sources.nist]}),
 s('present-cost','A three-year comparison','The same service has two different cash-flow paths.',cost,'D15.2','Base energy returns to 80 dollars/MWh. At 8%, recurring factor is 2.5771, residual PV 3.9692, ownership 34.0705 million and contract 28.3481 million. At 0% ownership is 36 and contract 33. This control changes only discounting, keeping horizon, service and cash flows fixed. The terminal residual is recovered value, not an expense or cash available today.',{controls:[c('discountRate','Annual discount rate',[[0,'0%'],[.08,'8%']])],sources:[sources.nist]}),
 s('cost-per-result','Use the useful denominator','Less accepted output makes the same bill more expensive.',cost,'D15.3','At the fixed 8% base scenario, divide present facilities cost by undiscounted accepted results across the same three-year horizon. Ten million results versus eight million gives a 25% unit-cost increase. Both alternatives have the same output condition. This is a present-cost-per-physical-result ratio, not a revenue NPV or discounted-output levelized metric; compute hardware remains outside the scope.',{controls:[c('outputMillions','Accepted results in three years',[[10,'10 million'],[8,'8 million']])]}),
 s('upgrade-paths','Trace the two improvements','Each upgrade needs a route to accepted work.',decision,'D15.4','Separate original intervention brief: feasibility, acceptance and equal output quality are stipulated for both options. Network capital four million yields +80 acceptable results per operating hour immediately; cooling capital six million yields +150 after one year. 8,000 usable hours/year, three-year horizon, all increments demanded. These rates are supplied workload outcomes, not conversions of the 100 MW ledger.',{pedagogical_role:'comparison'}),
 s('delivery-window','Change the delivery date','A later upgrade has fewer hours to repay its cost.',decision,'D15.4','The narrow capital-per-increment screening excludes energy, recurring cost, discounting and residuals. Network: 1.92 million results, $2.0833/result. Cooling after one year: 2.40 million, $2.50; immediately: 3.60 million, $1.6667. Cooling delay of 0.6 years ties the ratios. Halving demand halves realized output and doubles both unit costs without changing the ranking.',{controls:[c('coolingDelay','Cooling available',[[0,'Now'],[1,'After 1 year'],[2,'After 2 years']]),c('demand','Incremental output demanded',[[1,'100%'],[.5,'50%']])],sources:[sources.gao]}),
 s('upgrade-decision','Make a bounded decision','Which proposal passes this three-year screen?',decision,'D15.4','The fixed decision brief resets cooling delivery to after one year and demand to 100%. Network wins the supplied capital/output screen; cooling wins if available immediately. Neither ratio completes an investment decision without ongoing energy/operations and delivery risk. The incorrect MW option confuses a physical increment with accepted output.',{pedagogical_role:'transfer'}),
 s('abilene-campus','Return to Abilene','What does “75% delivered” put in the ledger?',decision,'D15.5','Oracle’s Abilene section, reviewed September 16 2026, states 75% of total capacity delivered as of September 2026, with the remainder in subsequent quarters. It does not define a numeric delivery denominator suitable for calculating MW or complete buildings. The local original photograph is Oracle’s Abilene data-hall aerial captioned July 15 2026; it does not establish energization. The section-specific September update is newer than the generic January footer.',{pedagogical_role:'problem',sources:[sources.oracle]}),
 s('abilene-ledger','The dated capacity ledger','Keep the project, date and capacity state together.',decision,'D15.5','Primary sources checked September 16 2026. Crusoe March 18 2025: planned eight-building campus, total power capacity 1.2 GW. Crusoe September 30 2025: first two buildings energized within one year of June 2024 construction start; first phase live on OCI; early training/inference workloads running. Oracle September 2026: 75% total capacity delivered, denominator undefined. These overlap; they must not be added. Neither full accepted-service MW nor measured demand or output is quantified by these claims.',{pedagogical_role:'comparison',sources:[sources.plan,sources.live,sources.oracle]}),
 s('separate-campuses','Keep the projects separate','The adjacent 900 MW project has a different customer.',decision,'D15.5','Crusoe June 9 2026 distinguishes the original 1.2 GW Oracle campus, with two buildings then operational and six under construction, from the second 900 MW Microsoft campus, where ground had recently broken. Both figures are project capacities, not measured IT demand. The June building status is a dated record, not a current inventory. The later Oracle percentage belongs to the original Oracle campus; it cannot be applied to the adjacent Microsoft project.',{pedagogical_role:'counterexample',sources:[sources.scope,sources.oracle]}),
 s('evidence-decision','Audit the proposed forecast','Can the public ledger support a cost-per-result forecast?',decision,'D15.5','A campus plan and delivered percentage cannot establish metered IT load, accepted workload output or full service economics. A defensible forecast needs a defined capacity boundary and acceptance state, workload measurements under the required service, and dated costs/obligations. The earlier teaching prices, overhead and rack powers cannot fill Abilene’s missing cells. Planned/designed capacity, permissions, energization, service acceptance and measured operation remain distinct evidence classes; no permitted-MW claim is inferred here.',{pedagogical_role:'transfer',sources:[sources.oracle,sources.scope]})
];
