import {capacityLedger,capacityStage,costComparison,usefulCost,upgradeScreen} from './capacity-model.js';
import {sources} from './capacity-scenes.js';
const money=value=>`$${value.toFixed(2)}`;
const arrow='<span class="k-arrow" aria-hidden="true">→</span>';
const metric=(value,label,kind='')=>`<div class="k-metric ${kind}"><strong>${value}</strong><span>${label}</span></div>`;
const card=(heading,copy,kind='')=>`<section class="k-card ${kind}"><h2>${heading}</h2><p>${copy}</p></section>`;
const credit=(url,label)=>`<p class="k-credit"><a href="${url}" target="_blank" rel="noreferrer">${label}</a></p>`;
const rack=()=>'<div class="k-rack" aria-hidden="true"><i></i><i></i><i></i><i></i></div>';
const inputs='<div class="k-inputs"><span>100 kW per compute rack</span><span>Shared IT: 5 MW</span><span>Same positions · reserves deducted</span></div>';

function bars(model,{raw=false}={}){
 const p=model.inputs,labels={site:`100 MW site input`,electrical:`${p.electricalMW} MW total IT`,cooling:`${p.coolingMW} MW total IT heat`,network:`${p.network} rack equivalents`,space:`${p.space} usable positions`,accepted:`${p.accepted} complete paths`};
 return `<div class="k-limit-chart" role="img" aria-label="Capacity ceilings in rack equivalents. ${model.ceilings.map(row=>`${row.label}: ${row.value}`).join('. ')}. Usable ceiling: ${model.racks}.">${model.ceilings.map(row=>`<div class="k-limit-row ${model.binding.includes(row.key)?'binding':''}"><div class="k-limit-name"><b>${row.label}</b>${raw?`<small>${labels[row.key]}</small>`:''}</div><div class="k-bar-track"><div class="k-bar-fill" style="width:${row.value/8}%"></div><span class="k-limit-marker" style="left:${model.racks/8}%"></span></div><strong>${row.value}${model.binding.includes(row.key)?'<small>LIMIT</small>':''}</strong></div>`).join('')}</div>`;
}
function boundary(){return `<div class="k-stack"><div class="k-power-boundary"><div class="k-boundary-label">Site input = 1.2 × total IT + 5 MW</div><div class="k-boundary-parts"><section class="k-it-boundary"><span>Total IT</span><div class="k-two"><div class="k-compute">${rack()}<b>Compute racks</b><p>100 kW × rack count</p></div><div class="k-shared"><div class="k-server" aria-hidden="true">▤<br>▤</div><b>Network + storage</b><strong>5 MW</strong></div></div></section><section class="k-facility"><div><b>Load-dependent overhead</b><strong>0.2 × total IT</strong></div><div><b>Fixed facility overhead</b><strong>5 MW</strong></div></section></div></div><div class="k-equation">Compute power available = total IT power − <b>5 MW</b></div></div>`;}
function headroom(){const m=capacityLedger();return `<div class="k-stack"><div class="k-two k-headroom-intro">${metric('520 racks','Accepted end-to-end paths')}${metric(`${m.siteMW.toFixed(1)} MW`,'Site input at the 100 kW/rack operating point')}</div><div class="k-power-bar" role="img" aria-label="Of 100 MW site input: compute 52, shared IT 5, variable overhead 11.4, fixed overhead 5, unused headroom 26.6 MW.">${[[52,'compute'],[5,'shared'],[11.4,'variable'],[5,'fixed'],[26.6,'unused']].map(([value,cls])=>`<div class="${cls}" style="flex:${value}">${value>=20?`${value} MW`:''}</div>`).join('')}</div><div class="k-power-key">${[['Compute','52 MW','compute'],['Shared IT','5 MW','shared'],['Variable overhead','11.4 MW','variable'],['Fixed overhead','5 MW','fixed'],['Site headroom','26.6 MW','unused']].map(([name,value,cls])=>`<div><i class="${cls}"></i><span>${name}<b>${value}</b></span></div>`).join('')}</div><div class="k-verdict">More upstream power leaves the same <strong>520 accepted paths.</strong></div></div>`;}
function nextConstraint(state){const m=capacityStage(state.stage),feedback={current:'Accepted paths limit the first release.',acceptance:'180 more accepted paths unlock only 30 more racks: cooling binds.',cooling:'10 MW more cooling unlocks 50 more racks: networking binds.',network:'Electrical and cooling now both limit the system to 650 racks.'};return `<div class="k-stack">${inputs}${bars(m)}<div class="k-ceiling">${metric(`${m.racks} racks`,'Common feasible ceiling')}<p>${feedback[state.stage]}</p></div></div>`;}
function tied(state){const m=capacityLedger({accepted:700,network:800,coolingMW:state.tieUpgrade==='both'?80:70,electricalMW:state.tieUpgrade==='none'?70:80});return `<div class="k-stack"><div class="k-inputs"><span>Accepted paths: 700</span><span>Network: 800</span><span>Site: 741</span><span>Space: 750</span></div><div class="k-two k-tie">${card(`Electrical: ${m.inputs.electricalMW} MW IT`,`${m.ceilings[1].value} compute racks`,m.binding.includes('electrical')?'warning':'')}${card(`Cooling: ${m.inputs.coolingMW} MW IT`,`${m.ceilings[2].value} compute racks`,m.binding.includes('cooling')?'warning':'')}</div><div class="k-tie-join"><span></span><b>Both must serve the same racks</b><span></span></div><div class="k-ceiling">${metric(`${m.racks} racks`,'Feasible ceiling')}<p>${state.tieUpgrade==='both'?'The next release is limited by 700 accepted paths.':state.tieUpgrade==='electrical'?'Cooling still stops at 650. The extra electrical capacity waits.':'Two boundaries tie at 650. Both need to change.'}</p></div></div>`;}
function output(state){const waiting=state.workState==='waiting';return `<div class="k-stack"><div class="k-output-path"><section><div class="k-storage" aria-hidden="true">▤</div><h2>Storage</h2><p>${waiting?'Required data is late':'Data ready for this job'}</p></section><div class="k-flow ${waiting?'blocked':''}">${waiting?'WAIT':'→'}</div><section>${rack()}<h2>Same powered racks</h2><p>${waiting?'Waiting for input':'Doing the required work'}</p></section>${arrow}<section class="k-work-output ${waiting?'waiting':''}"><div class="k-results" aria-hidden="true">${Array.from({length:6},()=>`<i>${waiting?'—':'✓'}</i>`).join('')}</div><h2>Accepted results</h2><p>Required quality + completion time</p></section></div><div class="k-three k-denominators">${card('Cost per MW','Infrastructure capacity')}${card('Cost per accelerator-hour','Equipment time')}${card('Cost per accepted result','Useful service', 'positive')}</div></div>`;}
function ownership(){return `<div class="k-stack"><div class="k-scope">Same facilities service · 3 years <span>Customer compute hardware excluded from both</span></div><div class="k-ownership-table"><div class="k-table-head"><span>Customer pays</span><b>Own the facility</b><b>Buy the service</b></div><div><b>Capital now</b><span>$20m</span><span>Included in fee</span></div><div><b>Operations / year</b><span>$3m</span><span class="k-included">Included</span></div><div><b>Energy / year</b><span>$4m</span><span class="k-included">Included</span></div><div><b>Service fee / year</b><span>—</span><strong>$11m</strong></div><div><b>Recovered at year 3</b><strong>$5m residual</strong><span>—</span></div></div></div>`;}
function energy(state){const m=costComparison({energyPrice:state.energyPrice});return `<div class="k-stack"><div class="k-energy-equation"><div><strong>50,000</strong><span>MWh / year</span></div><b>×</b><div><strong>$${state.energyPrice}</strong><span>per MWh</span></div><b>=</b><div><strong>$${m.energyMillions}m</strong><span>annual energy cost</span></div></div><div class="k-two"><section class="k-bill"><h2>Own</h2><div><span>Non-energy operations</span><b>$3m</b></div><div><span>Energy</span><b>$${m.energyMillions}m</b></div><div class="k-bill-total"><span>Annual operating cost</span><strong>$${m.annualMillions}m</strong></div></section><section class="k-bill fixed-fee"><h2>Contract</h2><div><span>Facilities + energy</span><b>Included</b></div><div><span>Fee fixed for 3 years</span><b>No pass-through</b></div><div class="k-bill-total"><span>Annual service fee</span><strong>$11m</strong></div></section></div></div>`;}
function timing(){return `<div class="k-stack"><div class="k-cash-table"><div class="k-cash-row k-cash-header"><b>$ millions</b><span>Now</span><span>Year 1</span><span>Year 2</span><span>Year 3</span></div><div class="k-cash-row"><b>Own: pay</b><strong>20</strong><span>7</span><span>7</span><span>7</span></div><div class="k-cash-row k-receipt"><b>Own: recover</b><span>—</span><span>—</span><span>—</span><strong>5</strong></div><div class="k-cash-row"><b>Contract: pay</b><span>—</span><span>11</span><span>11</span><span>11</span></div></div><div class="k-discount"><div><h2>Put a future dollar in today’s terms</h2><p>Present value = future cash ÷ (1 + <b>r</b>)<sup>t</sup></p><small>r = 8% per year · t = years from now · payments at year end</small></div><div>${metric('$3.97m','Today’s value of the $5m year-3 receipt')}<p>5 ÷ 1.08³</p></div></div>${credit(sources.nist,'Present-value method: NIST Handbook 135, 2025 · teaching rate: 8%')}</div>`;}
function present(state){const m=costComparison({rate:state.discountRate});return `<div class="k-stack"><div class="k-inputs"><span>3 years · same facilities service</span><span>Own: $20m now + $7m/year − $5m residual</span><span>Contract: $11m/year</span></div><div class="k-pv-compare"><section><h2>Own</h2><div class="k-pv-bar" style="width:${m.ownPV/40*100}%"><strong>${money(m.ownPV)}m</strong></div><div class="k-pv-equation">20 + ${(7*m.recurringFactor).toFixed(2)} − <b>${m.residualPV.toFixed(2)}</b></div><p>Capital + recurring costs − recovered value</p></section><section><h2>Contract</h2><div class="k-pv-bar contract" style="width:${m.contractPV/40*100}%"><strong>${money(m.contractPV)}m</strong></div><div class="k-pv-equation">11 × ${m.recurringFactor.toFixed(4)}</div><p>Three annual fees, discounted to today</p></section></div><div class="k-ceiling">${metric(`${money(m.savingMillions)}m`,'Lower present cost for the contract')}<p>Ownership retains residual value and operating-cost exposure.</p></div></div>`;}
function unitCost(state){const m=costComparison(),own=usefulCost({costMillions:m.ownPV,resultsMillions:state.outputMillions}),contract=usefulCost({costMillions:m.contractPV,resultsMillions:state.outputMillions});return `<div class="k-stack"><div class="k-result-blocks" role="img" aria-label="${state.outputMillions} million accepted results out of the ten-million-result comparison.">${Array.from({length:10},(_,i)=>`<div class="${i<state.outputMillions?'accepted':'lost'}"><b>${i<state.outputMillions?'✓':'—'}</b><span>1m</span></div>`).join('')}</div><div class="k-inputs"><span>Same quality + completion requirement</span><span>3-year accepted output</span><span>Facilities present cost fixed at 8%</span></div><div class="k-two k-unit-cost">${metric(`${money(own.perResult)}/result`,`Own · ${money(m.ownPV)}m present cost`)}${metric(`${money(contract.perResult)}/result`,`Contract · ${money(m.contractPV)}m present cost`)}</div><div class="k-verdict">${state.outputMillions===8?'<strong>20% less output → 25% higher cost per result.</strong>':'Each accepted result carries a share of the same facilities cost.'}</div></div>`;}
function upgradePaths(){return `<div class="k-stack"><div class="k-scope">Same accepted result · both revised service paths proven</div><div class="k-two k-proposals"><section><h2>Network · $4m</h2><div class="k-mechanism"><span>Less time<br>waiting on traffic</span>${arrow}<strong>+80<br><small>results / hour</small></strong></div><div class="k-available">Available now</div></section><section><h2>Cooling · $6m</h2><div class="k-mechanism"><span>More supported<br>workload</span>${arrow}<strong>+150<br><small>results / hour</small></strong></div><div class="k-available later">Available after 1 year</div></section></div><div class="k-inputs"><span>8,000 usable hours / year</span><span>3-year opportunity</span><span>Every extra result demanded</span></div></div>`;}
function delivery(state){const m=upgradeScreen({coolingDelay:state.coolingDelay,demand:state.demand});return `<div class="k-stack k-delivery"><div class="k-inputs"><span>3 years · 8,000 usable hours/year</span><span>Network: $4m · +80 results/h</span><span>Cooling: $6m · +150 results/h</span></div><div class="k-output-calendar"><div class="k-year-labels"><span></span><b>Year 1</b><b>Year 2</b><b>Year 3</b></div>${[['Network',m.network],['Cooling',m.cooling]].map(([name,option])=>`<div class="k-calendar-row"><b>${name}</b>${Array.from({length:3},(_,year)=>`<div class="${year>=option.delay?'producing':'not-ready'}">${year>=option.delay?`<strong>${(option.rate*8000*m.demand/1e6).toFixed(2)}m</strong><span>extra results</span>`:'Awaiting delivery'}</div>`).join('')}</div>`).join('')}</div><div class="k-screen-results">${[['Network',m.network],['Cooling',m.cooling]].map(([name,option])=>`<div class="${m.preferred===name.toLowerCase()?'preferred':''}"><b>${name}</b><span>${(option.results/1e6).toFixed(2)}m extra results</span><strong>${money(option.perResult)} / result</strong></div>`).join('')}</div><div class="k-screen-scope"><b>${m.preferred==='network'?'Network':'Cooling'} has the lower capital per extra result.</b><span>Capital-only screen · ongoing costs and discounting excluded</span></div></div>`;}
function upgradeDecision(state){const feedback={network:'Network passes this screen: $2.08 per extra result versus $2.50. Reconsider if cooling can arrive sooner; then compare ongoing cost and delivery risk.',cooling:'The higher hourly gain runs for only two years. It delivers more extra results, but costs $2.50 each versus $2.08 for network.',power:'A power increase has no supplied route to more accepted output. First identify the constraint and prove the workload gain.'};return `<div class="k-decision"><section class="k-brief"><h2>Decision brief</h2><p>3 years · 8,000 usable hours/year</p><p>All extra results demanded</p><dl><dt>Network</dt><dd>$4m · +80 results/h · now</dd><dt>Cooling</dt><dd>$6m · +150 results/h · after 1 year</dd></dl><strong>Choose the lower capital per extra result.</strong></section><section class="k-answer"><div class="k-answer-choices">${[['network','Fund network in this screen.'],['cooling','Fund cooling for its larger hourly gain.'],['power','Fund more site MW before either proposal.']].map(([key,label])=>`<button data-upgrade-choice="${key}" aria-pressed="${state.upgradeChoice===key}">${label}</button>`).join('')}</div><button id="upgrade-reveal" aria-expanded="${state.showUpgrade}" ${state.upgradeChoice?'':'disabled'}>${state.showUpgrade?'Hide feedback':'Check decision'}</button><p class="k-feedback" role="status">${state.showUpgrade?feedback[state.upgradeChoice]:''}</p></section></div>`;}
function abilene(){return `<div class="k-case"><figure><img src="../assets/references/distribution-abilene-data-halls.jpg" alt="Oracle aerial photograph of the Abilene data halls, captioned July 15, 2026."><figcaption><a href="${sources.oracle}" target="_blank" rel="noreferrer">Abilene data halls · Oracle · 15 July 2026</a></figcaption></figure><section><div class="k-date">Oracle · September 2026</div><div class="k-case-number">75%<span>of total capacity delivered</span></div><p>Original Oracle / OpenAI campus</p><div class="k-missing">Delivery denominator?<br>Accepted IT service?<br>Measured useful output?</div></section></div>`;}
function evidenceLedger(){const entries=[['18 Mar 2025','Planned campus','1.2 GW · 8 buildings',sources.plan,'Crusoe'],['30 Sep 2025','Energized','First 2 buildings',sources.live,'Crusoe'],['30 Sep 2025','Workloads running','Early training + inference',sources.live,'Crusoe'],['Sep 2026','Delivered','75% of total capacity',sources.oracle,'Oracle']];return `<div class="k-stack"><div class="k-scope">Original Oracle / OpenAI campus · dated publisher reports</div><div class="k-evidence-ledger">${entries.map(([date,state,value,url,publisher])=>`<div><time>${date}<small>${publisher}</small></time><b>${state}</b><span>${value}</span><a href="${url}" target="_blank" rel="noreferrer" aria-label="${publisher} source for ${state}">Source ↗</a></div>`).join('')}</div><div class="k-unreported"><b>Still unquantified in these claims</b><span>Accepted service MW · metered IT demand · accepted results</span></div><p class="k-credit">Primary records checked 16 September 2026 · the rows overlap; they are not additive phases.</p></div>`;}
function campusScope(){return `<div class="k-stack"><div class="k-date">Crusoe · 9 June 2026</div><div class="k-two k-campus-pair"><section><h2>Original campus</h2><div class="k-campus-buildings" aria-hidden="true">${Array.from({length:8},(_,i)=>`<i class="${i<2?'complete':''}"></i>`).join('')}</div><strong>1.2 GW project</strong><b>Oracle</b><p>2 buildings operational<br>6 under construction at that date</p></section><section><h2>Adjacent campus</h2><div class="k-campus-buildings adjacent" aria-hidden="true"><i></i><i></i></div><strong>900 MW project</strong><b>Microsoft</b><p>Ground recently broken<br>A separate development</p></section></div>${credit(sources.scope,'Crusoe · June 9, 2026 project update')}<div class="k-verdict">Oracle’s later <strong>75% delivered</strong> statement belongs to the original campus.</div></div>`;}
function evidenceDecision(state){const feedback={multiply:'Multiplying 75% by a headline campus rating assumes the delivery denominator and electrical boundary match. The records do not establish that match or measured IT load.',borrow:'The teaching overhead, workload rates and prices describe separate exercises. They cannot supply Abilene’s unknown configuration, output or commercial terms.',measure:'Yes. Retain the dated claims, then obtain the delivery boundary, accepted paths, workload results and scoped costs for the same configuration and period.'};return `<div class="k-decision"><section class="k-brief"><h2>The proposed forecast</h2><p>Campus plan: 1.2 GW</p><p>Oracle report: 75% delivered</p><div class="k-unknown-cells"><span>Accepted IT MW <b>?</b></span><span>Results per hour <b>?</b></span><span>Cost per result <b>?</b></span></div><strong>What belongs in the next model revision?</strong></section><section class="k-answer"><div class="k-answer-choices">${[['multiply','Use 75% of 1.2 GW as operating IT power.'],['borrow','Fill the gaps with the teaching workload and costs.'],['measure','Keep the gaps; obtain matched service, output and cost evidence.']].map(([key,label])=>`<button data-evidence-choice="${key}" aria-pressed="${state.evidenceChoice===key}">${label}</button>`).join('')}</div><button id="evidence-reveal" aria-expanded="${state.showEvidence}" ${state.evidenceChoice?'':'disabled'}>${state.showEvidence?'Hide feedback':'Check the ledger'}</button><p class="k-feedback" role="status">${state.showEvidence?feedback[state.evidenceChoice]:''}</p></section></div>`;}

export function capacityVisual(id,state){switch(id){
 case 'capacity-purpose':return `<div class="k-stack"><div class="k-opening"><section><div class="k-substation" aria-hidden="true">ϟ</div>${metric('100 MW','Site power limit')}</section>${arrow}<section><div class="k-rack-group" aria-hidden="true">${rack()}${rack()}${rack()}</div>${metric('520 racks','Accepted service paths')}</section>${arrow}<section><div class="k-question">?</div><h2>Useful results<br>within the opportunity</h2></section></div><div class="k-decision-chain"><span>Constraint</span>${arrow}<span>Accepted output</span>${arrow}<span>Scoped cost</span>${arrow}<span>Delivery date</span></div></div>`;
 case 'power-boundaries':return boundary();
 case 'capacity-ledger':return `<div class="k-stack">${inputs}${bars(capacityLedger(),{raw:true})}<div class="k-ledger-formulas"><span>Site: ((100 − 5) ÷ 1.2 − 5) ÷ 0.1 → <b>741</b></span><span>Cooling: (60 − 5) ÷ 0.1 = <b>550</b></span></div></div>`;
 case 'site-headroom':return headroom();
 case 'next-constraint':return nextConstraint(state);
 case 'tied-constraints':return tied(state);
 case 'useful-output':return output(state);
 case 'ownership-boundary':return ownership();
 case 'energy-exposure':return energy(state);
 case 'cash-flow-timing':return timing();
 case 'present-cost':return present(state);
 case 'cost-per-result':return unitCost(state);
 case 'upgrade-paths':return upgradePaths();
 case 'delivery-window':return delivery(state);
 case 'upgrade-decision':return upgradeDecision(state);
 case 'abilene-campus':return abilene();
 case 'abilene-ledger':return evidenceLedger();
 case 'separate-campuses':return campusScope();
 case 'evidence-decision':return evidenceDecision(state);
 default:throw new Error(`Unknown capacity scene: ${id}`);
}}
