import {capacityLedger,capacityStage,costComparison,usefulCost,upgradeScreen} from './capacity-model.js';
import {sources} from './capacity-scenes.js';
const money=value=>`$${value.toFixed(2)}`;
const arrow='<span class="k-arrow" aria-hidden="true">→</span>';
const metric=(value,label,kind='')=>`<div class="k-metric ${kind}"><strong>${value}</strong><span>${label}</span></div>`;
const card=(heading,copy,kind='')=>`<section class="k-card ${kind}"><h2>${heading}</h2><p>${copy}</p></section>`;
const credit=(url,label)=>`<p class="k-credit"><a href="${url}" target="_blank" rel="noreferrer">${label}</a></p>`;
const rack=()=>'<div class="k-rack" aria-hidden="true"><i></i><i></i><i></i><i></i></div>';
const inputs='<div class="k-inputs"><span>Rack limits · larger sets include smaller sets</span><span>100 kW/rack · reserves deducted</span></div>';

function bars(model,{raw=false}={}){
 const p=model.inputs,labels={site:`100 MW site input`,electrical:`${p.electricalMW} MW total IT`,cooling:`${p.coolingMW} MW total IT heat`,network:`${p.network} rack equivalents`,space:`${p.space} usable positions`,accepted:`${p.accepted} complete paths`};
 return `<div class="k-limit-chart" role="img" aria-label="Capacity ceilings in rack equivalents. ${model.ceilings.map(row=>`${row.label}: ${row.value}`).join('. ')}. Usable ceiling: ${model.racks}.">${model.ceilings.map(row=>`<div class="k-limit-row ${model.binding.includes(row.key)?'binding':''}"><div class="k-limit-name"><b>${row.label}</b>${raw?`<small>${labels[row.key]}</small>`:''}</div><div class="k-bar-track"><div class="k-bar-fill" style="width:${row.value/8}%"></div><span class="k-limit-marker" style="left:${model.racks/8}%"></span></div><strong>${row.value}${model.binding.includes(row.key)?'<small>LIMIT</small>':''}</strong></div>`).join('')}</div>`;
}
function headroom(){const m=capacityLedger();return `<div class="k-stack"><div class="k-two k-headroom-intro">${metric('520 racks','Complete paths that passed acceptance')}${metric(`${m.siteMW.toFixed(1)} MW`,'Of a 100 MW site limit · 100 kW per compute rack')}</div><div class="k-power-bar" role="img" aria-label="Of 100 MW site input: compute 52, network and storage 5, load-dependent facility overhead 11.4, fixed facility overhead 5, unused headroom 26.6 MW.">${[[52,'compute'],[5,'shared'],[11.4,'variable'],[5,'fixed'],[26.6,'unused']].map(([value,cls])=>`<div class="${cls}" style="flex:${value}">${value>=20?`${value} MW`:''}</div>`).join('')}</div><div class="k-power-key">${[['Compute','52 MW','compute'],['Network + storage','5 MW','shared'],['Load-dependent plant','11.4 MW','variable'],['Fixed plant','5 MW','fixed'],['Unused site power','26.6 MW','unused']].map(([name,value,cls])=>`<div><i class="${cls}"></i><span>${name}<b>${value}</b></span></div>`).join('')}</div><p class="k-boundary-note">Total IT includes compute, network and storage. Facility overhead is added outside IT.</p><div class="k-verdict">More site power still leaves only <strong>520 accepted rack paths.</strong></div></div>`;}
function nextConstraint(state){const m=capacityStage(state.stage),feedback={current:'Accepted paths limit the first release.',acceptance:'180 more accepted paths unlock only 30 more racks: cooling binds.',cooling:'10 MW more cooling unlocks 50 more racks: networking binds.',network:'Electrical and cooling now both limit the system to 650 racks.'};return `<div class="k-stack">${inputs}${bars(m)}<div class="k-ceiling">${metric(`${m.racks} racks`,'Common feasible ceiling')}<p>${feedback[state.stage]}</p></div></div>`;}
function tied(state){const m=capacityLedger({accepted:700,network:800,coolingMW:state.tieUpgrade==='both'?80:70,electricalMW:state.tieUpgrade==='none'?70:80});return `<div class="k-stack"><div class="k-inputs"><span>Accepted paths: 700</span><span>Network: 800</span><span>Site: 741</span><span>Space: 750</span></div><div class="k-two k-tie">${card(`Electrical: ${m.inputs.electricalMW} MW IT`,`${m.ceilings[1].value} compute racks`,m.binding.includes('electrical')?'warning':'')}${card(`Cooling: ${m.inputs.coolingMW} MW IT`,`${m.ceilings[2].value} compute racks`,m.binding.includes('cooling')?'warning':'')}</div><div class="k-tie-join"><span></span><b>Both must serve the same racks</b><span></span></div><div class="k-ceiling">${metric(`${m.racks} racks`,'Feasible ceiling')}<p>${state.tieUpgrade==='both'?'The next release is limited by 700 accepted paths.':state.tieUpgrade==='electrical'?'Cooling still stops at 650. The extra electrical capacity waits.':'Two boundaries tie at 650. Both need to change.'}</p></div></div>`;}
function output(state){const waiting=state.workState==='waiting';return `<div class="k-stack"><div class="k-output-path"><section><div class="k-storage" aria-hidden="true">▤</div><h2>Storage</h2><p>${waiting?'Required data is late':'Data ready for this job'}</p></section><div class="k-flow ${waiting?'blocked':''}">${waiting?'WAIT':'→'}</div><section>${rack()}<h2>Same powered racks</h2><p>${waiting?'Waiting for input':'Doing the required work'}</p></section>${arrow}<section class="k-work-output ${waiting?'waiting':''}"><div class="k-results" aria-hidden="true">${Array.from({length:6},()=>`<i>${waiting?'—':'✓'}</i>`).join('')}</div><h2>Accepted results</h2><p>Jobs meeting the quality and deadline</p></section></div><div class="k-three k-denominators">${card('Cost per MW','Infrastructure capacity')}${card('Cost per accelerator-hour','Equipment time')}${card('Cost per accepted result','Useful service', 'positive')}</div></div>`;}
function ownership(state){const m=costComparison({energyPrice:state.energyPrice,rate:state.discountRate});return `<div class="k-stack"><div class="k-scope">Same facilities service · 3 years <span>Customer compute hardware excluded from both</span></div><div class="k-ownership-table"><div class="k-table-head"><span>Customer pays</span><b>Own the facility</b><b>Buy the service</b></div><div><b>Capital now</b><span>$20m</span><span>Included in fee</span></div><div><b>Operations / year</b><span>$3m</span><span class="k-included">Included</span></div><div><b>Energy / year</b><span>$${m.energyMillions}m <small>at $${state.energyPrice}/MWh</small></span><span class="k-included">Included</span></div><div><b>Service fee / year</b><span>—</span><strong>$11m</strong></div><div><b>Recovered at year 3</b><strong>$5m residual</strong><span>—</span></div></div></div>`;}
function energy(state){const m=costComparison({energyPrice:state.energyPrice});return `<div class="k-stack"><div class="k-energy-equation"><div><strong>50,000</strong><span>MWh / year</span></div><b>×</b><div><strong>$${state.energyPrice}</strong><span>per MWh</span></div><b>=</b><div><strong>$${m.energyMillions}m</strong><span>annual energy cost</span></div></div><div class="k-two"><section class="k-bill"><h2>Own</h2><div><span>Non-energy operations</span><b>$3m</b></div><div><span>Energy</span><b>$${m.energyMillions}m</b></div><div class="k-bill-total"><span>Annual operating cost</span><strong>$${m.annualMillions}m</strong></div></section><section class="k-bill fixed-fee"><h2>Contract</h2><div><span>Facilities + energy</span><b>Included</b></div><div><span>Fee fixed for 3 years</span><b>No pass-through</b></div><div class="k-bill-total"><span>Annual service fee</span><strong>$11m</strong></div></section></div></div>`;}
function timing(state){const m=costComparison({energyPrice:state.energyPrice,rate:state.discountRate});return `<div class="k-stack k-timing"><div class="k-inputs"><span>Same facilities service · 3 years</span><span>Energy: $${state.energyPrice}/MWh</span><span>Compute hardware excluded</span></div><div class="k-cash-table"><div class="k-cash-row k-cash-header"><b>$ millions</b><span>Now</span><span>Year 1</span><span>Year 2</span><span>Year 3</span></div><div class="k-cash-row"><b>Own: pay</b><strong>20</strong><span>${m.annualMillions}</span><span>${m.annualMillions}</span><span>${m.annualMillions}</span></div><div class="k-cash-row k-receipt"><b>Own: recover</b><span>—</span><span>—</span><span>—</span><strong>5</strong></div><div class="k-cash-row"><b>Contract: pay</b><span>—</span><span>11</span><span>11</span><span>11</span></div></div><div class="k-two k-present-totals">${metric(`$${m.ownPV.toFixed(1)}m`,'Own · total cost in today’s dollars')}${metric(`$${m.contractPV.toFixed(1)}m`,'Contract · total cost in today’s dollars')}</div><p class="k-time-explanation">${state.discountRate===0?'At 0%, payments count equally whenever they occur.':'At 8%, future payments and recovered value count less in today’s dollars.'}</p>${credit(sources.nist,'Method: NIST Handbook 135 · year-end payments · calculation in the reader')}</div>`;}
function unitCost(state){const m=costComparison({energyPrice:state.energyPrice,rate:state.discountRate}),own=usefulCost({costMillions:m.ownPV,resultsMillions:state.outputMillions}),contract=usefulCost({costMillions:m.contractPV,resultsMillions:state.outputMillions});return `<div class="k-stack"><div class="k-result-blocks" role="img" aria-label="${state.outputMillions} million accepted results out of the ten-million-result comparison.">${Array.from({length:10},(_,i)=>`<div class="${i<state.outputMillions?'accepted':'lost'}"><b>${i<state.outputMillions?'✓':'—'}</b><span>1m</span></div>`).join('')}</div><div class="k-inputs"><span>Jobs meeting the quality and deadline</span><span>3 years · energy $${state.energyPrice}/MWh · rate ${state.discountRate*100}%</span></div><div class="k-two k-unit-cost">${metric(`${money(own.perResult)}/result`,`Own · $${m.ownPV.toFixed(1)}m present cost`)}${metric(`${money(contract.perResult)}/result`,`Contract · $${m.contractPV.toFixed(1)}m present cost`)}</div><div class="k-verdict">${state.outputMillions===8?'<strong>20% less output → 25% higher cost per result.</strong>':'Each accepted result carries a share of the same facilities cost.'}</div></div>`;}
function upgradePaths(){return `<div class="k-stack"><div class="k-scope">Same accepted result · both revised service paths proven</div><div class="k-two k-proposals"><section><h2>Network · $4m</h2><div class="k-mechanism"><span>Less time<br>waiting on traffic</span>${arrow}<strong>+80<br><small>results / hour</small></strong></div><div class="k-available">Available now</div></section><section><h2>Cooling · $6m</h2><div class="k-mechanism"><span>More supported<br>workload</span>${arrow}<strong>+150<br><small>results / hour</small></strong></div><div class="k-available later">Available after 1 year</div></section></div><div class="k-inputs"><span>8,000 usable hours / year</span><span>3-year opportunity</span><span>Every extra result demanded</span></div></div>`;}
function delivery(state){const m=upgradeScreen({coolingDelay:state.coolingDelay,demand:state.demand}),revealed=state.showUpgrade&&Boolean(state.upgradeChoice),winner=m.preferred==='network'?'Network':'Cooling';return `<div class="k-stack k-delivery"><div class="k-inputs"><span>3 years · 8,000 usable hours/year</span><span>Network: $4m · +80 results/h</span><span>Cooling: $6m · +150 results/h</span></div><div class="k-output-calendar"><div class="k-year-labels"><span></span><b>Year 1</b><b>Year 2</b><b>Year 3</b></div>${[['Network',m.network],['Cooling',m.cooling]].map(([name,option])=>`<div class="k-calendar-row"><b>${name}</b>${Array.from({length:3},(_,year)=>`<div class="${year>=option.delay?'producing':'not-ready'}">${year>=option.delay?`<strong>${(option.rate*8000*m.demand/1e6).toFixed(2)}m</strong><span>extra results</span>`:'Awaiting delivery'}</div>`).join('')}</div>`).join('')}</div><div class="k-prediction" role="group" aria-label="Predict the lower capital cost per extra result"><span>Lower capital per result?</span>${[['network','Network'],['cooling','Cooling']].map(([key,label])=>`<button data-upgrade-choice="${key}" aria-pressed="${state.upgradeChoice===key}">${label}</button>`).join('')}<button id="upgrade-reveal" aria-expanded="${revealed}" ${state.upgradeChoice?'':'disabled'}>${revealed?'Hide comparison':'Check prediction'}</button></div>${revealed?`<div class="k-screen-results" data-upgrade-preferred="${m.preferred}">${[['Network',m.network],['Cooling',m.cooling]].map(([name,option])=>`<div class="${m.preferred===name.toLowerCase()?'preferred':''}"><b>${name}</b><span>${(option.results/1e6).toFixed(2)}m extra results</span><strong>${money(option.perResult)} / result</strong></div>`).join('')}</div>`:'<p class="k-prediction-prompt">Choose an upgrade, then compare its cost with all the extra results it delivers.</p>'}<div class="k-screen-scope"><b role="status">${revealed?`${state.upgradeChoice===m.preferred?'Yes.':'Reconsider.'} ${winner} has the lower capital per extra result.`:'Change the delivery date and make a new prediction.'}</b><span>Capital only · ongoing costs and discounting excluded</span></div></div>`;}
function abilene(){return `<div class="k-case"><figure><img src="../assets/references/distribution-abilene-data-halls.jpg" alt="Oracle aerial photograph of the Abilene data halls, captioned July 15, 2026."><figcaption><a href="${sources.oracle}" target="_blank" rel="noreferrer">Abilene data halls · Oracle · 15 July 2026</a></figcaption></figure><section><div class="k-date">Oracle · September 2026</div><div class="k-case-number">75%<span>of total capacity delivered</span></div><p>Original Oracle / OpenAI campus</p><div class="k-missing">Delivery denominator?<br>Accepted IT service?<br>Measured useful output?</div></section></div>`;}
function evidenceLedger(){const entries=[['18 Mar 2025','Planned campus','1.2 GW · 8 buildings',sources.plan,'Crusoe'],['30 Sep 2025','Energized','First 2 buildings',sources.live,'Crusoe'],['30 Sep 2025','Workloads running','Early training + inference',sources.live,'Crusoe'],['Sep 2026','Delivered','75% of total capacity',sources.oracle,'Oracle']];return `<div class="k-stack"><div class="k-scope">Original Oracle / OpenAI campus · dated publisher reports</div><div class="k-evidence-ledger">${entries.map(([date,state,value,url,publisher])=>`<div><time>${date}<small>${publisher}</small></time><b>${state}</b><span>${value}</span><a href="${url}" target="_blank" rel="noreferrer" aria-label="${publisher} source for ${state}">Source ↗</a></div>`).join('')}</div><div class="k-unreported"><b>Still unquantified in these claims</b><span>Accepted service MW · metered IT demand · accepted results</span></div><p class="k-credit">Primary records checked 16 September 2026 · the rows overlap; they are not additive phases.</p></div>`;}
function campusScope(){return `<div class="k-stack"><div class="k-date">Crusoe · 9 June 2026</div><div class="k-two k-campus-pair"><section><h2>Original campus</h2><div class="k-campus-buildings" aria-hidden="true">${Array.from({length:8},(_,i)=>`<i class="${i<2?'complete':''}"></i>`).join('')}</div><strong>1.2 GW project</strong><b>Oracle</b><p>2 buildings operational<br>6 under construction at that date</p></section><section><h2>Adjacent campus</h2><div class="k-campus-buildings adjacent" aria-hidden="true"><i></i><i></i></div><strong>900 MW project</strong><b>Microsoft</b><p>Ground recently broken<br>A separate development</p></section></div>${credit(sources.scope,'Crusoe · June 9, 2026 project update')}<div class="k-verdict">Oracle’s later <strong>75% delivered</strong> statement belongs to the original campus.</div></div>`;}
function evidenceDecision(state){const ready=Boolean(state.evidenceClaim&&state.evidenceNeed),revealed=ready&&state.showEvidence,claim=state.evidenceClaim==='plan'?'The 1.2 GW plan belongs in the dated ledger. It does not establish operating IT demand.':'900 MW is not established as operating IT demand: the 75% delivery denominator is not defined. Retain the 1.2 GW plan as a dated claim.',needs={power:'Request metered IT power with its electrical boundary and time period. Acceptance records separately show which complete service paths are ready.',output:'Request completed jobs, their quality and deadline checks, and elapsed time for the same service. MW alone cannot supply this rate.',cost:'Request the included capital and operating costs, recovered value, and accepted results for the same service and horizon. The teaching prices cannot fill these cells.'};return `<div class="k-stack k-evidence-task"><div class="k-evidence-questions"><section><h2>1 · Which entry is supported?</h2><p>Campus plan: 1.2 GW<br>Oracle report: 75% delivered</p><div class="k-answer-choices">${[['plan','Planned campus capacity: 1.2 GW'],['operating','Operating IT demand: 900 MW']].map(([key,label])=>`<button data-evidence-claim="${key}" aria-pressed="${state.evidenceClaim===key}">${label}</button>`).join('')}</div></section><section><h2>2 · Complete one forecast input</h2><p>Choose a quantity. Explain which records or measurements you would request.</p><div class="k-answer-choices">${[['power','Operating IT power'],['output','Accepted results per hour'],['cost','Cost per accepted result']].map(([key,label])=>`<button data-evidence-need="${key}" aria-pressed="${state.evidenceNeed===key}">${label}</button>`).join('')}</div></section></div><button id="evidence-reveal" aria-expanded="${revealed}" ${ready?'':'disabled'}>${revealed?'Hide guidance':'Compare with the evidence needed'}</button>${revealed?`<div class="k-evidence-feedback" role="status"><p data-evidence-claim-status="${state.evidenceClaim==='plan'?'supported':'unsupported'}">${claim}</p><p data-evidence-need="${state.evidenceNeed}">${needs[state.evidenceNeed]}</p></div>`:''}</div>`;}

export function capacityVisual(id,state){switch(id){
 case 'capacity-purpose':return `<div class="k-stack k-investment"><div class="k-scope">Two proposals for more useful work</div><div class="k-investment-table"><div><b>Proposal</b><b>Capital</b><b>Available</b></div><div><section><h2>Network</h2><p>Less time waiting for data</p></section><strong>$4m</strong><span>Now</span></div><div><section><h2>Cooling</h2><p>More supported workload</p></section><strong>$6m</strong><span>After 1 year</span></div></div><div class="k-decision-chain"><span>What limits the work?</span>${arrow}<span>What does it cost?</span>${arrow}<span>When does it help?</span></div></div>`;
 case 'site-headroom':return headroom();
 case 'next-constraint':return nextConstraint(state);
 case 'tied-constraints':return tied(state);
 case 'useful-output':return output(state);
 case 'ownership-boundary':return ownership(state);
 case 'energy-exposure':return energy(state);
 case 'cash-flow-timing':return timing(state);
 case 'cost-per-result':return unitCost(state);
 case 'upgrade-paths':return upgradePaths();
 case 'delivery-window':return delivery(state);
 case 'abilene-campus':return abilene();
 case 'abilene-ledger':return evidenceLedger();
 case 'separate-campuses':return campusScope();
 case 'evidence-decision':return evidenceDecision(state);
 default:throw new Error(`Unknown capacity scene: ${id}`);
}}
