import {backstopVisual} from './capacity-backstop.js';
import {renderEnergyCost} from './capacity-energy.js';
import {rentalRevenue,h100Ranges} from './capacity-model.js';
import {sources} from './capacity-scenes.js';
const credit=(url,label)=>`<p class="k-credit"><a href="${url}" target="_blank" rel="noreferrer">${label}</a></p>`;
const wrap=(body)=>`<div class="k-stack">${body}</div>`;
const panel=(title,body)=>`<section class="k-panel"><h2>${title}</h2>${body}</section>`;
const svg=(body,label)=>`<svg viewBox="0 0 1100 330" role="img" aria-label="${label}">${body}</svg>`;
const txt=(x,y,v,size=25,fill='ink',anchor='start')=>`<text x="${x}" y="${y}" font-size="${size}" fill="var(--${fill})" text-anchor="${anchor}">${v}</text>`;
function tenor(){return wrap(`<div class="k-tenor">${[1,3,5].map(years=>`<div class="k-term-row"><b>${years} year${years>1?'s':''}</b><div class="k-term-track" aria-label="${years} contracted years in a five-year window">${Array.from({length:5},(_,i)=>`<span class="${i<years?'sold':'unsold'}">Year ${i+1}</span>`).join('')}</div></div>`).join('')}</div><div class="k-key"><span><i class="sold"></i>Contracted</span><span><i class="unsold"></i>Must sell or renew later</span></div><div class="k-split"><p>Provider: revenue visibility</p><p>Customer: capacity commitment</p></div>${credit(sources.pricing,'SemiAnalysis · rental terms from on-demand through five years')}`);}
function market(){let b=txt(70,28,'H100 · one-year contract · $/GPU-hour',25);const x=v=>200+(v-1)*350;for(const tick of[1,1.5,2,2.5,3])b+=`<path d="M${x(tick)} 54V267" stroke="var(--line)"/>`+txt(x(tick),310,`$${tick.toFixed(2)}`,21,'muted','middle');for(const [i,p]of h100Ranges.entries()){const y=85+i*80;b+=txt(20,y+5,p.period,22)+`<path d="M${x(p.low)} ${y}H${x(p.high)}" stroke="var(--teal)" stroke-width="19" stroke-linecap="round"/>`+txt(x(p.high)+23,y+7,`$${p.low.toFixed(2)}–${p.high.toFixed(2)}`,24);}return wrap('<div class="k-market-desktop">'+svg(b,'Dated H100 one-year rental price ranges, rising from October 2025 through April 2026.')+'</div><div class="k-market-mobile">'+h100Ranges.map(p=>`<div><b>${p.period}</b><span>$${p.low.toFixed(2)}–${p.high.toFixed(2)}</span></div>`).join('')+'</div>'+'<p class="k-note">25th–75th percentile ranges · typical 25% prepayment</p>'+credit(sources.pricing,'SemiAnalysis public price history'));}
function occupancy(state){const m=rentalRevenue(state);return wrap(`<div class="k-example">Worked example · 1,024 GPUs · one year</div><div class="k-two">${panel('Full-fleet commitment',`<p>$2.50 / GPU-hour</p><div class="k-hours"><span style="width:100%">All hours paid</span></div><strong class="k-number">$${(m.committed/1e6).toFixed(2)}m</strong>`)}${panel('Uncommitted rental pool',`<p>$4.00 / rented GPU-hour</p><div class="k-hours"><span style="width:${m.occupancy*100}%">${m.occupancy*100}% rented</span></div><strong class="k-number">$${(m.market/1e6).toFixed(2)}m</strong>`)}</div><p class="k-equation">Equal revenue at $2.50 ÷ $4.00 = <b>62.5% rented hours</b></p>`);}
function plan(){return wrap(`<div class="k-schedule"><div class="k-schedule-head"><b>Milestone</b><b>Announced target<br><small>Crusoe · March 2025</small></b><b>Later report</b></div><div><b>First two buildings</b><span>Energize in 1H 2025</span><span>Energized within a year of June 2024<br><small>Crusoe · September 2025</small></span></div><div><b>Six more buildings</b><span>Construction complete mid-2026</span><span>75% of capacity delivered<br>Remainder in later quarters<br><small>Oracle · September 2026</small></span></div></div><div class="k-credits">${credit(sources.plan,'Original targets')}${credit(sources.live,'First-phase report')}${credit(sources.oracle,'September 2026 update')}</div>`);}
export function capacityVisual(id,state){const backstop=backstopVisual(id);if(backstop)return backstop;switch(id){
 case 'capacity-purpose':return wrap(`<div class="k-opening"><div><p>Case study · CoreWeave</p><strong>&gt;98%</strong><p>of 2025 revenue came from<br>committed contracts</p></div><div class="k-opening-question">What is sold?<br>Who carries the risk?<br>How is the cluster financed?</div></div>${credit(sources.filing,'CoreWeave · 2025 annual report')}`);
 case 'what-is-sold':return wrap(`<div class="k-two">${panel('GPU cloud capacity','<div class="k-invoice"><b>GPU-hours / cluster commitment</b><span>Hardware access + agreed services</span></div><p>Customer runs training or inference</p>')}${panel('Model API','<div class="k-invoice"><b>Tokens / requests</b><span>A model-serving product</span></div><p>Provider operates the model service</p>')}</div>${credit(sources.managed,'CoreWeave · GPU-hour and token-billed product examples')}`);
 case 'service-boundary':return wrap(`<div class="k-serving-pair">${[['You run inference','Your team'],['CoreWeave runs inference','CoreWeave']].map(([heading,owner])=>`<section class="k-serving-choice"><h2>${heading}</h2><div class="k-serving-layer">Your model + application</div><div class="k-serving-owner ${owner==='CoreWeave'?'is-managed':''}"><strong>${owner}</strong><span>Serving · scaling · updates</span></div><div class="k-serving-layer">CoreWeave GPU infrastructure</div></section>`).join('')}</div>${credit(sources.managed,'CoreWeave · Inference on CKS / Dedicated Inference')}`);
 case 'service-examples':return wrap(`<div class="k-serving-pair k-serving-examples"><section><p class="k-service-type">GPU capacity</p><div class="k-brand-plate k-anthropic"><img src="../assets/references/capacity-anthropic-logo.svg" alt=""><h2>Anthropic</h2></div><p class="k-service-role">Claude workloads</p><span class="k-service-arrow" aria-hidden="true">↓</span><strong class="k-provider-name">CoreWeave</strong><p class="k-service-role">Supplies cloud compute</p>${credit(sources.anthropic,'CoreWeave · Anthropic agreement · April 2026')}</section><section><p class="k-service-type">Managed inference</p><div class="k-brand-plate"><img class="k-cursor-logo" src="../assets/references/capacity-cursor-logo.svg" alt="Cursor"></div><p class="k-service-role">Fast Apply model</p><span class="k-service-arrow" aria-hidden="true">↓</span><div class="k-provider-brand"><img src="../assets/references/capacity-fireworks-logo.svg" alt="Fireworks"></div><p class="k-service-role">Deploys + serves the model</p>${credit(sources.cursor,'Fireworks · Cursor Fast Apply · June 2024')}</section></div>`);
 case 'rental-products':return wrap(`<div class="k-three">${panel('On-demand','<strong class="k-symbol">↔</strong><p>Pay for used capacity<br>No multi-year term</p>')}${panel('Spot','<strong class="k-symbol">⏸</strong><p>Rent spare capacity<br>Price can change; provider can reclaim</p>')}${panel('Committed capacity','<strong class="k-symbol">▰</strong><p>Reserve a defined term<br>Pay the contracted obligation</p>')}</div>${credit(sources.spot,'AWS EC2 · Spot versus On-Demand')}`);
 case 'contract-tenor':return tenor();
 case 'rental-market':return market();
 case 'billable-occupancy':return occupancy(state);
 case 'contract-financing':return wrap(`<div class="k-financing"><section><h2>Customer</h2><p>Capacity contract</p></section><div class="k-money-flow"><span>Payments</span><b>→</b></div><section class="k-finance-core"><h2>GPU cloud</h2><p>Buys hardware<br>Delivers service</p></section><div class="k-money-flow"><span>Hardware financing</span><b>←</b><span>Debt service</span><b>→</b></div><section><h2>Lender</h2><p>Provides capital</p></section></div>${credit(sources.filing,'CoreWeave · asset-level debt supported by customer contracts')}`);
 case 'hardware-prices-meme':return '<figure class="k-meme"><img src="../assets/references/storage-hardware-prices-meme.png" alt="Grim Reaper AI meme: RAM, GPU and SSD prices rise, with CPU prices next."></figure>';
 case 'gpu-hour-cost':return renderEnergyCost();
 case 'abilene-roles':return wrap(`<figure class="k-campus-photo"><img src="../assets/references/distribution-abilene-data-halls.jpg" alt="Oracle aerial photograph of the Abilene data halls, July 15 2026."></figure><div class="k-chain"><section><h2>Crusoe</h2><p>Builds the facility</p></section><b>→</b><section><h2>Oracle</h2><p>Provides OCI capacity</p></section><b>→</b><section><h2>OpenAI</h2><p>Runs AI workloads</p></section></div>${credit(sources.live,'Abilene · first-phase announcement · photograph: Oracle, July 2026')}`);
 case 'abilene-ledger':return plan();
 default:throw new Error(`Unknown capacity scene: ${id}`);
}}
