// Dated case evidence and original teaching comparisons. No site simulation.
export const sources = {
  mlgw:{title:'MLGW · 2025 xAI update',url:'https://www.mlgw.com/images/content/files/pdf/new/xAI%202025%20Update.pdf',date:'2025',limits:'Historical utility account, not current IT demand or a cost comparison.'},
  xai:{title:'SemiAnalysis · SpaceX construction pace',url:'https://newsletter.semianalysis.com/p/spacex-10gw-in-2027-why-its-real',date:'2026-08-07',limits:'Public construction-pace passage following MiniHard reviewed. Research attribution in the Southaven/MiniHard context; not a complete as-built one-line. Revenue and 2027 forecasts are not used.'},
  sparks:{title:'Crusoe · Redwood microgrid update',url:'https://www.crusoe.ai/resources/newsroom/crusoe-and-redwood-materials-expand-strategic-partnership-scaling-to-7x-the-original-ai-infrastructure-density',date:'2026-03-24',limits:'Company-reported availability; grid backup is explicit. Uptime is not solar energy share.'},
  impact:{title:'Crusoe · 2025 impact report web summary',url:'https://www.crusoe.ai/resources/blog/crusoes-2025-impact-report',date:'2026-05-28',limits:'Selected web sections reviewed. Solar and storage ratings are not actual output or usable energy. The linked full report was not reviewed.'},
  cooling:{title:'Crusoe · Inside Abilene',url:'https://www.crusoe.ai/resources/blog/an-inside-look-at-the-abilene-ai-data-center',date:'2025-08-05',limits:'Dated company design description. Non-evaporative heat rejection does not establish zero total site water use.'},
  campus:{title:'Crusoe · Abilene development update',url:'https://www.crusoe.ai/resources/newsroom/crusoe-announces-new-900-mw-ai-factory-campus-in-abilene-texas-to-support-microsoft-ai-infrastructure',date:'2026-03-27',limits:'Original campus and adjacent Microsoft project have separate buildings and milestones. Energized capacity is not metered useful work.'},
  google:{title:'Google · Supporting grids with demand response',url:'https://cloud.google.com/blog/products/infrastructure/using-demand-response-to-reduce-data-center-power-consumption',date:'2023-10-03',limits:'Publisher-indexed introduction reviewed; direct fetch timed out. Historical pilot description for eligible non-urgent tasks.'},
};

export function transferCurrent(powerMW,voltageKV,pf=1) {
  if (![powerMW,voltageKV,pf].every(Number.isFinite)||powerMW<0||voltageKV<=0||pf<=0||pf>1) throw new RangeError('Use finite power ≥ 0, voltage > 0 and 0 < PF ≤ 1.');
  return powerMW*1000/(Math.sqrt(3)*voltageKV*pf);
}
export function storageHours(energyMWh,loadMW) {
  if(!Number.isFinite(energyMWh)||energyMWh<0||!Number.isFinite(loadMW)||loadMW<=0)throw new RangeError('Use energy ≥ 0 and load > 0.');
  return energyMWh/loadMW;
}

export const scenes=[
 {id:'land',domain:'Land and site',title:'Greenfield and brownfield start with different constraints',kind:'land',reference:'d12-hazards-and-site-evidence',sources:['impact','mlgw'],scope:'Original Abilene phase and original Colossus · redevelopment comparison',question:'Which site is cheaper if both must deliver the same useful work by the same date?',answer:'The labels do not decide. Compare the retained shell and services with retrofit work, new utility capacity, cooling, fiber, site investigations and operating costs.',explanation:'Abilene is our recurring greenfield campus. Original Colossus reused the Electrolux factory in Memphis, Tennessee. Brownfield here means redevelopment of an existing industrial site; it does not assert contamination or a legal designation. Reuse may remove some construction work and create constraints elsewhere. No matched project-cost comparison is supplied.'},
 {id:'colossus',domain:'Land reuse · Original Colossus',title:'A reused factory still needed substantial new power infrastructure',kind:'colossus',reference:'d12-hazards-and-site-evidence',sources:['mlgw'],scope:'MLGW historical 2025 grid-service account · Paul Lowery Road, Memphis, Tennessee',question:'How much of this 150 MW service came through the new substation?',answer:'142 ÷ 150 ≈ 94.7%. The existing factory did not make the new electrical work disappear.',explanation:'The chart separates the utility’s 8 MW from the existing substation and 142 MW from the new one. It does not describe IT draw, current capacity, backup generation, construction savings or the separate Tulane Road site. Trace the service path that must exist before a retained building can host the required load.'},
 {id:'procurement',domain:'Electrical supply · Southaven and MiniHard',title:'Equipment lead times can change the electrical path',kind:'procurement',reference:'d03-voltage-and-distance',sources:['xai'],scope:'Procurement account: SemiAnalysis, 7 August 2026 · paths below are conceptual',question:'What does the shorter procurement path trade away or need to replace?',answer:'It can bypass long-lead large-transformer stages. The MV alternative still needs enough circuits, conductor capacity, switching, protection and tested controls. Earlier service can justify a different electrical design.',explanation:'SemiAnalysis describes imported power modules and MV delivery from generation to transformers supplying LV, avoiding long-lead switchgear and large power transformers. The passage appears in its Southaven/MiniHard construction discussion. It is a reported speed-versus-efficiency strategy, not evidence that all Colossus equipment uses MV or that the original Colossus had no HV connection. MV is medium voltage; HV is high voltage; LV is low voltage.'},
 {id:'current',domain:'Voltage and distance',title:'The same power at lower voltage needs more current',kind:'current',reference:'d03-voltage-and-distance',sources:[],scope:'Original comparison · 200 MW, balanced three-phase AC, PF = 1 · not xAI design values',question:'At the same equivalent conductor resistance, what happens to resistive loss?',answer:'Current rises by 161/34.5 ≈ 4.67 times, so I²R loss rises by about 21.8 times. Adding circuits or conductor area changes resistance and the comparison.',explanation:'Use I = P/(√3 × line-to-line voltage × PF). The aggregate currents do not specify one cable rating or a feasible feeder layout. Voltage, distance, circuit count, conductor area, insulation, fault duty and delivery dates must be designed together. The result explains a tradeoff; it does not estimate losses at a named site.'},
 {id:'sparks',domain:'Storage · Crusoe + Redwood, Sparks, Nevada',title:'Solar power and battery energy answer different questions',kind:'sparks',reference:'d05-storage-power-and-time',sources:['impact'],scope:'Reported equipment: 12 MW solar, 63 MWh batteries · runtime below is an ideal teaching example',question:'Can a 63 MWh label guarantee the selected runtime?',answer:'Only in the stated ideal energy calculation. Real delivery also needs enough discharge power, usable state of charge, reserve, conversion efficiency and auxiliary allowance.',explanation:'Crusoe reports solar paired with repurposed EV batteries at Redwood Materials. In this example the full 63 MWh is assumed usable, load is constant, and solar input, losses and reserves are zero. At 3 MW that is 21 hours; at 6 MW, 10.5 hours. Neither load nor runtime is a measured Sparks operating condition.'},
 {id:'availability',domain:'Continuity and reliability · Sparks, Nevada',title:'Grid backup and stored energy support different service boundaries',kind:'availability',reference:'d05-storage-power-and-time',sources:['sparks'],scope:'Crusoe report, 24 March 2026 · company-reported operating measures',question:'Does 99.2% availability mean 99.2% of electricity came from solar?',answer:'No. Availability counts time meeting a service definition. Solar share counts energy. The latter needs a metered supply ledger, including grid energy.',explanation:'Crusoe reports microgrid availability over seven months and separately states that Cloud availability uses grid backup. The two percentages are not interchangeable reliability measurements, a guaranteed SLA, or proof of continuous solar-only operation. Storage shifts energy across time; backup provides another supply when needed.'},
 {id:'abilene-cooling',domain:'Heat rejection · Our Abilene reference campus',title:'A closed coolant loop can reject heat to outdoor air',kind:'cooling',reference:'d11-water-and-heat-reuse',sources:['cooling'],scope:'Crusoe’s August 2025 design description · functional heat path, not an as-built drawing',question:'Does non-evaporative heat rejection mean zero water use for the whole site?',answer:'No. Initial fill, maintenance and other site uses remain separate accounts. It means the specified rejection process does not rely on evaporating cooling water.',explanation:'The Abilene description combines recirculating facility water with air-cooled chillers. Heat still has to cross each interface, and compressor work joins the outdoor duty. Hot-weather performance remains a design constraint. A closed equipment loop could also feed a different, evaporative outdoor arrangement; identify both loops before drawing conclusions.'},
 {id:'demand-response',domain:'Scheduling · Google demand response',title:'Scheduling moves flexible work to a different hour',kind:'demand',reference:'d09-service-acceptance',sources:['google'],scope:'Google’s 2023 pilot account · the schedule below is an original example',question:'Which job can move through a two-hour grid event without failing its brief?',answer:'The video-processing job may move if later capacity still meets tomorrow’s deadline. Delaying the interactive request by two hours would fail its 200 ms requirement.',explanation:'Google describes moving eligible non-urgent tasks during grid stress. Contrast this with Sparks: a battery moves energy through time; scheduling moves work and its demand. Deferral requires deadlines, resource availability and retained progress. It can reduce peak demand without reducing total job energy.'},
 {id:'abilene-ledger',domain:'Capacity and evidence · Our recurring campus',title:'Abilene’s buildings have separate capacity milestones',kind:'ledger',reference:'d15-upgrade-and-evidence',sources:['campus'],scope:'Crusoe’s dated account: 27 March 2026 · not September 2026 operating inventory',question:'Can these statements establish current campus IT demand or useful output?',answer:'No. Energized buildings, future delivery and an adjacent project are different records. Actual demand and useful output need matching measurements and workload definitions.',explanation:'We return to the original Crusoe-built Stargate campus throughout the course. The adjacent Microsoft development stays a separate record. An illustrative rack or energy calculation never fills a missing Abilene measurement. This lets the real campus connect the domains while preserving the boundary of what each source establishes.'},
];
