import {hardwareVisual,svg,t,rect,line,credit} from './compute-hardware.js';
import {workloadBound,roofline,serviceDomains} from './compute-model.js';
const fmt=(v,d=0)=>v.toLocaleString('en-US',{maximumFractionDigits:d});
const metric=(value,label)=>`<div class="big-stat"><strong>${value}</strong><span>${label}</span></div>`;
const stat=(label,value,detail='')=>`<div class="comparison-stat"><span>${label}</span><strong>${value}</strong>${detail?`<small>${detail}</small>`:''}</div>`;
const photo=(name,alt)=>`<img src="../assets/generated/${name}" alt="${alt}">`;
function title(){return `<figure class="hero-figure">${photo('compute-scales.png','Conceptual scale transition from an AI rack, to a compute tray, to a GPU package.')}<figcaption class="scale-labels"><span>Rack</span><span>Compute tray</span><span>GPU package</span></figcaption></figure>`;}
function hbm(compact){if(compact)return `<figure class="hero-figure"><img src="../assets/generated/compute-hbm-package.png" alt="Stacked memory and a GPU logic die connect through a shared interposer."><figcaption class="hbm-mobile-labels"><span><b>HBM</b> Stacked memory beside the GPU</span><span><b>Interposer</b> Shared connection layer beneath the dies</span></figcaption></figure>`;return `<svg class="diagram hbm-cross-section" viewBox="0 0 1100 650" role="img" aria-label="High-bandwidth memory stacks sit beside the GPU logic die on a shared interposer. Vertical connections join the memory layers; short lateral connections cross the interposer." xmlns="http://www.w3.org/2000/svg"><rect width="1100" height="650" rx="12" fill="#fff"/><image href="../assets/generated/compute-hbm-package.png" x="0" y="38" width="1100" height="600"/><g fill="#193139" font-family="inherit" font-size="23"><text x="185" y="58" text-anchor="middle">Stacked HBM</text><text x="550" y="58" text-anchor="middle">GPU logic</text><text x="860" y="612" text-anchor="middle">Interposer · connection layer</text></g><g stroke="#526660" fill="none" stroke-width="2"><path d="M185 75V180"/><path d="M550 75V200"/><path d="M860 586V465L810 370"/><circle cx="810" cy="370" r="3" fill="#526660"/></g></svg>`;}

function locality(compact){
 if(compact)return `<div class="locality-mobile"><section><h2>GPU-local HBM</h2><p>GPU execution ⇄ memory controllers ⇄ HBM</p></section><div class="locality-bridge">NVLink-C2C</div><section><h2>CPU-side LPDDR5X</h2><p>The GPU can also address memory here.</p></section><p class="single-point">The address is accessible; the bytes still cross a link.</p></div>`;
 const body=t(550,35,'GB300 · hardware-coherent CPU and GPU memory',21,'--muted','middle')+rect(60,85,360,290)+t(240,130,'CPU side',23,'--ink','middle')+rect(100,165,280,100)+t(240,220,'LPDDR5X',30,'--ink','middle')+t(240,307,'Reached across NVLink-C2C',20,'--muted','middle')+rect(670,85,360,290)+t(850,130,'GPU side',23,'--ink','middle')+rect(710,165,280,100,'--surface-soft')+t(850,220,'Local HBM',30,'--ink','middle')+t(850,307,'Reached by memory controllers',19,'--muted','middle')+line('M420 215H670','--phase-three')+t(545,192,'Coherent access',18,'--phase-three','middle')+t(550,435,'The bytes remain on the side that stores them.',24,'--ink','middle');
 return svg(body,'CPU LPDDR5X and GPU HBM can share coherent addressing. Reaching CPU memory still crosses the chip-to-chip link.');
}
function capacity(){return `<div class="comparison-pair"><section><h2>Capacity</h2><div class="memory-slots" aria-hidden="true">${Array.from({length:12},()=>'<i></i>').join('')}</div>${stat('HBM3e per Blackwell Ultra GPU','288 GB','Bytes that can be resident')}</section><section><h2>Bandwidth</h2><div class="bandwidth-lanes" aria-hidden="true">${Array.from({length:6},()=>'<i>→</i>').join('')}</div>${stat('GPU memory interface','Up to 8 TB/s','Bytes transferred per second')}</section></div>`;}
function readTime(){return `<div class="read-account"><div class="operand-strip"><span>144 GB of resident weights</span><span>HBM → GPU</span><span>8 TB/s sustained for this read</span></div><div class="fraction-equation"><span class="fraction"><span>144 × 10⁹ bytes</span><span>8 × 10¹² bytes/s</span></span><span>=</span><strong>0.018 s</strong><span>=</span><strong>18 ms</strong></div><div class="read-timeline"><div><span>Read weights</span></div><div><span>Compute, cache traffic, communication…</span></div></div><p class="single-point">One weight-read account is only part of a token-generation step.</p></div>`;}
function reuse(state,compact){
 const n=state.tokens;
 const vectors=Array.from({length:n},(_,i)=>`<div class="token-vector" aria-label="Token vector ${i+1}">${Array.from({length:4},()=>'<i></i>').join('')}</div>`).join('');
 return `<div class="reuse-layout"><div class="weight-origin"><h2>HBM</h2><div class="weight-tile">${Array.from({length:16},()=>'<i></i>').join('')}</div><span>One weight tile</span></div><div class="reuse-arrow">→<small>Load once</small></div><div class="on-chip"><h2>GPU on-chip memory</h2><div class="reuse-core"><div class="weight-tile">${Array.from({length:16},()=>'<i></i>').join('')}</div><span class="multiply">×</span><div class="token-vectors">${vectors}</div></div><div class="kernel-label">Tensor Core matrix operations</div></div></div><p class="single-point">${n===1?'One vector uses the tile.':'Eight vectors reuse the resident tile before it is replaced.'}</p>`;
}
function bounds(){
 const rows=[{label:'Low reuse',flops:2e12},{label:'High reuse',flops:40e12}].map(({label,flops})=>{const m=workloadBound({flops,hbmBytes:160e9});return `<section><h2>${label}</h2><p class="inputs">${fmt(flops/1e12)} TFLOP of work · 160 GB from HBM</p><div class="time-pair">${stat('Compute',`${fmt(m.computeSeconds*1000)} ms`,`${fmt(flops/1e12)} TFLOP ÷ 200 TFLOP/s`)}${stat('Memory',`${fmt(m.memorySeconds*1000)} ms`,'160 GB ÷ 8 TB/s')}</div><div class="bound-result"><span>Complete overlap</span><strong>≥ ${fmt(m.overlappedSeconds*1000)} ms</strong><small>${m.bottleneck==='memory'?'Memory-limited':'Compute-limited'}</small></div></section>`;}).join('');
 return `<div class="model-condition">Assumed operation rates: 200 TFLOP/s compute · 8 TB/s HBM</div><div class="comparison-pair bounds-pair">${rows}</div><p class="equation-line">t ≥ max(work ÷ compute rate, bytes ÷ memory rate)</p>`;
}
function roof(state,compact){
 if(compact){const m=roofline({arithmeticIntensity:state.intensity}),x=v=>60+v*3.7,y=v=>320-v/1e12*1.15;let b=t(60,28,'Throughput · TFLOP/s',17,'--muted');[0,100,200].forEach(v=>{b+=`<path d="M60 ${y(v*1e12)}H445" stroke="var(--line)"/>`+t(46,y(v*1e12)+5,v,16,'--muted','end');});[0,25,50,100].forEach(v=>{b+=t(x(v),350,v,16,'--muted','middle');});b+=`<path d="M60 320L${x(25)} ${y(200e12)}H445" fill="none" stroke="var(--teal)" stroke-width="5"/><circle cx="${x(state.intensity)}" cy="${y(m.attainableFlopsPerSecond)}" r="7" fill="var(--phase-three)" stroke="var(--paper)" stroke-width="2"/>`;b+=t(300,68,'Compute limit',18,'--teal','middle')+t(280,230,'Memory limit',18,'--teal','middle')+t(250,389,'Arithmetic intensity · FLOP/B',17,'--muted','middle');return `<div class="model-condition">200 TFLOP/s compute · 8 TB/s HBM</div>${svg(b,'Roofline with linear axes. The selected point lies on the resource ceiling.',500,420)}<div class="roof-result"><strong>${fmt(m.attainableFlopsPerSecond/1e12)} TFLOP/s</strong><span>${m.bottleneck==='balanced'?'Both limits meet':m.bottleneck==='memory'?'Memory-limited':'Compute-limited'}</span><span>Knee: 200 ÷ 8 = 25 FLOP/B</span></div>`;}
 const m=roofline({arithmeticIntensity:state.intensity}), x=v=>110+v*8.5,y=v=>395-v/1e12*1.5;
 let b=t(105,35,'Compute throughput · TFLOP/s',19,'--muted');
 [0,50,100,150,200].forEach(v=>{b+=`<path d="M110 ${y(v*1e12)}H960" stroke="var(--line)"/>`+t(90,y(v*1e12)+6,v,17,'--muted','end');});
 [0,10,25,50,100].forEach(v=>{b+=t(x(v),425,v,17,'--muted','middle');});
 b+=`<path d="M${x(0)} ${y(0)}L${x(25)} ${y(200e12)}H960" fill="none" stroke="var(--teal)" stroke-width="7" stroke-linejoin="round"/>`;
 b+=t(145,155,'Memory limit',21,'--teal')+t(800,70,'Compute limit',23,'--teal','middle');
 b+=`<path d="M${x(state.intensity)} 395V${y(m.attainableFlopsPerSecond)}" stroke="var(--phase-three)" stroke-width="2" stroke-dasharray="6 5"/><circle cx="${x(state.intensity)}" cy="${y(m.attainableFlopsPerSecond)}" r="10" fill="var(--phase-three)" stroke="var(--paper)" stroke-width="3"/>`;
 b+=t(550,472,'Arithmetic intensity · FLOP per HBM byte',20,'--muted','middle');
 return `<div class="model-condition">Roofline model · 200 TFLOP/s compute · 8 TB/s HBM</div>${svg(b,`At ${state.intensity} FLOP per byte, the throughput ceiling is ${fmt(m.attainableFlopsPerSecond/1e12)} TFLOP per second. The knee is 25 FLOP per byte.`)}<div class="roof-result"><strong>${fmt(m.attainableFlopsPerSecond/1e12)} TFLOP/s</strong><span>${m.bottleneck==='balanced'?'The two ceilings meet':m.bottleneck==='memory'?'Memory-limited':'Compute-limited'}</span><span>Knee: 200 ÷ 8 = 25 FLOP/B</span></div>`;
}
function precision(){return `<div class="precision-layout"><div class="math-operation"><span>a × b + c</span><strong>2 FLOPs</strong><small>One multiply + one addition</small></div><div class="precision-fields"><section><h2>Precision</h2><div class="precision-comparison"><span>BF16<br><b>16-bit inputs</b></span><span>FP8<br><b>8-bit inputs</b></span></div><p>Accumulation can use a different precision.</p></section><section><h2>Sparsity</h2><div class="sparsity-example"><span>Dense<br><b>All entries</b></span><span>Sparse<br><b>Supported zero pattern</b></span></div></section></div></div><p class="single-point">Compare the rate for the operation your workload actually executes.</p>`;}
function placement(compact){
 if(compact)return `<div class="placement-mobile"><p class="model-condition">Tensor parallelism · one layer</p><div class="parallel-devices"><section><h2>GPU 1</h2><span>Weights W₁</span><b>×</b><span>Input x₁</span></section><section><h2>GPU 2</h2><span>Weights W₂</span><b>×</b><span>Input x₂</span></section></div><div class="reduction-arrows">↘　↙</div><div class="reduction-result"><b>Sum partial results</b><span>y = W₁x₁ + W₂x₂</span></div></div>`;
 let b=t(550,30,'Tensor parallelism · one layer split across two GPUs',21,'--muted','middle');
 const xs=[80,650];
 xs.forEach((x,i)=>{b+=rect(x,75,370,205)+t(x+185,115,`GPU ${i+1}`,25,'--ink','middle')+rect(x+25,145,135,85,'--surface-soft')+t(x+92,197,`Weights W${i+1}`,19,'--ink','middle')+t(x+194,198,'×',30,'--ink','middle')+rect(x+235,145,110,85)+t(x+290,197,`Input x${i+1}`,19,'--ink','middle');});
 b+=line('M265 280V315H460V345','--teal')+line('M835 280V315H640V345','--phase-three');
 b+=rect(395,345,310,90,'--surface-soft')+t(550,380,'Sum partial results',23,'--ink','middle')+t(550,414,'y = W₁x₁ + W₂x₂',22,'--ink','middle');
 return svg(b,'Two GPUs calculate partial results from different weight and input partitions; a reduction sums them to form the layer output.');
}
function repair(){return `<div class="hardware-pair"><figure class="hardware-photo"><img src="../assets/references/nvidia-gb300-tray.png" alt="NVIDIA DGX GB300 compute tray, the physical unit removed for this repair.">${credit('NVIDIA · Compute tray','https://docs.nvidia.com/dgx/dgxgb200-user-guide/hardware.html')}</figure><div class="hardware-notes">${metric('4 GPUs','leave this rack during the tray repair')}<div class="job-impact"><div><b>Job uses the removed tray</b><span>Stop or recover onto another allocation</span></div><div><b>Job uses other trays</b><span>Depends on isolation and shared services</span></div></div></div></div>`;}
function groups(state){
 const compare=[{name:'Four failures in one group',failed:[4,0,0,0]},{name:'One failure in each group',failed:[1,1,1,1]}];
 const panels=compare.map(v=>{const m=serviceDomains({failedByGroup:v.failed,devicesPerJob:state.jobSize});return `<section><h2>${v.name}</h2><div class="allocation-groups">${m.groups.map((g,i)=>`<div class="allocation-group"><span>Group ${i+1}</span><div>${Array.from({length:8},(_,j)=>`<i class="${j<g.failedDevices?'failed':j<g.failedDevices+g.allocatedDevices?'allocated':'idle'}" aria-label="${j<g.failedDevices?'Failed GPU':j<g.failedDevices+g.allocatedDevices?'Allocated GPU':'Healthy GPU outside this job'}">${j<g.failedDevices?'×':j<g.failedDevices+g.allocatedDevices?'●':'○'}</i>`).join('')}</div></div>`).join('')}</div><div class="group-result"><strong>${m.runnableJobs} <span>runnable ${state.jobSize}-GPU jobs</span></strong><span>28 healthy GPUs</span></div></section>`;}).join('');
 return `<div class="model-condition">Four independent 8-GPU groups · jobs cannot span groups</div><div class="comparison-pair group-comparison">${panels}</div><div class="group-legend"><span>● Allocated</span><span>○ Healthy, outside this job</span><span>× Failed</span></div>`;
}
function recover(){return `<div class="recovery-story"><section><span class="stage-number">01</span><h2>Replace the hardware</h2><div class="spare-icon" aria-hidden="true"><i>Tray</i><span>↔</span><i>Tray</i></div><p>Compatible tray, firmware and interfaces</p></section><section><span class="stage-number">02</span><h2>Rebuild the allocation</h2><div class="small-allocation" aria-hidden="true">${Array.from({length:8},()=>'<i></i>').join('')}</div><p>Healthy devices and working collectives</p></section><section><span class="stage-number">03</span><h2>Resume useful work</h2><div class="checkpoint-bar"><span>Checkpoint</span><b>→ Progress</b></div><p>Restore job state and verify progress</p></section></div>`;}
function diagnose(state){
 const options=[['compute','Double compute throughput'],['memory','Double HBM transfer rate'],['capacity','Double HBM capacity']];
 const selected=state.diagnosis,show=state.showDiagnosis;
 const evidence='<div class="diagnosis-evidence"><span>Unchanged kernel</span><b>2 TFLOP · 160 GB HBM traffic</b><span>Resident state: 240 GB of 288 GB</span><span>Compute: 200 TFLOP/s · Memory: 8 TB/s</span></div>';
 const answers={compute:['20 ms → 20 ms','Compute falls from 10 to 5 ms; the memory bound remains 20 ms.'],memory:['20 ms → 10 ms','Memory falls from 20 to 10 ms, matching the compute bound.'],capacity:['20 ms → 20 ms','The state already fits. More storage leaves this transfer rate unchanged.']};
 return `${evidence}<p class="question">Which upgrade lowers the compute/HBM time bound?</p><div class="diagnosis-options">${options.map(([id,label])=>`<button data-diagnosis="${id}" aria-pressed="${selected===id}">${label}</button>`).join('')}</div><div class="diagnosis-answer">${show?`<strong>${answers[selected][0]}</strong><p>${answers[selected][1]}</p>`:'<p>Assume complete overlap and no additional transfer or synchronization time.</p>'}</div><button id="diagnosis-reveal" aria-expanded="${show}" ${selected?'':'disabled'}>${show?'Hide comparison':'Show comparison'}</button>`;
}
function next(){return `<div class="network-bridge"><div class="mini-rack"><b>NVLink</b><div>${Array.from({length:9},()=>'<i></i>').join('')}</div><span>Within the rack</span></div><div class="network-span"><span>Network interfaces</span><div class="fabric-line">⇄</div><strong>Cluster fabric</strong></div><div class="mini-rack"><b>NVLink</b><div>${Array.from({length:9},()=>'<i></i>').join('')}</div><span>Another rack</span></div></div><p class="single-point">How do the racks exchange data without leaving GPUs waiting?</p>`;}
export function computeVisual(id,state,compact=false){
 if(id==='consumer-hardware-meme')return `<figure class="meme-figure"><img src="../assets/references/compute-consumer-hardware-meme.png" alt="Grim Reaper meme: AI Data Centers passes doors labeled Low MSRPs, Mid range Availability and Consumer VRAM, and knocks on PC Gaming as a Hobby."></figure>`;
 const hw=hardwareVisual(id,state,compact);if(hw)return hw;
 const renders={'compute-purpose':title,'hbm-package':()=>hbm(compact),'memory-locality':()=>locality(compact),'capacity-bandwidth':capacity,'weight-read':readTime,'operand-reuse':()=>reuse(state,compact),'operation-bounds':bounds,roofline:()=>roof(state,compact),'peak-flops':precision,'model-placement':()=>placement(compact),'tray-repair':repair,'fault-placement':()=>groups(state),'recover-work':recover,'diagnose-upgrade':()=>diagnose(state),'network-handoff':next};
 if(!renders[id])throw new Error(`Unknown compute scene: ${id}`);return renders[id]();
}
