const continuity = (
  id,
  label,
  title,
  objectives,
  reading = "d05-paths-and-transitions",
  extra = {},
) => ({ id, label, title, domain: "D05", objectives, reading, ...extra });
export const continuityScenes = Object.freeze(
  [
    continuity(
      "campus",
      "Power through a disturbance",
      "Trace the surviving supply, then test the whole service.",
      ["D05.1", "D05.2", "D05.3"],
    ),
    continuity(
      "equipment",
      "Locate the UPS and its batteries",
      "The UPS controls output. Its battery cabinet supplies stored energy.",
      ["D05.1", "D05.2"],
      "d05-storage-power-and-time",
    ),
    continuity(
      "normal",
      "Online double conversion",
      "The inverter already supplies the protected load.",
      ["D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity(
      "outage",
      "Remove the AC supply",
      "The battery supports the same DC link and inverter.",
      ["D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity(
      "capacitors",
      "The first milliseconds",
      "Capacitors cover the deficit while battery power rises.",
      ["D05.1", "D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity(
      "dc-link-recovery",
      "Restore the bus voltage",
      "Matching load stops the fall; surplus power restores the voltage.",
      ["D05.1", "D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity(
      "generator",
      "Bridge, transfer and recharge",
      "The UPS battery bridges the wait for accepted generator power.",
      ["D05.2"],
      "d05-paths-and-transitions",
      { ups: true },
    ),
    continuity(
      "storage-limits",
      "Power limit and energy duration",
      "The same stored energy can support different loads.",
      ["D05.1"],
      "d05-storage-power-and-time",
    ),
    continuity(
      "sparks-storage",
      "Crusoe + Redwood · Sparks",
      "Solar supplies power; batteries move energy through time.",
      ["D05.1"],
      "d05-storage-power-and-time",
    ),
    continuity(
      "static-bypass",
      "Static bypass",
      "Static bypass connects the load to the bypass AC source.",
      ["D05.2", "D05.3"],
      "d05-paths-and-transitions",
      { ups: true, mode: "static" },
    ),
    continuity(
      "maintenance-bypass",
      "Maintenance bypass",
      "Maintenance bypass carries the load around the isolated UPS.",
      ["D05.2", "D05.3"],
      "d05-paths-and-transitions",
      { ups: true, mode: "maintenance" },
    ),
    continuity(
      "capacity-n",
      "N · required capacity",
      "Two 50 kW modules supply the 100 kW requirement.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n" },
    ),
    continuity(
      "capacity-n1",
      "N+1 · one spare module",
      "One extra module covers one unavailable module.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n1" },
    ),
    continuity(
      "capacity-n2",
      "N+2 · maintenance plus a failure",
      "N+2 can cover maintenance and one module failure.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n2" },
    ),
    continuity(
      "shared-bus",
      "A shared bus can defeat the spares",
      "Healthy modules cannot supply through a failed common bus.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n1" },
    ),
    continuity(
      "two-n",
      "2N · two complete capacity paths",
      "Either path can carry the whole 100 kW load.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "two_n" },
    ),
    continuity(
      "two-n-plus-one",
      "2(N+1) · a spare on each path",
      "A spare on each path adds margin during maintenance.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "two_n1" },
    ),
    continuity(
      "load-growth",
      "Growth consumes the spare",
      "N changes when the supported load changes.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n1" },
    ),
    continuity(
      "fault-isolation",
      "Detect and isolate the fault zone",
      "Which device opens determines which healthy loads survive.",
      ["D05.3", "D05.4"],
      "d05-protection-and-fault-domains",
    ),
    continuity(
      "grounding",
      "Complete the fault-current loop",
      "Protective bonding gives fault current a return path to the source.",
      ["D05.4"],
      "d05-protection-and-fault-domains",
    ),
    continuity(
      "ac-dc-interruption",
      "AC and DC interruption",
      "DC interruption must create current extinction.",
      ["D05.4"],
      "d05-protection-and-fault-domains",
    ),
    continuity(
      "tier-topology",
      "Tier I–IV · infrastructure outcomes",
      "Tier III adds maintenance continuity. Tier IV adds fault tolerance.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity(
      "tier-generation",
      "Generation is already in Tier I",
      "On-site generation is part of all four Uptime Tiers.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity(
      "availability-budget",
      "Three named availability claims",
      "A percentage needs a service boundary and an evidence type.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity(
      "tier-investment",
      "Fairwater Atlanta · the design choice",
      "Fairwater’s GPU design relies on resilient utility power.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity(
      "service-check",
      "Check: the racks still have power",
      "The electrical transfer succeeds. Does the service survive?",
      ["D05.1", "D05.2", "D05.3"],
      "d05-paths-and-transitions",
      { check: true },
    ),
  ].map(Object.freeze),
);

export const continuityAliases = Object.freeze({
  "electrical-room": "equipment",
  return: "service-check",
});
export function resolveContinuityScene(hash) {
  const id = continuityAliases[hash] || hash;
  const i = continuityScenes.findIndex((s) => s.id === id);
  return i < 0 ? 0 : i;
}
