const continuity = (
  id,
  label,
  title,
  objectives,
  reading = "d05-paths-and-transitions",
  extra = {},
) => ({ id, label, title, domain: "D05", objectives, reading, ...extra });
export const continuityScenes = Object.freeze(
  [
    continuity(
      "campus",
      "Continuity, storage and protection",
      "Continuity, storage and protection",
      ["D05.1", "D05.2", "D05.3"],
    ),
    continuity(
      "equipment",
      "Locate the UPS and its batteries",
      "UPS cabinet and external batteries",
      ["D05.1", "D05.2"],
      "d05-storage-power-and-time",
    ),
    continuity(
      "normal",
      "Online double conversion",
      "The inverter already supplies the protected load.",
      ["D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity(
      "outage",
      "Remove the AC supply",
      "The battery supports the same DC link and inverter.",
      ["D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity("capacitance", "Charge and capacitance", "Capacitance relates stored charge to voltage", ["D05.1", "D05.2"], "d05-storage-power-and-time", { ups: true }),
    continuity("capacitor-energy", "Energy stored in a capacitor", "Why does capacitor energy include one half?", ["D05.1", "D05.2"], "d05-storage-power-and-time", { ups: true }),
    continuity(
      "capacitors",
      "The first milliseconds",
      "How long can the capacitor support a 1 MW load?",
      ["D05.1", "D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity("battery-ramp", "The battery ramps up", "The capacitor supplies the deficit during the battery ramp", ["D05.1", "D05.2"], "d05-storage-power-and-time", { ups: true }),
    continuity("recovery-time", "Derive recovery time", "How long does it take to restore the bus voltage?", ["D05.1", "D05.2"], "d05-storage-power-and-time"),
    continuity(
      "dc-link-recovery",
      "Restore the bus voltage",
      "More surplus power restores the bus sooner",
      ["D05.1", "D05.2"],
      "d05-storage-power-and-time",
      { ups: true },
    ),
    continuity(
      "generator",
      "Bridge, transfer and recharge",
      "The UPS battery bridges the wait for accepted generator power.",
      ["D05.2"],
      "d05-paths-and-transitions",
      { ups: true },
    ),
    continuity(
      "storage-limits",
      "Power limit and energy duration",
      "Battery output power determines which load it can support",
      ["D05.1"],
      "d05-storage-power-and-time",
    ),
    continuity(
      "sparks-storage",
      "Crusoe + Redwood · Sparks",
      "Solar and battery storage at Crusoe’s Sparks site",
      ["D05.1"],
      "d05-storage-power-and-time",
    ),
    continuity(
      "static-bypass",
      "Forced static bypass",
      "Forced static bypass supplies the load when the inverter is unavailable.",
      ["D05.2", "D05.3"],
      "d05-paths-and-transitions",
      { ups: true, mode: "static" },
    ),
    continuity(
      "maintenance-bypass",
      "Maintenance bypass",
      "Maintenance bypass carries the load around the isolated UPS.",
      ["D05.2", "D05.3"],
      "d05-paths-and-transitions",
      { ups: true, mode: "maintenance" },
    ),
    continuity("stored-energy-isolation", "Stored energy after isolation", "Opening the AC supply can leave stored energy connected", ["D05.4"], "d05-protection-and-fault-domains"),
    continuity(
      "capacity-n",
      "N · required capacity",
      "Two 50 kW modules supply the 100 kW requirement.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n" },
    ),
    continuity(
      "capacity-n1",
      "N+1 · one spare module",
      "One extra module covers one unavailable module.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n1" },
    ),
    continuity(
      "capacity-n2",
      "N+2 · maintenance plus a failure",
      "N+2 can cover maintenance and one module failure.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n2" },
    ),
    continuity(
      "shared-bus",
      "A shared bus can defeat the spares",
      "Healthy modules cannot supply through a failed common bus.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n1" },
    ),
    continuity(
      "two-n",
      "2N · two complete capacity paths",
      "Either path can carry the whole 100 kW load.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "two_n" },
    ),
    continuity(
      "two-n-plus-one",
      "2(N+1) · a spare on each path",
      "A spare on each path adds margin during maintenance.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "two_n1" },
    ),
    continuity(
      "load-growth",
      "Growth consumes the spare",
      "N changes when the supported load changes.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { ups: true, redundancy: "n1" },
    ),
    continuity(
      "fault-isolation",
      "Detect and isolate the fault zone",
      "Which device opens determines which healthy loads survive.",
      ["D05.3", "D05.4"],
      "d05-protection-and-fault-domains",
    ),
    continuity(
      "grounding",
      "Complete the fault-current loop",
      "A fault to the metal case needs a return path",
      ["D05.4"],
      "d05-protection-and-fault-domains",
    ),
    continuity(
      "ac-dc-interruption",
      "How contacts interrupt current",
      "Why opening the contacts may not stop the current",
      ["D05.4"],
      "d05-protection-and-fault-domains",
    ),
    continuity("tier-overview", "Tiers I–IV", "Uptime Institute Tiers I–IV", ["D05.3"], "d05-paths-and-transitions", { reliability: true }),
    continuity(
      "tier-topology",
      "Tier I–IV · infrastructure outcomes",
      "Maintenance and fault tolerance",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity(
      "tier-generation",
      "Generation is already in Tier I",
      "On-site generation is part of all four Uptime Tiers.",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity(
      "availability-budget",
      "Three named availability claims",
      "Three, four and five nines of availability",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity(
      "tier-investment",
      "Fairwater Atlanta · the design choice",
      "Four-nines availability at three-nines cost",
      ["D05.3"],
      "d05-paths-and-transitions",
      { reliability: true },
    ),
    continuity("fairwater-power-management", "Fairwater power oscillations", "How Microsoft manages power oscillations", ["D05.1", "D05.2"], "d05-paths-and-transitions", { quote: true }),
    continuity(
      "service-check",
      "Knowledge check",
      "The racks have power. Can the workload keep running?",
      ["D05.1", "D05.2", "D05.3"],
      "d05-paths-and-transitions",
      { check: true },
    ),
    continuity("bypass-check", "Inverter failed, then utility fails", "The UPS is on bypass. Will the load ride through?", ["D05.2", "D05.3"], "d05-paths-and-transitions", { check: true }),
  ].map(Object.freeze),
);

export const continuityAliases = Object.freeze({
  "electrical-room": "equipment",
  return: "service-check",
});
export function resolveContinuityScene(hash) {
  const id = continuityAliases[hash] || hash;
  const i = continuityScenes.findIndex((s) => s.id === id);
  return i < 0 ? 0 : i;
}
