import {deviceTemperature,hydraulicPoint,parallelBranches,retrofitAnswers} from './cooling-capture-model.js';
const n=(v,d=1)=>Number(v.toFixed(d)).toString();
const text=(x,y,s,size=28,color='ink',anchor='middle')=>`<text x="${x}" y="${y}" text-anchor="${anchor}" style="font-size:${size}px;fill:var(--${color})">${s}</text>`;
const box=(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="var(--panel)" stroke="var(--line)"/>`;
const path=(d,c='tech')=>`<path d="${d}" fill="none" stroke="var(--${c})" stroke-width="4"/>`;
const card=(x,y,w,title,big,detail='',color='tech')=>box(x,y,w,180)+text(x+w/2,y+38,title,26)+text(x+w/2,y+100,big,45,color)+(detail?text(x+w/2,y+149,detail,23):'');
const control=(key,label,options)=>({key,label,options});
export const captureScenes=[
{id:'local-heat-flux',label:'Heat concentrated on the chip',title:'The same heat can be harder to remove',reference:'d10-local-thermal-paths',kind:'capture-detail',pedagogical_role:'comparison',description:'Two 400 W devices have heat-transfer areas of 4 and 1 square centimetres. Their average heat fluxes are 100 and 400 W per square centimetre; neither value by itself establishes junction temperature.'},
{id:'device-temperature',label:'Coolant and chip temperature',title:'Cool coolant does not guarantee a cool chip',reference:'d10-local-thermal-paths',kind:'capture-detail',pedagogical_role:'comparison',description:'At 400 W and a 35 degree local coolant reference, stipulated junction-to-fluid resistances of .08 and .12 K/W give 67 and 83 degrees. The chosen device limit is 80 degrees.',controls:[control('fluidC','Local coolant', [['35','35°C'],['30','30°C']])]},
{id:'pump-operating-point',label:'Flow needs pressure',title:'The pump and the circuit set the flow together',reference:'d10-flow-and-pressure',kind:'capture-detail',pedagogical_role:'mechanism',description:'For 84 kW water duty at cp 4.2, the required 10 K rise needs 2 L/s. Pump curve is 160 minus 10q squared kPa, circuit curve is 30q squared. An added restriction increases the circuit coefficient to 70.',controls:[control('restriction','Circuit',[['normal','Clean path'],['restricted','Added restriction']])]},
{id:'branch-flow',label:'Total flow can hide a hot branch',title:'Two litres per second can still leave one branch short',reference:'d10-flow-and-pressure',kind:'capture-detail',pedagogical_role:'counterexample',description:'A controller maintains 2 L/s total water flow for two 42 kW branches. A restriction redistributes flow from 1 plus 1 to .5 plus 1.5 L/s. The mixed return remains 45 degrees, while the restricted branch reaches 55 degrees.',controls:[control('branch','Flow split',[['balanced','Balanced'],['restricted','Restricted branch']])]},
{id:'coolant-interfaces',label:'Qualify the complete liquid path',title:'Every wetted part has to work with the coolant',reference:'d10-cdu-interfaces',kind:'capture-detail',pedagogical_role:'architecture',description:'The cold plate, quick disconnects, hoses, filters and CDU share a coolant circuit. Material and fluid compatibility, qualified pressure, cleanliness and leak isolation are interface requirements.'},
{id:'cooling-retrofit',label:'Choose a retrofit',title:'Which cooling route fits this existing rack?',reference:'d10-cdu-interfaces',kind:'capture-detail',pedagogical_role:'transfer',description:'A 100 kW rack has 20 kW room-air capacity. Available cold plates capture 85 percent into liquid. Existing servers are not immersion-qualified. Choose the route to develop, then establish its hydraulic, fluid and service interfaces.',controls:[control('retrofit','Develop this option',[['air','Air only'],['coldplate','Cold plates + air'],['rear-door','Rear door'],['immersion','Immersion']]),control('reveal','Reasoning',[['hidden','Choose first'],['shown','Show reasoning']])]}
];
function flux(small){const w=small?420:1100;let b='';for(const [i,area]of [4,1].entries()){const cx=small?210:280+i*540,cy=small?140+i*290:225,side=area===4?140:70;b+=text(cx,cy-104,'400 W',34,'heat')+`<rect x="${cx-side/2}" y="${cy-side/2}" width="${side}" height="${side}" fill="var(--heatfill)" stroke="var(--heat)" stroke-width="3"/>`+text(cx,cy+110,`${area} cm² → ${400/area} W/cm²`,29);}return b+text(w/2,small?685:468,'Heat flux = heat ÷ area',29);}
function temperature(state,small){const fluid=Number(state.fluidC),w=small?420:1100;let b=text(w/2,40,`400 W per device · coolant ${fluid}°C · limit 80°C`,small?21:28);for(const [i,r]of [.08,.12].entries()){const x=small?20:35+i*550,y=small?80+i*230:105,cw=small?380:500,m=deviceTemperature({fluidC:fluid,resistance:r});b+=card(x,y,cw,`Thermal resistance ${r} K/W`,`${n(m.junctionC)}°C`,`${n(Math.abs(m.marginK))}°C ${m.passes?'below':'above'} limit`,m.passes?'facility':'fault');}return b+text(w/2,small?620:394,'Chip temperature = coolant + heat × resistance',small?18:29);}
function hydraulics(state,small){const m=hydraulicPoint({resistance:state.restriction==='restricted'?70:30}),w=small?420:1100,left=small?60:90,right=small?385:680,top=60,bottom=small?350:365,x=q=>left+q/3*(right-left),y=p=>bottom-p/200*(bottom-top);let b=path(`M${left} ${top}V${bottom}H${right}`,'muted')+text(left,28,'kPa',23);for(const p of [0,100,200])b+=text(left-10,y(p)+7,p,20,'muted','end');for(const q of [0,1,2,3])b+=text(x(q),bottom+29,q,20,'muted');b+=text((left+right)/2,bottom+62,'Flow (L/s)',24);for(const [f,c]of [[q=>160-10*q*q,'tech'],[q=>(state.restriction==='restricted'?70:30)*q*q,'heat']]){const pts=[];for(let q=0;q<=3;q+=.03){const p=f(q);if(p>=0&&p<=200)pts.push(`${x(q)},${y(p)}`);}b+=`<polyline points="${pts.join(' ')}" fill="none" stroke="var(--${c})" stroke-width="4"/>`;}b+=`<circle cx="${x(m.flowLs)}" cy="${y(m.pressureKPa)}" r="8" fill="var(--ink)"/>`+text(x(.65),y(160)+35,'Pump',25,'tech')+text(x(2.2),85,'Circuit',25,'heat');if(small)b+=card(20,455,380,`${n(m.pressureKPa)} kPa`,`${n(m.flowLs,2)} L/s`,`84 kW → ${n(m.deltaK)}°C rise`);else b+=card(740,110,325,`${n(m.pressureKPa)} kPa`,`${n(m.flowLs,2)} L/s`,`84 kW → ${n(m.deltaK)}°C rise`);return b+text(w/2,small?690:477,'Water · 1 kg/L · cp = 4.2 kJ/(kg·K)',small?21:25);}
function branches(state,small){const m=parallelBranches(state.branch==='restricted'),w=small?420:1100;let b=text(w/2,40,'35°C supply · 42 kW in each branch',small?23:28);for(let i=0;i<2;i++){const x=small?20:35+i*550,y=small?80+i*230:120,cw=small?380:500;b+=card(x,y,cw,`${m.flows[i]} L/s`,`${n(m.returns[i])}°C return`,i===0?'Branch A':'Branch B',m.returns[i]>50?'fault':'tech');}return b+text(w/2,small?625:405,`Total 2 L/s · mixed return ${n(m.mixedReturnC)}°C`,small?25:33)+text(w/2,small?680:465,'Water · 1 kg/L · cp = 4.2 kJ/(kg·K)',small?21:25);}
function interfaces(small){const w=small?420:1100;let b='';const names=['Cold plate','Hoses + connectors','CDU'];for(let i=0;i<3;i++){const x=small?40:25+i*370,y=small?50+i*175:90,cw=small?340:320;b+=box(x,y,cw,110)+text(x+cw/2,y+62,names[i],28)+(i<2?text(small?210:x+345,small?y+146:y+66,small?'↓':'→',37,'tech'):'');}const ys=small?[607,647,687]:[290,350,410];['Fluid + materials','Pressure + cleanliness','Leak detection + isolation'].forEach((v,i)=>b+=text(w/2,ys[i],v,small?26:34));return b;}
function retrofit(state,small){const w=small?420:1100;let b=text(w/2,38,'100 kW rack · 20 kW room-air capacity',small?23:30);const cx=small?210:550;b+=box(cx-110,78,220,160)+text(cx,136,'Existing rack',27)+text(cx,198,'100 kW',44,'heat');b+=text(w/2,small?282:285,'Servers are not immersion-qualified',small?21:27);const y=small?320:325;b+=card(small?15:60,y,small?190:450,'Cold plates','85 kW','To liquid','tech')+card(small?215:590,y,small?190:450,'Other parts','15 kW','To room air','heat');if(state.reveal==='shown'){const a=retrofitAnswers[state.retrofit];const lines=a.correct?['Develop the cold-plate route.','15 kW fits the 20 kW air allowance.','Check the liquid and service interfaces.']:state.retrofit==='air'?['Air-only needs 100 kW.','The room can remove only 20 kW.']:state.retrofit==='rear-door'?['First establish the door’s thermal duty,','server airflow and service clearance.']:['These servers are not','qualified for immersion.'];lines.forEach((v,i)=>b+=text(w/2,(small?570:540)+i*35,v,small?22:27,a.correct?'facility':'fault'));}return b;}
export function renderCapture(id,state,compact){switch(id){case'local-heat-flux':return flux(compact);case'device-temperature':return temperature(state,compact);case'pump-operating-point':return hydraulics(state,compact);case'branch-flow':return branches(state,compact);case'coolant-interfaces':return interfaces(compact);case'cooling-retrofit':return retrofit(state,compact);default:throw new Error(`Unknown capture scene ${id}`);}}
