export const initialState = Object.freeze({load:'row', rowCount:3, powerFactor:1, transformerCase:'nominal', balanced:true, faultStage:'normal', diagnosisStage:'fault', cycleDegrees:30, voltageView:'meter'});
const read = id => `../index.html#d04-${id}`;
const labels = {"distribution-purpose": "Campus to rack", "campus-route": "Trace the load", "one-line": "Single-line diagrams", "switchgear-anatomy": "Inside switchgear", "protection-relay": "Relay and breaker", "isolation-surge": "Disconnect the transformer", "surge-protection": "Surge protection", "busway-introduction": "What is a busway?", "compass-skid": "Compass integrated skid", "local-stepdown": "Transformer location", "transformer-taps": "Transformer voltage and taps", "building-branches": "Building branches", "distribution-units": "Floor PDU, rack PDU, PSU", "busway-branches": "Busway and tap-offs", "fujitsu-busway": "Fujitsu busway", "row-growth": "Shared conductor capacity", "power-factor-explained": "Apparent power and power factor", "power-factor": "Power factor", "phase-loading": "Phase imbalance", "feeder-diagnosis": "Failed interruption", "distribution-handoff": "Continuity handoff"};
const scene = (id,title,role,objective,reference,explanation,extra={}) => ({id,label:labels[id] || title,title,pedagogical_role:role,objectives:[objective],reference:read(reference),explanation,...extra});
export const learning_contract = Object.freeze({
 driving_question:'How does campus power reach a rack through equipment that can carry, switch and protect it?',
 fixed_boundary:'High-voltage AC through the campus and hall transformers to rack inputs and separate auxiliary branches.',
 changed_variable:'Transformer location and tap ratio, branch connections, power factor, phase allocation and fault interruption.',
 primary_payoff:'Identify the equipment on a load path and explain how its physical job constrains the service.',
 misconception:'Available campus megawatts or spare tap-off positions establish a complete usable power path.',
 closing_question:'Which healthy branch loses supply when upstream backup clears a failed feeder interruption?',
});
export const scenes = [
  scene('distribution-purpose','Follow power from the campus connection to a working rack','problem','D04.1','read-the-power-train','A campus connection feeds a branching electrical network. Follow where voltage changes, where loads share conductors, and where each rating applies before approving another hall.'),
  scene('campus-route','Trace the load back to high-voltage AC','architecture','D04.1','read-the-power-train','Select the rack, cooling pump or future hall. This teaching network uses Abilene’s 345 kV expansion connection and 34.5 kV campus distribution as its voltage references. Medium-voltage switchgear supplies hall feeders. A second transformer provides 480 V for the building bus, where IT and cooling branches separate. The future hall has its own open feeder. Mortenson reports the 345 kV expansion; a Longhorn review drawing identifies a 34.5 kV Lancium feed. These sources support the voltage references, not a complete as-built 345/34.5 kV campus one-line. The 480 V building stage remains a teaching example.',{controls:[{key:'load',label:'Trace a load',options:[['row','Rack'],['cooling','Cooling pump'],['future','Future hall']]}]}),
  scene('campus-switchgear-focus','Now look inside the medium-voltage switchgear','architecture','D04.1','read-the-power-train','Return to the same campus distribution network. The outline picks out the medium-voltage switchgear between the campus transformer and the hall feeders. Keep its position in the power path in mind while the next scene opens a real switchgear panel.',{controls:[{key:'load',label:'Trace a load',options:[['row','Rack'],['cooling','Cooling pump'],['future','Future hall']]}]}),
  scene('switchgear-anatomy','Inside a Siemens NXAirS switchgear panel','mechanism','D04.1','read-the-power-train','The supplied labeled Siemens sectional image identifies the busbars, withdrawable vacuum circuit breaker, earthing switch, cable connection and low-voltage control compartment. The three corrected leaders follow Siemens’s original component callouts on catalog page 12. Protection and control equipment occupies the low-voltage compartment; power current passes through the bus, breaker and outgoing cable. This named NXAirS family is rated up to 12 kV. It is a separate anatomy example, not the 34.5 kV teaching installation or the 8DJH 36 equipment in the Compass skid.',{imageTitle:true}),
  scene('campus-three-phase-focus','Now follow the 480 V three-phase connection','architecture','D04.1','read-the-power-train','Return to the same overview after inspecting switchgear. The outline follows the 480 V AC conductor from the hall transformer into the building bus. The next drawing expands a circuit from that bus into its individual phase, neutral and protective-earth conductors.',{controls:[{key:'load',label:'Trace a load',options:[['row','Rack'],['cooling','Cooling pump'],['future','Future hall']]}]}),
  scene('one-line','What a single-line diagram hides','mechanism','D04.1','read-the-power-train','The single-line drawing compresses multiphase connections. The expanded low-voltage example shows three phases, neutral and protective earth. Neutral carries return current for phase-to-neutral loads; protective earth has a different job. Neither is an extra phase.',{hideTitle:true}),
  scene('three-phase','Three balanced phases fill the power dips of a single phase','mechanism','D04.1','read-the-power-train','Expand the three phase conductors into a balanced wye-connected resistive load. Each phase supplies one-third of the 100 kW average power, with its voltage and current shifted by 120 degrees from the other phases. Scrubbing the cycle shows that the three phase powers add to 100 kW at every instant. Signed line currents add to zero: current entering through some phase conductors returns through the others. A neutral would carry zero current in this balanced sinusoidal model. Unequal loads and nonlinear current waveforms change that result; neutral and protective earth remain different conductors. The next view shows where the 480 V label is measured.',{label:'Three-phase current and power'}),
  scene('voltage-basis','480 V is the voltage between two live phase conductors','mechanism','D04.1','read-the-power-train','The voltmeter connects to live phases L1 and L2, not to earth. Any phase pair in this balanced system measures 480 V RMS; phase-to-neutral voltage is 480 divided by the square root of three, approximately 277 V RMS. RMS describes the effective value over a cycle rather than a fixed signed voltage. Switch to the pair waveforms to see why three 480 V readings are not successive 480 V steps: their instantaneous signed differences add to zero, while all three pairs have the same RMS magnitude. The 480 V building bus in the campus overview uses this line-to-line convention. Its single-phase equipment can use phase-to-neutral or phase-to-phase connections according to its input rating.',{label:'Measure the 480 V supply'}),
  scene('protection-relay','The relay detects the fault; the breaker interrupts the current','mechanism','D04.1','read-the-power-train','The current transformer (CT), drawn as a ring around the feeder conductor, supplies a scaled current measurement to the protection relay. When its configured protection criteria are met, the relay sends a trip command to the breaker trip coil. The breaker contacts separate and the interrupting chamber extinguishes the arc. The relay itself does not carry or interrupt the feeder current. A persistent current after a trip command requires breaker-failure or backup protection, developed in Chapter 7. The first three states show the current-measurement and trip sequence. The fourth view introduces CT and capacitor voltage transformer (CVT) measurements at a 345 kV connection. The CVT branches from phase to earth and supplies a scaled voltage signal; it is not in the series power path. At medium voltage, voltage measurement commonly uses an inductive VT or a voltage sensor instead. The illustrated overcurrent trip uses CT current; not every relay function needs voltage. This is a functional example, not an Abilene instrument-transformer equipment schedule.',{controls:[{key:'faultStage',label:'Feeder event',options:[['normal','Normal'],['detected','Fault detected'],['cleared','Breaker cleared fault'],['measurements','CT + CVT at 345 kV']]}]}),
  scene('isolation-surge','A disconnector isolates the transformer from its supply','mechanism','D04.1','read-the-power-train','Locate the breaker, disconnector, transformer and hall on the same feeder. With the breaker open, the illustrated disconnector provides an air gap in the series path to the transformer. A plain disconnector is not a fault-current interrupter; the two devices have distinct duties. The illustration shows the electrical separation, not a complete maintenance procedure.'),
  scene('surge-protection','A surge arrester protects transformer insulation from overvoltage','mechanism','D04.1','read-the-power-train','Keep the same source-to-hall circuit in view, now with the normal series path connected. The arrester is a parallel connection from the phase conductor near the transformer to earth. During an overvoltage it conducts surge current and limits the stress on the transformer insulation. It does not open the feeder or isolate the transformer.'),
  scene('compass-co-design','Design the switchgear and transformer as one package','architecture','D04.1','read-the-power-train','Compass and Siemens jointly developed a prefabricated medium-voltage skid for Compass data centers. The switchgear still switches and protects; the transformer still changes voltage. Designing the package together coordinates their voltage/current requirements, protection and physical connections before the assembly reaches the site. The diagram shows the package concept, not a detailed Compass engineering drawing or an Abilene product selection. The following photograph supplies the real case.'),
  scene('compass-skid','Siemens builds switchgear and transformer skids for Compass data centers','architecture','D04.1','read-the-power-train','Siemens and Compass Datacenters co-developed a custom medium-voltage skid for data centers using 8DJH 36 switchgear and a transformer. Siemens supplies this prefabricated package; Compass is the data-center customer. The original factory photograph shows its switchgear portion; the transformer is not visible.',{case:'compass'}),
  scene('local-stepdown','Put the high-current route close to the hall','comparison','D04.2','current-and-rating','Keep a balanced 2 MW load, PF 1, and both voltage levels fixed. Moving the step-down transformer from the campus entrance to the hall changes which voltage crosses the 450 m route. At 34.5 kV that route carries about 33.5 A; at 480 V it carries about 2,406 A. Cable, insulation and equipment requirements change with the route; these currents do not establish actual losses.'),
  scene('transformer-taps','A tap changes the transformer voltage ratio','mechanism','D04.1','read-the-power-train','The 480-to-120 V example from Hammond Power Solutions uses 80 connected primary turns and 20 secondary turns. Raising the source to 504 V with the same connection raises the ideal output to 126 V. The 504 V tap connects 84 primary turns, restoring a 120 V output at that source voltage. A tap selects how many winding turns are connected; the source voltage and connection jointly determine output. These are three configured states at fixed frequency, without automatic tap control. Actual permitted connections and change procedures belong to the selected transformer.',{controls:[{key:'transformerCase',label:'Source and connection',options:[['nominal','480 V supply'],['supply-rise','504 V, same tap'],['matched-tap','504 V, matched tap']]}]}),
  scene('transformer-taps-photo','The taps are physical winding connections','mechanism','D04.1','read-the-power-train','The supplied photograph connects the turns-ratio example to real hardware. Multiple winding connection points are visible on the three coils, and the supplied red marking identifies one attached lead. The photograph has no provided manufacturer or connection schedule; no exact voltage, turn count or permitted connection is inferred from it. It illustrates what a winding tap looks like, without changing the previous numerical example.'),
  scene('building-branches','The building bus feeds more than IT','architecture','D04.1','read-the-power-train','The low-voltage switchboard collects an incoming supply on busbars and distributes it through outgoing circuits. Cooling, lighting, controls and IT are separate loads. Where a UPS belongs depends on which loads require its service; the normal-flow diagram leaves that continuity function as an identified block.'),
  scene('distribution-units','A floor PDU, rack PDU and PSU perform different jobs','comparison','D04.1','read-the-power-train','A floor power distribution unit distributes power to outgoing feeders or branch circuits. A rack PDU distributes AC to server outlets; a server PSU converts AC to DC. The illustrated floor PDU includes a transformer, while other designs distribute power without changing voltage.'),
  scene('busway-introduction','A busway carries shared power above a row of racks','architecture','D04.1','read-the-power-train','A busway encloses continuous power conductors in a manufactured housing. An end feed connects it to the upstream supply. In this overhead data-hall arrangement, the housing runs along the rack row and accepts branch connections near the loads. First identify that shared conductor assembly; the next slide then follows one tap-off from those conductors to a rack.'),
  scene('busway-branches','A tap-off connects one rack to the overhead busway','mechanism','D04.1','read-the-power-train','An end feed supplies the busway conductors. A tap-off makes a branch with its specified protection and connector, then a short cord supplies the rack. The bus carries the sum of the downstream loads. A busway and a cable both have conductor and thermal constraints; their physical arrangement and branch installation differ.'),
  scene('fujitsu-busway','Fujitsu used overhead busway to add rack branches without underfloor cabling','comparison','D04.1','read-the-power-train','For an expansion of a managed 3.2 MW data center north of London, Fujitsu selected 250 A Starline Track Busway. Its existing hall used cables below the floor; the new design kept that space available for cooling and added metering at tap-offs. A movable branch connection shortened the work of accommodating changing rack requirements.',{case:'fujitsu'}),
  scene('row-growth','A new tap-off still uses the same upstream conductors','counterexample','D04.2','current-and-rating','The row example uses 415 V balanced three-phase, PF 1 and a supplied 250 A usable budget. Three 40 kW racks require 167 A at the end feed. A fourth raises it to 223 A, although each rack branch still carries about 56 A. A fifth would need about 278 A. Spare physical tap positions do not add current capacity.',{controls:[{key:'rowCount',label:'Connected racks',options:[[3,'Three × 40 kW'],[4,'Four × 40 kW'],[5,'Five × 40 kW']]}]}),
  scene('apparent-power-beer','Apparent power is like a glass of beer','mechanism','D04.2','current-and-rating','The supplied glass-of-beer analogy labels liquid as active power, foam as reactive power, and the whole glass as apparent power. Use it as a visual memory cue for equipment capacity. The literal heights are not an addition rule. The following comparison introduces the numerical example; the power triangle then explains the relationship between its quantities.',{imageTitle:true}),
  scene('power-factor-explained','Apparent power and power factor','mechanism','D04.2','current-and-rating','The supplied comparison keeps real input P at 900 kW and balanced three-phase voltage at 480 V line-to-line. Apparent power S is the RMS voltage/current loading: S = P/PF. PF 1 gives 900 kVA and 1,083 A; PF 0.8 gives 1,125 kVA and 1,353 A. Those are 90% and 112.5% of a 1,000 kVA rating. Real power is average energy transfer, including useful output and losses; PF is P/S, not conversion efficiency. Reactive power Q describes the cyclic exchange of energy with electric and magnetic fields. With sinusoidal voltage and current, S² = P² + Q²: this example has Q = 0 at PF 1 and |Q| = 675 kvar at PF 0.8. Harmonic distortion can also lower true power factor; P and PF alone do not uniquely determine Q in that case.',{imageTitle:true}),
  scene('power-triangle','The Power Triangle','mechanism','D04.2','current-and-rating','The horizontal leg is real power P = 900 kW; the vertical leg is reactive power Q = 675 kvar; apparent power S = 1,125 kVA is the hypotenuse. These are perpendicular components, so S² = P² + Q², not P + Q. Power factor is P/S = 900/1,125 = 0.80. This is the PF 0.80 load introduced in the preceding transformer comparison. Real power is the average transfer of energy, including useful output and losses. Reactive power describes energy exchanged with magnetic or electric fields, not 675 kW consumed as waste heat. The right triangle assumes sinusoidal voltage and current; its angle is their phase displacement. Harmonics can also lower true power factor, so a low measured PF alone does not establish this Q. Schneider Electric documents both the sinusoidal power triangle and the distinction between total and displacement power factor.',{label:'The power triangle',sources:['https://www.electrical-installation.org/enwiki/Definition_of_reactive_power','https://www.electrical-installation.org/enwiki/Harmonic_distortion_indicators_-_Power_factor']}),
  scene('power-factor-quote','Power factor and conductor heating','mechanism','D04.2','current-and-rating','The course author’s supplied passage explains the field-energy exchange behind reactive current, then distinguishes power factor from conversion efficiency. It follows the real/apparent-power comparison and precedes the interactive transformer-loading example. The quote is course teaching text, not an attributed manufacturer or Microsoft statement.',{hideTitle:true}),
  scene('power-factor','Lower power factor uses more of the transformer’s current capacity','comparison','D04.2','current-and-rating','Keep real AC input at 900 kW and line-to-line voltage at 480 V in a balanced three-phase teaching example. At PF 1 the load needs 900 kVA; at PF 0.8 it needs 1,125 kVA. The supplied 1,000 kVA transformer limit is a current-and-voltage rating, not an energy-loss allowance. Apparent power S = P / PF; line current I = S / (√3 V). No converter efficiency is changed or assumed by this comparison.',{controls:[{key:'powerFactor',label:'Input power factor',options:[[1,'1.00'],[.9,'0.90'],[.8,'0.80']]}]}),
  scene('phase-loading','A three-phase rack PDU feeds single-phase PSU groups','counterexample','D04.2','current-and-rating','Three equal phase voltages do not force equal currents. In this 277 V phase-to-neutral example, six single-phase PSU groups each draw 20 A. A 2/2/2 assignment draws 40 A per phase; a 4/1/1 assignment draws 80/20/20 A. The 60 A teaching limit is exceeded on L1 even though total useful load is unchanged. The neutral carries the instantaneous sum returning from the three branches; sinusoidal currents cancel only when balanced. Real nonlinear PSU currents add harmonic considerations. This is a conceptual load allocation, not instructions for moving live connections.',{controls:[{key:'balanced',label:'Allocate six PSU groups',options:[[true,'Spread across phases'],[false,'Crowded onto L1']]}]}),
  scene('feeder-diagnosis','Upstream backup opens when the feeder breaker fails to open','transfer','D04.4','read-the-power-train','Hall A has a feeder fault. Its relay has issued a trip, but its breaker remains closed and fault current continues. Hall B has no local fault and shares the incoming bus. Before opening the backup breaker, predict which hall connections it will remove. Upstream backup protection isolates the persistent fault by opening the shared incoming breaker, also disconnecting Hall B. The failed feeder breaker and the functioning incoming breaker are two different devices.',{controls:[{key:'diagnosisStage',label:'Breaker failure',options:[['fault','Feeder trip fails'],['backup','Upstream backup opens']]}]}),
  scene('distribution-handoff','Next: keep racks and cooling running through an interruption','transfer','D04.1','read-the-power-train','The normal-load account establishes voltage interfaces, connected loads and usable limits. The next chapter changes the operating state: which paths keep IT and the supporting pumps powered when supply or equipment is unavailable? Preserve the same boundaries when adding storage and alternate paths.'),
];
