export const initialState = Object.freeze({load:'row', rowCount:3, powerFactor:1, balanced:true, faultStage:'normal', diagnosis:'breaker', reveal:false});
const read = id => `../index.html#d04-${id}`;
const labels = {"distribution-purpose": "Campus to rack", "abilene-distribution": "Abilene", "campus-route": "Trace the load", "one-line": "Single-line diagrams", "switchgear-anatomy": "Inside switchgear", "protection-relay": "Relay and breaker", "isolation-surge": "Isolation and surges", "compass-skid": "Compass integrated skid", "local-stepdown": "Transformer location", "building-branches": "Building branches", "distribution-units": "Floor PDU, rack PDU, PSU", "busway-branches": "Busway and tap-offs", "fujitsu-busway": "Fujitsu busway", "row-growth": "Shared conductor capacity", "power-factor": "Power factor", "phase-loading": "Phase imbalance", "feeder-diagnosis": "Failed interruption", "distribution-handoff": "Continuity handoff"};
const scene = (id,title,role,objective,reference,explanation,extra={}) => ({id,label:labels[id] || title,title,pedagogical_role:role,objectives:[objective],reference:read(reference),explanation,...extra});
export const learning_contract = Object.freeze({
 driving_question:'How does campus power reach a rack through equipment that can carry, switch and protect it?',
 fixed_boundary:'Campus AC connection through building distribution to rack inputs and separate auxiliary branches.',
 changed_variable:'Transformer location, branch connections, power factor, phase allocation and fault interruption.',
 primary_payoff:'Identify the equipment on a load path and explain how its physical job constrains the service.',
 misconception:'Available campus megawatts or spare tap-off positions establish a complete usable power path.',
 closing_question:'What failed when a relay issued a trip but fault current continued?',
});
export const aliases = Object.freeze({'feeder-switching':'protection-relay','transformer':'local-stepdown','meter-boundary':'building-branches','output-to-input':'power-factor','apparent-power':'power-factor','current-rating':'power-factor','thermal-limits':'phase-loading','reserve':'row-growth','phase-opening':'building-branches','hot-weather':'building-branches','expansion-decision':'feeder-diagnosis'});
export const chapter8Aliases = Object.freeze({'conversion-locations':'conversion-farther-upstream','green-dc':'green-zurich-west','green-path':'green-zurich-west','loss-ledger':'ac-dc-ledger','relocated-heat':'conversion-farther-upstream'});
export const scenes = [
  scene('distribution-purpose','Follow power from the campus connection to a working rack','problem','D04.1','read-the-power-train','A campus connection feeds a branching electrical network. Follow where voltage changes, where loads share conductors, and where each rating applies before approving another hall.'),
  scene('abilene-distribution','Abilene needs a complete path to every hall','problem','D04.1','read-the-power-train','Return to the original Oracle/OpenAI campus in Abilene, shown in Oracle’s July 15, 2026 data-hall aerial. A supply connection must become a complete distribution path to each load. The public photograph does not establish feeder routes or equipment ratings; use the following defined campus model to learn how to read those details.',{case:'abilene'}),
  scene('campus-route','Trace one load back to the connection','architecture','D04.1','read-the-power-train','Select the rack or cooling pump. Their paths share a campus feeder and a building bus, then separate. The future hall has its own open feeder. A drawn route only supplies a load when the required connections exist and are in the stated operating condition.',{controls:[{key:'load',label:'Load',options:[['row','Rack'],['cooling','Cooling pump'],['future','Future hall']]}]}),
  scene('one-line','Read a three-phase circuit from a single line','mechanism','D04.1','read-the-power-train','The single-line drawing compresses multiphase connections. The expanded low-voltage example shows three phases, neutral and protective earth. Neutral carries return current for phase-to-neutral loads; protective earth has a different job. Neither is an extra phase.'),
  scene('switchgear-anatomy','Switchgear puts the bus, switching and protection in one assembly','mechanism','D04.1','read-the-power-train','A switchgear assembly includes insulated bus conductors, feeder switching equipment, instrument transformers or sensors, protection and controls. The breaker carries and interrupts power current; a protection relay works with low-energy measurement and trip signals. Actual equipment may use switches and fuses instead of this breaker-based arrangement. The conceptual cutaway identifies functions, not the internal layout of the Compass product.'),
  scene('protection-relay','The relay detects the fault; the breaker interrupts the current','mechanism','D04.1','read-the-power-train','Current transformers provide scaled measurements to the feeder protection relay. When its configured protection criteria are met, the relay sends a trip command to the breaker trip coil. The breaker contacts separate and the interrupting chamber extinguishes the arc. The relay itself does not carry or interrupt the feeder current. A persistent current after a trip command requires breaker-failure or backup protection, developed in Chapter 7. This three-state diagram is a causal sequence without a specified clearing time.',{controls:[{key:'faultStage',label:'Feeder event',options:[['normal','Normal'],['detected','Fault detected'],['cleared','Breaker cleared fault']]}]}),
  scene('isolation-surge','Isolation and surge protection solve different electrical problems','comparison','D04.1','read-the-power-train','A plain disconnector establishes an isolating gap; it is not a fault-current interrupting device. Switch-disconnectors and circuit-breaker disconnectors combine capabilities only where rated for those duties. A metal-oxide surge arrester becomes conductive during an overvoltage, diverting surge current and limiting the voltage imposed on equipment insulation. It does not maintain a normal supply or provide a maintenance isolation gap. These are distinct functions, not interchangeable switches.'),
  scene('compass-skid','Compass packages switching and transformation on one transportable skid','architecture','D04.1','read-the-power-train','Siemens and Compass co-developed an integrated medium-voltage skid using 8DJH 36 switchgear and a transformer. The package combines functions without merging them: switchgear manages connections, while the transformer changes voltage. The photograph shows the switchgear portion in the factory. Its product-family name does not establish the actual site voltage.',{case:'compass'}),
  scene('local-stepdown','Put the high-current route close to the hall','comparison','D04.2','current-and-rating','Keep a balanced 2 MW load, PF 1, and both voltage levels fixed. Moving the step-down transformer from the campus entrance to the hall changes which voltage crosses the 450 m route. At 13.8 kV that route carries about 84 A; at 480 V it carries about 2,406 A. Cable, insulation and equipment requirements change with the route; these currents do not establish actual losses.'),
  scene('building-branches','The building bus feeds more than IT','architecture','D04.1','read-the-power-train','The low-voltage switchboard collects an incoming supply on busbars and distributes it through outgoing circuits. Cooling, lighting, controls and IT are separate loads. Where a UPS belongs depends on which loads require its service; the normal-flow diagram leaves that continuity function as an identified block.'),
  scene('distribution-units','A floor PDU, rack PDU and PSU perform different jobs','comparison','D04.1','read-the-power-train','A floor power distribution unit may package a transformer, branch breakers and metering. A rack PDU commonly distributes an existing AC supply to server outlets. The name alone cannot tell you whether voltage changes. Follow the labeled input and output of the selected equipment.'),
  scene('busway-branches','A tap-off creates a branch from a shared bus','mechanism','D04.1','read-the-power-train','An end feed supplies the busway conductors. A tap-off makes a branch with its specified protection and connector, then a short cord supplies the rack. The bus carries the sum of the downstream loads. A busway and a cable both have conductor and thermal constraints; their physical arrangement and branch installation differ.'),
  scene('fujitsu-busway','Fujitsu used overhead busway to add rack branches without underfloor cabling','comparison','D04.1','read-the-power-train','For an expansion of a managed 3.2 MW data center north of London, Fujitsu selected 250 A Starline Track Busway. Its existing hall used cables below the floor; the new design kept that space available for cooling and added metering at tap-offs. A movable branch connection shortened the work of accommodating changing rack requirements.',{case:'fujitsu'}),
  scene('row-growth','A new tap-off still uses the same upstream conductors','counterexample','D04.2','current-and-rating','The row example uses 415 V balanced three-phase, PF 1 and a supplied 250 A usable budget. Three 40 kW racks require 167 A at the end feed. A fourth raises it to 223 A, although each rack branch still carries about 56 A. A fifth would need about 278 A. Spare physical tap positions do not add current capacity.',{controls:[{key:'rowCount',label:'Connected racks',options:[[3,'Three × 40 kW'],[4,'Four × 40 kW'],[5,'Five × 40 kW']]}]}),
  scene('power-factor','Lower power factor uses more of the transformer’s current capacity','comparison','D04.2','current-and-rating','Keep real AC input at 900 kW and line-to-line voltage at 480 V in a balanced three-phase teaching example. At PF 1 the load needs 900 kVA; at PF 0.8 it needs 1,125 kVA. The supplied 1,000 kVA transformer limit is a current-and-voltage rating, not an energy-loss allowance. Apparent power S = P / PF; line current I = S / (√3 V). No converter efficiency is changed or assumed by this comparison.',{controls:[{key:'powerFactor',label:'Input power factor',options:[[1,'1.00'],[.9,'0.90'],[.8,'0.80']]}]}),
  scene('phase-loading','Single-phase rack loads can overload one phase conductor','counterexample','D04.2','current-and-rating','Three equal phase voltages do not force equal currents. In this 277 V phase-to-neutral example, six single-phase PSU groups each draw 20 A. A 2/2/2 assignment draws 40 A per phase; a 4/1/1 assignment draws 80/20/20 A. The 60 A teaching limit is exceeded on L1 even though total useful load is unchanged. The neutral carries the instantaneous sum returning from the three branches; sinusoidal currents cancel only when balanced. Real nonlinear PSU currents add harmonic considerations. This is a conceptual load allocation, not instructions for moving live connections.',{controls:[{key:'balanced',label:'Single-phase load allocation',options:[[true,'2 / 2 / 2 groups'],[false,'4 / 1 / 1 groups']]}]}),
  scene('feeder-diagnosis','The relay issued a trip, but feeder current is still flowing','transfer','D04.4','read-the-power-train','The downstream feeder relay records a trip command, but its breaker still reports closed and the current sensor still sees fault current. Diagnose the failed interruption rather than buying more campus megawatts. Breaker-failure protection can command upstream or adjacent breakers, enlarging the outage boundary. The next chapter tests how alternative paths, UPS systems and supporting cooling loads affect the resulting service.',{controls:[{key:'diagnosis',label:'What failed?',options:[['capacity','Campus capacity'],['breaker','Feeder interruption'],['surge','Surge protection']]}],reveal:'reveal'}),
  scene('distribution-handoff','Which loads lose supply when the common feeder opens?','transfer','D04.1','read-the-power-train','The normal-load account establishes voltage interfaces, connected loads and usable limits. The next chapter changes the operating state: which paths keep IT and the supporting pumps powered when supply or equipment is unavailable? Preserve the same boundaries when adding storage and alternate paths.'),
];
