export const initialState = Object.freeze({load:'row', rowCount:3, powerFactor:1, balanced:true, faultStage:'normal', diagnosisStage:'fault'});
const read = id => `../index.html#d04-${id}`;
const labels = {"distribution-purpose": "Campus to rack", "campus-route": "Trace the load", "one-line": "Single-line diagrams", "switchgear-anatomy": "Inside switchgear", "protection-relay": "Relay and breaker", "isolation-surge": "Disconnect the transformer", "surge-protection": "Surge protection", "busway-introduction": "What is a busway?", "compass-skid": "Compass integrated skid", "local-stepdown": "Transformer location", "building-branches": "Building branches", "distribution-units": "Floor PDU, rack PDU, PSU", "busway-branches": "Busway and tap-offs", "fujitsu-busway": "Fujitsu busway", "row-growth": "Shared conductor capacity", "power-factor": "Power factor", "phase-loading": "Phase imbalance", "feeder-diagnosis": "Failed interruption", "distribution-handoff": "Continuity handoff"};
const scene = (id,title,role,objective,reference,explanation,extra={}) => ({id,label:labels[id] || title,title,pedagogical_role:role,objectives:[objective],reference:read(reference),explanation,...extra});
export const learning_contract = Object.freeze({
 driving_question:'How does campus power reach a rack through equipment that can carry, switch and protect it?',
 fixed_boundary:'High-voltage AC through the campus and hall transformers to rack inputs and separate auxiliary branches.',
 changed_variable:'Transformer location, branch connections, power factor, phase allocation and fault interruption.',
 primary_payoff:'Identify the equipment on a load path and explain how its physical job constrains the service.',
 misconception:'Available campus megawatts or spare tap-off positions establish a complete usable power path.',
 closing_question:'Which healthy branch loses supply when upstream backup clears a failed feeder interruption?',
});
export const aliases = Object.freeze({'abilene-distribution':'campus-route','feeder-switching':'protection-relay','transformer':'local-stepdown','meter-boundary':'building-branches','output-to-input':'power-factor','apparent-power':'power-factor','current-rating':'power-factor','thermal-limits':'phase-loading','reserve':'row-growth','phase-opening':'building-branches','hot-weather':'building-branches','expansion-decision':'feeder-diagnosis'});
export const chapter8Aliases = Object.freeze({'conversion-locations':'conversion-farther-upstream','green-dc':'green-zurich-west','green-path':'green-zurich-west','loss-ledger':'ac-dc-ledger','relocated-heat':'conversion-farther-upstream'});
export const scenes = [
  scene('distribution-purpose','Follow power from the campus connection to a working rack','problem','D04.1','read-the-power-train','A campus connection feeds a branching electrical network. Follow where voltage changes, where loads share conductors, and where each rating applies before approving another hall.'),
  scene('campus-route','Trace the load back to high-voltage AC','architecture','D04.1','read-the-power-train','Select the rack, cooling pump or future hall. In this teaching network, 138 kV AC enters a campus substation and is transformed to 13.8 kV. Medium-voltage switchgear supplies hall feeders. A second transformer provides 480 V for the building bus, where IT and cooling branches separate. The future hall has its own open feeder. These defined voltages explain two stages of transformation; they are not an asserted Abilene one-line.',{controls:[{key:'load',label:'Trace a load',options:[['row','Rack'],['cooling','Cooling pump'],['future','Future hall']]}]}),
  scene('one-line','Read a three-phase circuit from a single line','mechanism','D04.1','read-the-power-train','The single-line drawing compresses multiphase connections. The expanded low-voltage example shows three phases, neutral and protective earth. Neutral carries return current for phase-to-neutral loads; protective earth has a different job. Neither is an extra phase.'),
  scene('switchgear-anatomy','Inside a Siemens NXAirS switchgear panel','mechanism','D04.1','read-the-power-train','The original Siemens sectional drawing identifies the busbar, withdrawable circuit-breaker, cable-connection and low-voltage compartments. Protection and control equipment occupies the low-voltage compartment; power current passes through the bus, breaker and outgoing cable. This named NXAirS family is rated up to 12 kV. It is a separate anatomy example, not the 13.8 kV teaching installation or the 8DJH 36 equipment in the Compass skid.'),
  scene('protection-relay','The relay detects the fault; the breaker interrupts the current','mechanism','D04.1','read-the-power-train','Current transformers provide scaled measurements to the feeder protection relay. When its configured protection criteria are met, the relay sends a trip command to the breaker trip coil. The breaker contacts separate and the interrupting chamber extinguishes the arc. The relay itself does not carry or interrupt the feeder current. A persistent current after a trip command requires breaker-failure or backup protection, developed in Chapter 7. This three-state diagram is a causal sequence without a specified clearing time.',{controls:[{key:'faultStage',label:'Feeder event',options:[['normal','Normal'],['detected','Fault detected'],['cleared','Breaker cleared fault']]}]}),
  scene('isolation-surge','A disconnector isolates the transformer from its supply','mechanism','D04.1','read-the-power-train','Locate the breaker, disconnector, transformer and hall on the same feeder. With the breaker open, the illustrated disconnector provides an isolating gap in the series path to the transformer. A plain disconnector is not a fault-current interrupter; the two devices have distinct duties. The illustration shows the electrical separation, not a complete maintenance procedure.'),
  scene('surge-protection','A surge arrester protects transformer insulation from overvoltage','mechanism','D04.1','read-the-power-train','Keep the same source-to-hall circuit in view, now with the normal series path connected. The arrester is a parallel connection from the phase conductor near the transformer to earth. During an overvoltage it conducts surge current and limits the stress on the transformer insulation. It does not open the feeder or isolate the transformer.'),
  scene('compass-skid','Siemens supplies a combined switchgear and transformer skid for Compass','architecture','D04.1','read-the-power-train','Siemens and Compass co-developed a custom medium-voltage skid using 8DJH 36 switchgear and a transformer. Siemens supplies this prefabricated package; Compass is the customer, not the name of a Siemens catalog range. This is an actual manufacturer-built package. The original factory photograph shows its switchgear portion; the transformer is not visible.',{case:'compass'}),
  scene('local-stepdown','Put the high-current route close to the hall','comparison','D04.2','current-and-rating','Keep a balanced 2 MW load, PF 1, and both voltage levels fixed. Moving the step-down transformer from the campus entrance to the hall changes which voltage crosses the 450 m route. At 13.8 kV that route carries about 84 A; at 480 V it carries about 2,406 A. Cable, insulation and equipment requirements change with the route; these currents do not establish actual losses.'),
  scene('building-branches','The building bus feeds more than IT','architecture','D04.1','read-the-power-train','The low-voltage switchboard collects an incoming supply on busbars and distributes it through outgoing circuits. Cooling, lighting, controls and IT are separate loads. Where a UPS belongs depends on which loads require its service; the normal-flow diagram leaves that continuity function as an identified block.'),
  scene('distribution-units','A floor PDU, rack PDU and PSU perform different jobs','comparison','D04.1','read-the-power-train','A floor power distribution unit may package a transformer, branch breakers and metering. A rack PDU commonly distributes an existing AC supply to server outlets. The name alone cannot tell you whether voltage changes. Follow the labeled input and output of the selected equipment.'),
  scene('busway-introduction','A busway carries shared power above a row of racks','architecture','D04.1','read-the-power-train','A busway encloses continuous power conductors in a manufactured housing. An end feed connects it to the upstream supply. In this overhead data-hall arrangement, the housing runs along the rack row and accepts branch connections near the loads. First identify that shared conductor assembly; the next slide then follows one tap-off from those conductors to a rack.'),
  scene('busway-branches','A tap-off connects one rack to the overhead busway','mechanism','D04.1','read-the-power-train','An end feed supplies the busway conductors. A tap-off makes a branch with its specified protection and connector, then a short cord supplies the rack. The bus carries the sum of the downstream loads. A busway and a cable both have conductor and thermal constraints; their physical arrangement and branch installation differ.'),
  scene('fujitsu-busway','Fujitsu used overhead busway to add rack branches without underfloor cabling','comparison','D04.1','read-the-power-train','For an expansion of a managed 3.2 MW data center north of London, Fujitsu selected 250 A Starline Track Busway. Its existing hall used cables below the floor; the new design kept that space available for cooling and added metering at tap-offs. A movable branch connection shortened the work of accommodating changing rack requirements.',{case:'fujitsu'}),
  scene('row-growth','A new tap-off still uses the same upstream conductors','counterexample','D04.2','current-and-rating','The row example uses 415 V balanced three-phase, PF 1 and a supplied 250 A usable budget. Three 40 kW racks require 167 A at the end feed. A fourth raises it to 223 A, although each rack branch still carries about 56 A. A fifth would need about 278 A. Spare physical tap positions do not add current capacity.',{controls:[{key:'rowCount',label:'Connected racks',options:[[3,'Three × 40 kW'],[4,'Four × 40 kW'],[5,'Five × 40 kW']]}]}),
  scene('power-factor','Lower power factor uses more of the transformer’s current capacity','comparison','D04.2','current-and-rating','Keep real AC input at 900 kW and line-to-line voltage at 480 V in a balanced three-phase teaching example. At PF 1 the load needs 900 kVA; at PF 0.8 it needs 1,125 kVA. The supplied 1,000 kVA transformer limit is a current-and-voltage rating, not an energy-loss allowance. Apparent power S = P / PF; line current I = S / (√3 V). No converter efficiency is changed or assumed by this comparison.',{controls:[{key:'powerFactor',label:'Input power factor',options:[[1,'1.00'],[.9,'0.90'],[.8,'0.80']]}]}),
  scene('phase-loading','A three-phase rack PDU feeds single-phase PSU groups','counterexample','D04.2','current-and-rating','Three equal phase voltages do not force equal currents. In this 277 V phase-to-neutral example, six single-phase PSU groups each draw 20 A. A 2/2/2 assignment draws 40 A per phase; a 4/1/1 assignment draws 80/20/20 A. The 60 A teaching limit is exceeded on L1 even though total useful load is unchanged. The neutral carries the instantaneous sum returning from the three branches; sinusoidal currents cancel only when balanced. Real nonlinear PSU currents add harmonic considerations. This is a conceptual load allocation, not instructions for moving live connections.',{controls:[{key:'balanced',label:'Allocate six PSU groups',options:[[true,'Spread across phases'],[false,'Crowded onto L1']]}]}),
  scene('feeder-diagnosis','A failed feeder breaker can force both halls offline','transfer','D04.4','read-the-power-train','Hall A has a feeder fault. Its relay has issued a trip, but its breaker remains closed and fault current continues. Hall B has no local fault and shares the incoming bus. Before opening the backup breaker, predict which hall connections it will remove. Upstream backup protection isolates the persistent fault by opening the shared incoming breaker, also disconnecting Hall B. This demonstrates how one failed interruption expands the outage boundary.',{controls:[{key:'diagnosisStage',label:'Breaker failure',options:[['fault','Feeder trip fails'],['backup','Upstream backup opens']]}]}),
  scene('distribution-handoff','Next: keep racks and cooling running through an interruption','transfer','D04.1','read-the-power-train','The normal-load account establishes voltage interfaces, connected loads and usable limits. The next chapter changes the operating state: which paths keep IT and the supporting pumps powered when supply or equipment is unavailable? Preserve the same boundaries when adding storage and alternate paths.'),
];
