import {fabricBudget,messageTime,ringTime,propagation,ringChunkState} from './networking-model.js';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const n=(v,d=0)=>v.toLocaleString('en-US',{maximumFractionDigits:d});
const T=(x,y,s,size=23,color='ink',anchor='middle')=>`<text x="${x}" y="${y}" font-size="${size}" fill="var(--${color})" text-anchor="${anchor}">${s}</text>`;
const R=(x,y,w,h,fill='surface',stroke='line')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="var(--${fill})" stroke="var(--${stroke})" stroke-width="2"/>`;
const L=(d,color='teal',dashed=false,arrow=true)=>`<path d="${d}" stroke="var(--${color})" stroke-width="4" fill="none" ${dashed?'stroke-dasharray="8 7"':''} ${arrow?'marker-end="url(#net-arrow-'+color+')"':''}/>`;
const svg=(body,label,w=1100,h=470)=>`<svg class="network-diagram" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg"><defs>${['teal','amber','phase-three','muted','ink'].map(c=>`<marker id="net-arrow-${c}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="var(--${c})"/></marker>`).join('')}</defs>${body}</svg>`;
const credit=(label,url)=>`<figcaption class="figure-credit"><a href="${url}" target="_blank" rel="noopener">${label}</a></figcaption>`;
const node=(name,detail='',kind='')=>`<div class="path-node ${kind}"><b>${name}</b>${detail?`<span>${detail}</span>`:''}</div>`;
const stepArrow='<span class="path-arrow" aria-hidden="true">→</span>';
const fact=(value,label)=>`<div class="network-fact"><strong>${value}</strong><span>${label}</span></div>`;
const generated=()=>`<figure class="network-hero"><img src="../assets/generated/compute-scales.png" alt="An AI rack, an extracted compute tray and an accelerator package shown at three physical scales."><figcaption class="compute-scale-labels"><span>Rack</span><span>Compute tray</span><span>GPU + memory</span></figcaption></figure>`;
const hardwareMeme=()=>`<figure class="network-meme"><img src="../assets/references/compute-consumer-hardware-meme.png" alt="Grim Reaper meme: AI Data Centers passes doors labeled Low MSRPs, Mid range Availability and Consumer VRAM, and knocks on PC Gaming as a Hobby."></figure>`;
function scales(){return `<div class="scopes-grid"><section><h2>Scale-up</h2><div class="nvlink-domain"><div class="mini-gpus"><span>GPU</span><span>GPU</span><span>GPU</span></div><div class="nvlink-drops"><i></i><i></i><i></i></div><div class="nvlink-plane">NVLink switches</div></div><b>Within a tightly coupled domain</b><span>GB300 NVL72 · 72 GPUs</span></section><section><h2>Scale-out</h2><div class="rack-pair"><div class="rack-icon">${'<i></i>'.repeat(5)}</div><span>↔</span><div class="rack-icon">${'<i></i>'.repeat(5)}</div></div><b>Across the AI cluster</b><span>Adapters + fabric switches</span></section><section><h2>Between facilities</h2><div class="site-pair"><i>DC</i><span>↔</span><i>DC</i></div><b>Across a campus or a region</b><span>Border network + fiber service</span></section></div>`;}
function packet(state){
 const selected=state.transfer||'local',stem='<div class="route-stem" aria-hidden="true">↓</div>';
 const local=`<div class="local-gpu-boundary"><span class="object-location">One GPU package</span>${node('HBM','GPU memory')}${stem}${node('GPU compute','Read weights and data')}</div>`;
 const peer=`${node('GPU','Sends a result')}${stem}${node('NVLink switches')}${stem}${node('Peer GPU','Receives the result')}`;
 const cluster=`<div class="route-tray"><span class="object-location">Compute tray</span>${node('GPU')}${stepArrow}${node('Adapter')}</div>${stem}${node('Fabric switches','Optical links between racks')}${stem}<div class="route-tray"><span class="object-location">Peer compute tray</span>${node('Adapter')}${stepArrow}${node('GPU')}</div>`;
 return `<div class="complete-routes local-and-network-routes">${[['local','GPU-local memory',local],['rack','Inside the rack',peer],['cluster','Across racks',cluster]].map(([key,label,body])=>`<section class="${selected===key?'selected-path':'muted-path'}" aria-label="${label}${selected===key?' — selected':''}"><h2>${label}</h2>${body}</section>`).join('')}</div>`;
}
function sharedModel(){return `<div class="shared-model"><div class="model-gpus">${[['1','A'],['2','B']].map(([gpu,part])=>`<section><h2>GPU ${gpu}</h2><div class="model-weight part-${part.toLowerCase()}">Part ${part} of one layer</div><span class="local-compute-arrow">↓</span><div class="partial-result">Compute a partial result</div></section>`).join('')}</div><div class="model-exchange"><span aria-hidden="true">↘</span><div><strong>Exchange through NVLink switches</strong><span>Each GPU receives the other part’s result</span></div><span aria-hidden="true">↙</span></div><div class="model-combine">GPUs combine the results, then continue.</div></div>`;}

function hardware(){return `<div class="hardware-layout"><figure class="nic-photo"><img src="../assets/references/networking-connectx7.jpg" alt="NVIDIA ConnectX-7 single-port network adapter manufacturer product rendering.">${credit('NVIDIA · ConnectX-7','https://www.nvidia.com/en-us/networking/infiniband-adapters/')}</figure><div class="nic-facts"><h2>400G adapter example · ConnectX-7</h2>${fact('400 Gb/s','Single-port example · MCX75310AAS-NEAT')}<div class="hardware-detail"><span>PCIe 5.0 ×16</span><span>68.9 × 167.65 mm</span></div></div><figure class="switch-photo"><h2>Quantum-2 QM9700</h2><img src="../assets/references/networking-qm9700-front.png" alt="QM9700 front panel showing the 32 twin-port OSFP cages."><div class="switch-callouts"><span><b>32</b> physical cages</span><span><b>64 × 400 Gb/s</b> logical ports</span><span><b>1U</b> rack height</span></div>${credit('NVIDIA · QM9700 hardware manual','https://networking-docs.nvidia.com/qm97x0hw/introduction')}</figure></div>`;}
function media(){return `<div class="media-comparison"><section><h2>Copper</h2><div class="link-drawing copper"><span>Port</span><i></i><span>Port</span></div><p>Electrical signal along the cable</p><div class="reach-example"><strong>2 m</strong><span>Passive copper cable</span></div></section><section><h2>Optical fiber</h2><div class="link-drawing optical"><span>E ↔ O</span><i></i><span>O ↔ E</span></div><p>Electrical ↔ optical conversion at each end</p><div class="reach-pair"><div class="reach-example"><strong>30 m</strong><span>Multimode optics</span></div><div class="reach-example"><strong>500 m</strong><span>Single-mode DR4 optics</span></div></div></section></div><p class="single-condition">400G LinkX product examples · E: electrical · O: optical</p>`;}
function packaging(){return `<div class="package-comparison"><section><h2>Pluggable optics</h2><div class="switch-board"><span class="board-label">Switch board</span><div class="chip">Switch<br>silicon</div><div class="electrical-traces">${'<i></i>'.repeat(5)}</div><div class="optical-engine">Optics</div><div class="fiber-stub"></div></div><div class="package-point"><b>Front-panel module</b><span>Replace the optical module at the port.</span></div></section><section><h2>Co-packaged optics</h2><div class="switch-board"><span class="board-label">Switch board</span><div class="cpo-package"><div class="chip">Switch<br>silicon</div><div class="optical-engine">Optics</div></div><div class="fiber-stub long"></div></div><div class="package-point"><b>Optical engine beside the switch silicon</b><span>Repair boundary depends on the product.</span></div></section></div>`;}
function fabric(compact,placement=null){
 const w=compact?540:1100,h=compact?620:530,xs=compact?[65,200,335,470]:[130,410,690,970],sy=compact?60:65,ly=compact?270:245,hy=compact?450:385,spines=compact?[150,390]:[365,735];
 let b=T(w/2,compact?22:25,'Spine switches',compact?19:23);for(const [j,x]of spines.entries())b+=R(x-55,sy,110,48)+T(x,sy+30,`Spine ${j+1}`,18);
 for(const [i,x]of xs.entries()){for(const [j,sx]of spines.entries()){const active=placement==='remote'&&(i===0||i===3);b+=L(`M${x} ${ly}L${sx} ${sy+48}`,active?'amber':'muted',false,false);}b+=R(x-52,ly,104,50,placement==='local'&&i===0?'positive-surface':'surface')+T(x,ly+31,`Leaf ${i+1}`,19);for(let k=0;k<4;k++){const ex=x+(k-1.5)*(compact?24:32);b+=L(`M${ex} ${ly+50}V${hy}`,'teal',false,false);b+=R(ex-9,hy,18,36,'surface-soft','teal');}b+=T(x,hy+64,'4 servers',compact?16:20);}
 if(placement==='remote')b+=T(w/2,h-15,'Collective traffic crosses the spine tier',compact?20:25,'amber');else if(placement==='local')b+=T(w/2,h-15,'This exchange stays at Leaf 1',compact?20:25,'teal');else b+=T(w/2,h-15,'16 server links + 8 uplinks = 24 cables',compact?20:25);
 return svg(b,'Four leaf switches each attach four servers and connect to both spine switches. Each line represents one cable.',w,h);
}
function cut(state){const b=fabricBudget({uplinksPerLeaf:state.uplinks});return `<div class="cut-layout"><div class="cut-input"><h2>Sending leaf</h2><div class="endpoint-row">${Array.from({length:4},()=>'<span>400</span>').join('')}</div><strong>1,600 Gb/s</strong><span>From four server ports</span></div><div class="cut-neck"><span class="cut-line">Cross-leaf cut</span><div class="cut-links">${Array.from({length:state.uplinks},()=>'<i><span>400 Gb/s</span></i>').join('')}</div><strong>${n(b.upGbps)} Gb/s</strong></div><div class="cut-output"><h2>Receiving leaf</h2><div class="endpoint-row">${Array.from({length:4},()=>'<span>400</span>').join('')}</div><strong>${b.oversubscription}:1</strong><span>Downlink-to-uplink ratio</span></div></div><div class="bound-equation"><span>32 GB crossing the cut</span><strong>32 GB ÷ ${n(b.upGbps/8)} GB/s = ${n(b.transferSeconds,2)} s</strong><span>Lower bound · balanced traffic · one direction</span></div>`;}
function message(){const small=messageTime({bytes:1000}),large=messageTime({bytes:1e9});return `<div class="message-comparison"><div class="message-inputs"><span>400 Gb/s = 50 GB/s</span><span>5 µs fixed latency</span></div><table><thead><tr><th>Message</th><th>Put bytes on the link</th><th>Fixed latency + transfer</th></tr></thead><tbody><tr><th>1 KB</th><td>0.02 µs</td><td><b>${small.totalUs} µs</b></td></tr><tr><th>1 GB</th><td>20 ms</td><td><b>${n(large.totalUs/1000,3)} ms</b></td></tr></tbody></table><div class="equation">Time = fixed latency + bytes ÷ payload rate</div></div>`;}
function incast(compact){const w=compact?520:1100,h=compact?570:440;const sx=compact?50:110,qx=compact?245:500,rx=compact?420:945,ys=compact?[100,195,290,385]:[65,160,255,350];let b=T(qx+20,35,'Switch output queue',compact?20:24);for(let i=0;i<4;i++)b+=R(sx-37,ys[i]-24,74,48)+T(sx,ys[i]+7,`GPU ${i+1}`,17)+L(`M${sx+38} ${ys[i]}L${qx-20} 225`,'amber');b+=R(qx-20,175,135,100,'surface-soft')+Array.from({length:5},(_,i)=>R(qx-9+i*22,200,15,42,i<3?'amber':'surface','line')).join('')+L(`M${qx+115} 225H${rx-45}`,'teal')+R(rx-45,190,90,70)+T(rx,220,'One',18)+T(rx,244,'receiver',18)+T(qx+75,310,'400 Gb/s out',compact?19:24,'teal')+T(w/2,h-18,'1,600 Gb/s offered → packets wait before one output port',compact?17:24);return svg(b,'Four senders offer more traffic than one 400 gigabit receiver link can drain, creating a queue.',w,h);}
const worker=(i,chunks)=>`<section class="rank"><h2>Worker ${i+1}</h2><div class="gradient-buffer">${chunks.map((c,j)=>`<i class="chunk chunk-${j} ${c}" aria-label="Chunk ${j+1} ${c}">${c==='absent'?'':String.fromCharCode(65+j)+(c==='partial'?['₁','₂','₃','₄'][i]:'')}</i>`).join('')}</div></section>`;
function allreduce(){return `<div class="gradient-story"><div class="gradient-workers">${Array.from({length:4},(_,i)=>worker(i,['partial','partial','partial','partial'])).join('')}</div><div class="collective-label"><span>Each worker computed gradients from its part of the batch.</span><b>All-reduce</b><span>A = A₁ + A₂ + A₃ + A₄ · likewise for B, C and D</span></div><div class="gradient-workers result-workers">${Array.from({length:4},(_,i)=>worker(i,['complete','complete','complete','complete'])).join('')}</div></div>`;}
function ring(state){const round=state.ringRound,rows=ringChunkState(round),label=round===0?'Each worker starts with its own gradient.':round===3?'Reduce-scatter · each worker now owns one combined chunk.':'All-gather · every worker has all four combined chunks.';return `<div class="ring-visual"><div class="ring-workers">${rows.map((chunks,i)=>worker(i,chunks.map(c=>c.kind))).join('')}</div><div class="ring-line"><span>Worker 1 → 2 → 3 → 4 → 1</span></div><p class="ring-phase">${label}</p><div class="ring-count"><div><strong>3 rounds</strong><span>Reduce-scatter</span></div><span>+</span><div><strong>3 rounds</strong><span>All-gather</span></div><span>=</span><div><strong>6 rounds</strong><span>Total</span></div></div><p class="single-condition">1 GB ÷ 4 chunks × 6 rounds = 1.5 GB sent per worker</p></div>`;}
function criticalPath(state){const b=ringTime({bandwidthGBps:state.collectiveRate});const bar=(overlap)=>{const width=270,scale=100/width,start=overlap?180:200,total=overlap?b.overlappedStepMs:b.sequentialStepMs;return `<div class="timeline-stack"><div class="timeline-row"><span>Compute</span><div><i style="left:0;width:${200*scale}%" class="compute-bar">200 ms</i></div></div><div class="timeline-row"><span>Collective</span><div><i style="left:${start*scale}%;width:${b.communicationMs*scale}%" class="comm-bar">${b.communicationMs}</i></div></div><div class="timeline-end" style="--end:${total/width}"><b>${total} ms</b><span>Step finished</span></div></div>`;};return `<div class="timeline-inputs"><span>Four workers · 1 GB gradients each</span><span>1.5 GB ÷ ${state.collectiveRate} GB/s = ${b.communicationMs} ms communication</span></div><div class="critical-pair"><section><h2>Exchange after compute</h2>${bar(false)}</section><section><h2>20 ms can overlap independent compute</h2>${bar(true)}</section></div>`;}
function fabrics(){return `<div class="fabric-choice"><section><h2>Ethernet + RoCE</h2><strong>24,576 H100 GPUs</strong><div class="fabric-core">Ethernet adapter ⇄ Ethernet switch</div><p>RoCE carries remote memory transfers over Ethernet.</p></section><section><h2>InfiniBand</h2><strong>24,576 H100 GPUs</strong><div class="fabric-core">InfiniBand adapter ⇄ InfiniBand switch</div><p>Dedicated end-to-end network architecture.</p></section></div><div class="co-design"><span>Routing</span><span>Congestion control</span><span>Collective software</span><span>Job placement</span></div>${credit('Meta Engineering · March 2024','https://engineering.fb.com/2024/03/12/data-center-engineering/building-metas-genai-infrastructure/')}`;}
function tpu(){return `<div class="tpu-architecture"><div class="tpu-block"><h2>One TPU v4 rack</h2><div class="tpu-chips">${'<i></i>'.repeat(64)}</div><b>4 × 4 × 4 = 64 chips</b><span>Electrical inter-chip links</span></div><div class="tpu-connection"><b>ICI</b><span>Inter-chip interconnect</span><div>⇄</div><b>48 optical circuit switches</b></div><div class="tpu-pod"><h2>64 racks</h2><div class="tpu-racks">${'<i></i>'.repeat(64)}</div><strong>4,096 TPU v4 chips</strong><span>Reconfigure connections between rack blocks.</span></div></div>${credit('Google · TPU v4 architecture, ISCA 2023','https://arxiv.org/abs/2304.01433')}`;}
function ocs(state,compact){const cross=state.ocsPairing==='crossed';const w=compact?520:1100,h=compact?470:410;const x1=compact?60:120,x2=compact?460:980,y1=130,y2=300,mid=w/2;let b=R(mid-100,65,200,290,'surface-soft')+T(mid,105,'Optical circuit switch',compact?18:22);for(const [x,name,y]of[[x1,'A',y1],[x1,'B',y2],[x2,'C',y1],[x2,'D',y2]])b+=R(x-30,y-25,60,50)+T(x,y+8,name,25);b+=L(`M${x1+30} ${y1}H${mid-65}L${mid+65} ${cross?y2:y1}H${x2-30}`,'teal',false,false)+L(`M${x1+30} ${y2}H${mid-65}L${mid+65} ${cross?y1:y2}H${x2-30}`,'amber',false,false)+T(mid,385,'Mirrors set the light paths.',compact?22:25);return `<div class="ocs-layout">${svg(b,'Two simultaneous optical circuits are reconfigured from A to C and B to D into A to D and B to C.',w,h)}<figure class="ocs-source"><img src="../assets/references/networking-google-ocs.jpg" alt="Google optical circuit switch diagram showing MEMS mirrors connecting optical fiber paths.">${credit('Google · optical paths through MEMS mirrors','https://cloud.google.com/blog/topics/systems/tpu-v4-enables-performance-energy-and-co2e-efficiency-gains')}</figure></div>`;}
function campus(){return `<div class="campus-path"><section><h2>Inside the facility</h2><div class="vertical-path">${node('AI cluster','Internal fabric')}${stepArrow}${node('Border router','Traffic to external networks')}${stepArrow}${node('Patch panel','Agreed service handoff')}</div></section><section><h2>Physical connection</h2><div class="vertical-path">${node('Meet-me room','Carrier and customer fiber connect')}${stepArrow}${node('Entrance + outside fiber','Ducts, splice points, route')}${stepArrow}${node('Carrier service','Private connection or Internet transit')}</div></section></div><p class="single-condition">The patch cable is a connection; the carrier contract defines the service.</p>`;}
function distance(){const p=propagation(100);return `<div class="distance-story"><div class="wide-fiber"><div class="site-icon">Facility A</div><div class="route-distance"><b>100 km fiber route</b><i></i><span>200,000 km/s propagation speed</span></div><div class="site-icon">Facility B</div></div><div class="distance-metrics">${fact(`${p.oneWayMs} ms`,'One-way propagation')}${fact(`${p.roundTripMs} ms`,'Round-trip propagation')}</div><div class="wan-distinction"><section><h2>Bulk data transfer</h2><p>Keep many bytes in flight.</p></section><section><h2>Dependent exchanges</h2><p>Each required reply adds another round trip.</p></section></div><p class="single-condition">Google Multislice uses ICI within a slice and the data-center network between slices.</p></div>`;}
function failure(){return `<div class="failure-comparison"><section><h2>Healthy fabric</h2><div class="rank-times">${[1,2,3,4].map(i=>`<div><span>Worker ${i}</span><i style="width:60%"></i></div>`).join('')}</div><b>Collective finishes together</b></section><section><h2>One link repeatedly retries</h2><div class="rank-times delayed">${[1,2,3,4].map(i=>`<div><span>Worker ${i}</span><i style="width:${i===4?90:60}%" class="${i===4?'slow':''}"></i>${i!==4?'<em>Wait</em>':''}</div>`).join('')}</div><b>The next update waits for Worker 4</b></section></div><div class="fault-location"><span>GPU</span>→<span>Adapter</span>→<strong>Marginal cable / connector</strong>→<span>Switch</span></div>`;}
function diagnosis(state){const answers={replace:'Use port errors and rank timing to locate and replace the marginal link. Retest the collective at the expected payload rate.',uplinks:'More upstream ports do not repair the marginal source link. The retry spike follows that physical connection.',gpus:'Additional GPUs do not restore the missing transfer. The next update still depends on the delayed participant.'};return `<div class="diagnosis-grid"><div class="diagnosis-measurements"><h2>After a cable move</h2><dl><dt>Compute phase</dt><dd>Unchanged</dd><dt>Collective</dt><dd>One worker arrives late</dd><dt>Its switch port</dt><dd>Link up · retries rising</dd><dt>Other uplinks</dt><dd>Spare capacity</dd></dl></div><div class="diagnosis-options"><h2>What should be checked first?</h2>${[['replace','Trace that worker’s adapter, cable and port'],['uplinks','Add more spine uplinks'],['gpus','Add GPUs to the job']].map(([id,label])=>`<button data-diagnosis="${id}" aria-pressed="${state.diagnosis===id}">${label}</button>`).join('')}</div></div><div class="diagnosis-response" aria-live="polite">${state.showDiagnosis&&state.diagnosis?`<p>${answers[state.diagnosis]}</p>`:''}</div><button id="diagnosis-reveal" ${!state.diagnosis?'disabled':''} aria-expanded="${state.showDiagnosis}">${state.showDiagnosis?'Hide explanation':'Explain the diagnosis'}</button>`;}
function storage(){return `<div class="storage-traffic"><div class="storage-system"><h2>Storage system</h2><div class="disk-stack">${'<i></i>'.repeat(5)}</div></div><div class="traffic-directions"><div><b>Dataset reads →</b><span>Feed the next compute step</span></div><div><b>← Checkpoints</b><span>Preserve progress for recovery</span></div></div><div class="storage-compute"><h2>AI cluster</h2><div class="rack-pair"><div class="rack-icon">${'<i></i>'.repeat(6)}</div><div class="rack-icon">${'<i></i>'.repeat(6)}</div></div></div></div>`;}
export function networkingVisual(id,state,compact=false){switch(id){case'networking-purpose':return generated();case'consumer-hardware-meme':return hardwareMeme();case'three-scales':return scales();case'packet-path':return packet(state);case'shared-model':return sharedModel();case'network-hardware':return hardware();case'copper-and-light':return media();case'optical-packaging':return packaging();case'leaf-spine':return fabric(compact);case'shared-uplinks':return cut(state);case'traffic-placement':return fabric(compact,state.placement);case'message-time':return message();case'incast':return incast(compact);case'all-reduce':return allreduce();case'ring-collective':return ring(state);case'collective-time':return criticalPath(state);case'ethernet-infiniband':return fabrics();case'tpu-interconnect':return tpu();case'optical-circuits':return ocs(state,compact);case'campus-fiber':return campus();case'distance-latency':return distance();case'fabric-failure':return failure();case'network-diagnosis':return diagnosis(state);case'storage-handoff':return storage();default:throw new Error(`No networking visual for ${id}`);}}
