import {fabricBudget,propagation} from './networking-model.js';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const n=(v,d=0)=>v.toLocaleString('en-US',{maximumFractionDigits:d});
const T=(x,y,s,size=23,color='ink',anchor='middle')=>`<text x="${x}" y="${y}" font-size="${size}" fill="var(--${color})" text-anchor="${anchor}">${s}</text>`;
const R=(x,y,w,h,fill='surface',stroke='line')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="var(--${fill})" stroke="var(--${stroke})" stroke-width="2"/>`;
const L=(d,color='teal',dashed=false,arrow=true)=>`<path d="${d}" stroke="var(--${color})" stroke-width="4" fill="none" ${dashed?'stroke-dasharray="8 7"':''} ${arrow?'marker-end="url(#net-arrow-'+color+')"':''}/>`;
const svg=(body,label,w=1100,h=470)=>`<svg class="network-diagram" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg"><defs>${['teal','amber','phase-three','muted','ink'].map(c=>`<marker id="net-arrow-${c}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="var(--${c})"/></marker>`).join('')}</defs>${body}</svg>`;
const credit=(label,url)=>`<figcaption class="figure-credit"><a href="${url}" target="_blank" rel="noopener">${label}</a></figcaption>`;
const node=(name,detail='',kind='')=>`<div class="path-node ${kind}"><b>${name}</b>${detail?`<span>${detail}</span>`:''}</div>`;
const stepArrow='<span class="path-arrow" aria-hidden="true">→</span>';
const fact=(value,label)=>`<div class="network-fact"><strong>${value}</strong><span>${label}</span></div>`;
const generated=()=>`<figure class="network-hero"><img src="../assets/generated/compute-scales.png" alt="An AI rack, an extracted compute tray and an accelerator package shown at three physical scales."><figcaption class="compute-scale-labels"><span>Rack</span><span>Compute tray</span><span>GPU + memory</span></figcaption></figure>`;
const hardwareMeme=()=>`<figure class="network-meme"><img src="../assets/references/storage-hardware-prices-meme.png" alt="Grim Reaper AI meme: RAM, GPU and SSD prices rise, with CPU prices next."></figure>`;
function superfactory(state,compact){
 const asset='../assets/references/networking-microsoft-ai-superfactory.png';
 if(!state.superfactoryView||state.superfactoryView==='overview')return `<figure class="network-reference-image"><img src="${asset}" alt="Microsoft: Inside an AI Superfactory. Fairwater connects Wisconsin and Georgia through an AI WAN. The infographic shows its high-speed backbone, power infrastructure, GPU density, liquid cooling, short cables and network topology."></figure>`;
 const campus=state.superfactoryView==='campus',y=campus?290:1120,h=campus?355:390;
 const labels=campus?['High-speed AI backbone','Powering the impossible','Unmatched GPU density']:['Liquid cooling innovation','Architected for speed','Intelligent network topology'];
 const view=(x,w,label)=>`<svg viewBox="${x} ${y} ${w} ${h}" role="img" aria-label="Microsoft AI Superfactory: ${esc(label)}"><defs><clipPath id="superfactory-${x}-${y}"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath></defs><image href="${asset}" width="1536" height="1536" clip-path="url(#superfactory-${x}-${y})"/></svg>`;
 return `<figure class="superfactory-details"><div class="superfactory-crops">${compact?[75,545,1015].map((x,i)=>view(x,445,labels[i])).join(''):view(75,1385,labels.join('; '))}</div>${credit('Microsoft · Inside an AI Superfactory','https://news.microsoft.com/source/features/ai/from-wisconsin-to-atlanta-microsoft-connects-datacenters-to-build-its-first-ai-superfactory/')}</figure>`;
}
const leafSpineOverview=()=>`<figure class="network-reference-image"><img src="../assets/references/networking-leaf-spine-overview.png" alt="Two spine switches each connect to all three leaf switches; each leaf serves four servers. Traffic between different leaves crosses a spine. Other topology examples include torus, dragonfly and custom fabrics."></figure>`;
function scales(){return `<div class="scopes-grid"><section><h2>Scale-up</h2><div class="nvlink-domain"><div class="mini-gpus"><span>GPU</span><span>GPU</span><span>GPU</span></div><div class="nvlink-drops"><i></i><i></i><i></i></div><div class="nvlink-plane">NVLink switches</div></div><b>Within a tightly coupled domain</b><span>Kimi K3 inference on GB200 NVL72<br>InferenceX · August 2026</span></section><section><h2>Scale-out</h2><div class="rack-pair"><div class="rack-icon">${'<i></i>'.repeat(5)}</div><span>↔</span><div class="rack-icon">${'<i></i>'.repeat(5)}</div></div><b>Across the AI cluster</b><span>Llama 3.1 405B training on 16,000+ H100s<br>Meta · 2024</span></section><section><h2>Between facilities</h2><div class="site-pair"><i>DC</i><span>↔</span><i>DC</i></div><b>Across campuses and regions</b><span>Fairwater: Atlanta ↔ Wisconsin<br>Microsoft · 2025</span></section></div>`;}
function packet(){
 const stem='<div class="route-stem" aria-hidden="true">↓</div>';
 const local=`<div class="local-gpu-boundary">${node('HBM','GPU memory')}${stem}${node('GPU compute','Read weights and data')}</div>`;
 const peer=`${node('GPU','Sends a result')}${stem}${node('NVLink switches')}${stem}${node('Peer GPU','Receives the result')}`;
 const cluster=`<div class="route-tray">${node('GPU')}${stepArrow}${node('Adapter')}</div>${stem}${node('Fabric switches','Optical links between racks')}${stem}<div class="route-tray">${node('Adapter')}${stepArrow}${node('GPU')}</div>`;
 return `<div class="complete-routes local-and-network-routes">${[['local','GPU-local memory',local],['rack','Inside the rack',peer],['cluster','Across racks',cluster]].map(([key,label,body])=>`<section aria-label="${label}"><h2>${label}</h2>${body}</section>`).join('')}</div>`;
}
function sharedModel(){return `<div class="shared-model"><div class="model-gpus">${[['1','A'],['2','B']].map(([gpu,part])=>`<section><h2>GPU ${gpu}</h2><div class="model-weight part-${part.toLowerCase()}">Part ${part} of one layer</div><span class="local-compute-arrow">↓</span><div class="partial-result">Compute a partial result</div></section>`).join('')}</div><div class="model-exchange"><span aria-hidden="true">↘</span><div><strong>GPUs combine the results through NVLink switches.</strong></div><span aria-hidden="true">↙</span></div><div class="model-combine">Hardware–software co-design</div></div>`;}

function hardware(){return `<div class="hardware-layout"><figure class="nic-photo"><img src="../assets/references/networking-connectx7.jpg" alt="NVIDIA ConnectX-7 single-port network adapter manufacturer product rendering.">${credit('NVIDIA · ConnectX-7','https://www.nvidia.com/en-us/networking/infiniband-adapters/')}</figure><div class="nic-facts"><h2>ConnectX-7 adapter</h2>${fact('400 Gb/s','Network port')}<div class="hardware-detail"><span>PCIe 5.0 ×16</span></div></div><figure class="switch-photo"><h2>Quantum-2 QM9700</h2><img src="../assets/references/networking-qm9700-front.png" alt="QM9700 front panel showing the 32 twin-port OSFP cages."><div class="switch-callouts"><span><b>32</b> physical cages</span><span><b>64 × 400 Gb/s</b> logical ports</span></div>${credit('NVIDIA · QM9700 hardware manual','https://networking-docs.nvidia.com/qm97x0hw/introduction')}</figure></div>`;}
function media(){return `<div class="media-comparison"><section><h2>Copper</h2><div class="link-drawing copper"><span>Port</span><i></i><span>Port</span></div><p>The electrical signal weakens and distorts with distance.</p><div class="reach-example"><strong>2 m</strong><span>Passive copper cable</span></div></section><section><h2>Optical fiber</h2><div class="link-drawing optical"><span>E ↔ O</span><i></i><span>O ↔ E</span></div><p>Lower signal loss makes longer links practical.</p><div class="reach-pair"><div class="reach-example"><strong>50 m</strong><span>Multimode optics</span></div><div class="reach-example"><strong>500 m</strong><span>Single-mode DR4 optics</span></div></div></section></div><p class="single-condition">400G LinkX cable and transceiver examples</p>`;}
function packaging(){return `<figure class="optical-packaging-image"><img src="../assets/references/networking-pluggable-vs-cpo.png" alt="Pluggable optics versus co-packaged optics. Pluggable optics sits at the switch front panel with a longer electrical path; co-packaged optical engines sit on the switch package with a shorter electrical path to the switch silicon."></figure>`;}
function fabric(compact,placement=null){
 const w=compact?540:1100,h=compact?620:530,xs=compact?[65,200,335,470]:[130,410,690,970],sy=compact?60:65,ly=compact?270:245,hy=compact?450:385,spines=compact?[150,390]:[365,735];
 let b=T(w/2,compact?22:25,'Spine switches',compact?19:23);for(const [j,x]of spines.entries())b+=R(x-55,sy,110,48)+T(x,sy+30,`Spine ${j+1}`,18);
 for(const [i,x]of xs.entries()){for(const [j,sx]of spines.entries()){const active=placement==='remote'&&(i===0||i===3);b+=L(`M${x} ${ly}L${sx} ${sy+48}`,active?'amber':'muted',false,false);}b+=R(x-52,ly,104,50,placement==='local'&&i===0?'positive-surface':'surface')+T(x,ly+31,`Leaf ${i+1}`,19);for(let k=0;k<4;k++){const ex=x+(k-1.5)*(compact?24:32);b+=L(`M${ex} ${ly+50}V${hy}`,'teal',false,false);b+=R(ex-9,hy,18,36,'surface-soft','teal');}b+=T(x,hy+64,'4 servers',compact?16:20);}
 if(placement==='remote')b+=T(w/2,h-15,'Collective traffic crosses the spine tier',compact?20:25,'amber');else if(placement==='local')b+=T(w/2,h-15,'This exchange stays at Leaf 1',compact?20:25,'teal');else b+=T(w/2,h-15,'16 server links + 8 uplinks = 24 cables',compact?20:25);
 return svg(b,'Four leaf switches each attach four servers and connect to both spine switches. Each line represents one cable.',w,h);
}
function physicalFabric(compact){
 const w=compact?540:1100,h=compact?460:550;
 const left=compact?132:270,right=compact?408:830,mid=w/2;
 const switchW=compact?252:510,switchH=switchW/10;
 const sy=compact?56:42,ly=190,dy=compact?310:305;
 const serverW=compact?252:455,serverH=serverW*194/384;
 const picture=(file,x,y,width,height)=>`<image href="../assets/references/${file}" x="${x-width/2}" y="${y}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid meet"/>`;
 let body=L(`M${left} ${ly}L${mid} ${sy+switchH}`,'teal',false,false)+L(`M${right} ${ly}L${mid} ${sy+switchH}`,'teal',false,false);
 body+=L(`M${left} ${dy-43}V${ly+switchH}`,'teal',false,false)+L(`M${right} ${dy-43}V${ly+switchH}`,'teal',false,false);
 body+=T(mid,sy-15,'Spine · QM9700',compact?28:32)+picture('networking-qm9700-front.png',mid,sy,switchW,switchH);
 for(const x of[left,right]){
  body+=`<rect x="${x-switchW/2-5}" y="${ly-45}" width="${switchW+10}" height="${switchH+45}" rx="8" fill="var(--paper)"/>`+T(x,ly-15,'Leaf · QM9700',compact?25:30)+picture('networking-qm9700-front.png',x,ly,switchW,switchH);
  body+=`<rect x="${x-serverW/2}" y="${dy-43}" width="${serverW}" height="42" fill="var(--paper)"/>`+T(x,dy-12,'DGX H100',compact?28:32)+picture('networking-dgx-h100.png',x,dy,serverW,serverH);
 }
 return `<figure class="physical-fabric">${svg(body,'One path between DGX H100 systems through leaf and spine QM9700 switches in the NVIDIA DGX H100 SuperPOD reference architecture. Product images identify the physical equipment; the full fabric has multiple paths.',w,h)}${credit('NVIDIA · DGX H100 SuperPOD reference architecture','https://docs.nvidia.com/dgx-superpod/reference-architecture-scalable-infrastructure-h100/latest/network-fabrics.html')}</figure>`;
}
function cut(state){const b=fabricBudget({uplinksPerLeaf:state.uplinks});return `<div class="cut-layout"><div class="cut-input"><h2>Sending leaf</h2><div class="endpoint-row">${Array.from({length:4},()=>'<span>400</span>').join('')}</div><strong>1,600 Gb/s</strong><span>From four server ports</span></div><div class="cut-neck"><span class="cut-line">Cross-leaf cut</span><div class="cut-links">${Array.from({length:state.uplinks},()=>'<i><span>400 Gb/s</span></i>').join('')}</div><strong>${n(b.upGbps)} Gb/s</strong></div><div class="cut-output"><h2>Receiving leaf</h2><div class="endpoint-row">${Array.from({length:4},()=>'<span>400</span>').join('')}</div><strong>${b.oversubscription}:1</strong><span>Downlink-to-uplink ratio</span></div></div><div class="bound-equation"><span>256 Gb crossing the cut</span><strong>256 Gb ÷ ${n(b.upGbps)} Gb/s = ${n(b.transferSeconds,2)} s</strong><span>Minimum transfer time · balanced traffic · one direction</span></div>`;}

function incast(){return `<div class="incast-path incast-simple"><div class="incast-senders">${[1,2,3,4].map(i=>`<div><b>Sender ${i}</b><span aria-hidden="true">→</span></div>`).join('')}</div><section class="incast-queue"><h2>Queue builds</h2><div class="incast-packets" aria-hidden="true">${'<i></i>'.repeat(5)}</div></section><div class="incast-receiver"><span class="incast-output" aria-hidden="true">→</span><div class="incast-destination"><div class="rack-icon" aria-hidden="true">${'<i></i>'.repeat(5)}</div><b>One receiver</b></div></div></div><p class="incast-payoff">Multiple senders overwhelm one receiver.</p>`;}

function fabrics(){return `<div class="fabric-choice"><section><h2>Ethernet + RoCE</h2><p class="roce-expansion">RDMA over Converged Ethernet</p><strong>24,576 H100 GPUs</strong><div class="fabric-core">Ethernet adapters ⇄ switches</div></section><section><h2>InfiniBand</h2><p class="roce-expansion">RDMA: remote direct memory access</p><strong>24,576 H100 GPUs</strong><div class="fabric-core">InfiniBand adapters ⇄ switches</div></section></div><div class="network-performance"><section><h2>Routing</h2></section><section><h2>Congestion control</h2></section><section><h2>Collective software</h2></section><section><h2>Job placement</h2></section></div>${credit('Meta Engineering · two cluster designs, March 2024','https://engineering.fb.com/2024/03/12/data-center-engineering/building-metas-genai-infrastructure/')}`;}
function ocs(state,compact){const cross=state.ocsPairing==='crossed';const w=compact?520:1100,h=compact?470:410;const x1=compact?60:120,x2=compact?460:980,y1=130,y2=300,mid=w/2;let b=R(mid-100,65,200,290,'surface-soft')+T(mid,105,'Optical circuit switch',compact?18:22);for(const [x,name,y]of[[x1,'A',y1],[x1,'B',y2],[x2,'C',y1],[x2,'D',y2]])b+=R(x-30,y-25,60,50)+T(x,y+8,name,25);b+=L(`M${x1+30} ${y1}H${mid-65}L${mid+65} ${cross?y2:y1}H${x2-30}`,'teal',false,false)+L(`M${x1+30} ${y2}H${mid-65}L${mid+65} ${cross?y1:y2}H${x2-30}`,'amber',false,false)+T(mid,385,'Mirrors set the light paths.',compact?22:25);return `<div class="ocs-layout">${svg(b,'Two simultaneous optical circuits are reconfigured from A to C and B to D into A to D and B to C.',w,h)}<figure class="ocs-source"><img src="../assets/references/networking-google-ocs.jpg" alt="Google optical circuit switch diagram showing MEMS mirrors connecting optical fiber paths.">${credit('Google TPU v4 · optical paths through MEMS mirrors','https://cloud.google.com/blog/topics/systems/tpu-v4-enables-performance-energy-and-co2e-efficiency-gains')}</figure></div>`;}
function campus(){return `<figure class="campus-fiber-image"><svg viewBox="0 0 1672 750" role="img" aria-label="Campus fiber handoff. The AI cluster connects through a border router and patch panel. A meet-me room connects customer and carrier fiber; entrance ducts and outside fiber lead to the carrier service."><image href="../assets/generated/networking-campus-fiber.png" width="1672" height="941"/></svg></figure>`;}
function distance(){const p=propagation(100);return `<div class="distance-simple"><div class="distance-exchange"><div class="site-icon">Facility A</div><div class="distance-fiber"><strong>100 km fiber route</strong><div><span>Request · ${p.oneWayMs} ms</span><i>→</i></div><div><span>Reply · ${p.oneWayMs} ms</span><i>←</i></div></div><div class="site-icon">Facility B</div></div><div class="distance-reply"><strong>${p.roundTripMs} ms</strong><span>propagation alone, before the reply can return</span></div><p class="distance-input">Signal speed in this calculation: 200,000 km/s</p></div>`;}
function straggler(){
 const rows=[20,20,20,50].map((ms,i)=>`<div class="straggler-row"><b>Server ${i+1}</b><div class="straggler-track"><span class="straggler-transfer ${ms===50?'straggler-slow':''}" style="width:${ms/50*100}%">${ms} ms</span>${ms<50?'<span class="straggler-wait">Waiting</span>':''}</div></div>`).join('');
 return `<div class="straggler-example"><p class="straggler-context">This step needs all four transfers.</p><div class="straggler-timeline" role="img" aria-label="Four transfers start together. Servers 1, 2 and 3 finish at 20 milliseconds and wait. Server 4 finishes at 50 milliseconds, when the next step can begin."><div class="straggler-axis"><span>Start</span><span>Next step</span></div>${rows}</div><p class="straggler-result">All four ready at <strong>50 ms</strong></p></div>`;
}
function metaStorage(){return `<div class="network-storage-case"><figure><img src="../assets/references/storage-meta-rsc.jpg" alt="Rows of racks in Meta’s Research SuperCluster.">${credit('Meta · Research SuperCluster · January 2022','https://ai.meta.com/blog/ai-rsc/')}</figure><div class="network-storage-tiers"><section><strong>175 PB</strong><span>Bulk storage</span></section><section><strong>46 PB</strong><span>Cache for repeated reads</span></section><section><strong>10 PB</strong><span>Shared file storage</span></section></div></div>`;}
function fairwaterScale(){return `<figure class="fairwater-quote"><blockquote>“…support training models with hundreds of trillions of parameters.”</blockquote><div class="fairwater-fiber"><span>Dedicated fiber between sites</span><blockquote>“That allows the data to travel, congestion-free, at nearly the speed of light.”</blockquote></div>${credit('Microsoft · November 12, 2025','https://news.microsoft.com/source/features/ai/from-wisconsin-to-atlanta-microsoft-connects-datacenters-to-build-its-first-ai-superfactory/')}</figure>`;}

export function networkingVisual(id,state,compact=false){switch(id){case'networking-purpose':return generated();case'consumer-hardware-meme':return hardwareMeme();case'three-scales':return scales();case'microsoft-ai-superfactory':return superfactory(state,compact);case'fairwater-model-scale':return fairwaterScale();case'meta-rsc':return metaStorage();case'packet-path':return packet(state);case'shared-model':return sharedModel();case'network-hardware':return hardware();case'copper-and-light':return media();case'optical-packaging':return packaging();case'leaf-spine':return leafSpineOverview();case'physical-fabric':return physicalFabric(compact);case'shared-uplinks':return cut(state);case'traffic-placement':return fabric(compact,state.placement);case'incast':return incast(compact);case'ethernet-infiniband':return fabrics();case'optical-circuits':return ocs(state,compact);case'campus-fiber':return campus();case'distance-latency':return distance();case'network-diagnosis':return straggler();default:throw new Error(`No networking visual for ${id}`);}}
