import {sampleQuality,heatBalance,readiness,transition,maintenanceState,unavailableUnion,diagnosticEvidence,flexibleSchedule} from './operations-model.js';
const arrow='<span class="o-arrow" aria-hidden="true">→</span>';
const card=(title,body,cls='')=>`<section class="o-card ${cls}"><h2>${title}</h2><p>${body}</p></section>`;
const result=(value,label,cls='')=>`<div class="o-result ${cls}"><strong>${value}</strong><span>${label}</span></div>`;
const strip=text=>`<div class="o-strip">${text}</div>`;
const rack=()=>'<div class="o-rack" aria-hidden="true"><i></i><i></i><i></i><i></i></div>';
const photo=(asset,alt,credit,url)=>`<figure class="o-photo"><img src="../assets/references/${asset}" alt="${alt}"><figcaption><a href="${url}" target="_blank" rel="noreferrer">${credit}</a></figcaption></figure>`;
const graph=(label,draw)=>`<div class="o-chart"><svg class="wide" viewBox="0 0 1100 350" role="img" aria-label="${label}">${draw(false)}</svg><svg class="narrow" viewBox="0 0 410 340" role="img" aria-label="${label}">${draw(true)}</svg></div>`;
const text=(x,y,value,cls='',anchor='middle')=>`<text x="${x}" y="${y}" text-anchor="${anchor}" class="${cls}">${value}</text>`;
const line=(x1,y1,x2,y2,cls='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${cls}"/>`;
const credit=(label,url)=>`<p class="o-credit"><a href="${url}" target="_blank" rel="noreferrer">${label}</a></p>`;
function replication(state){const bad=state.replicaFault==='write';return `<div class="o-stack o-replication"><div class="o-replica-comparison"><section><h2>Live replicas</h2><div class="o-replica-pair">${card('Copy A',bad?'Bad write':'Device failed','warning')}${bad?arrow:'<span class="o-arrow" aria-label="Failed device unavailable">×</span>'}${card('Copy B',bad?'Bad write copied':'Valid data available',bad?'warning':'positive')}</div></section><section class="o-retained-copy"><h2>Retained backup</h2><b>✓ Earlier valid version</b><p>${bad?'Restore, then reconcile later changes.':'Available if the live copies fail.'}</p></section></div><div class="o-gmail-case"><b>Gmail · 2011</b><span>A software bug reached replicated copies. Offline tape preserved the data; restoration took hours.</span></div>${credit('Google · Gmail incident, February 2011','https://gmail.googleblog.com/2011/02/gmail-back-soon-for-everyone.html')}</div>`;}
function llama(){return `<div class="o-stack o-llama-recovery"><div class="o-three">${result('54 days','Llama 3 training snapshot')}${result('466','47 planned + 419 unexpected interruptions')}${result('&gt;90%','Effective training time')}</div><div class="o-hardware-interruptions"><b>≈78%</b><span>of unexpected interruptions involved confirmed or suspected hardware issues.</span></div><div class="o-restoration-path"><span>Automated diagnosis</span>${arrow}<span>Restart + restore</span>${arrow}<span>Training advances</span></div>${strip('Only three incidents required significant manual intervention.')}${credit('Meta · The Llama 3 Herd of Models · §3.3.4','https://arxiv.org/html/2407.21783v3#S3.SS3.SSS4')}</div>`;}
function demandResponse(){return `<div class="o-stack o-demand-response"><div class="o-case">${photo('storage-google-dalles-repair.jpg','A Google technician replaces a motherboard at The Dalles data center.','Google · The Dalles, Oregon · facility operations','https://www.datacenters.google/discover-more/photo-gallery/')}<div class="o-case-copy"><h2>The Dalles, Oregon</h2><p>Day-ahead pilot with Northern Wasco County PUD.</p><div class="o-case-step"><b>Grid event notice</b><span>Identify constrained hours</span></div><div class="o-case-step"><b>Limit non-urgent work</b><span>Assign hourly compute budgets</span></div><div class="o-case-step"><b>Reschedule eligible jobs</b><span>Use deadline slack and later capacity</span></div></div></div>${credit('Google Cloud · Demand response, October 2023','https://cloud.google.com/blog/products/infrastructure/using-demand-response-to-reduce-data-center-power-consumption')}</div>`;}
function schedule(state){
 const m=flexibleSchedule({deadlineHour:state.deadline,shift:state.shift});
 const label=`Power from 13:00 to 21:00. The job ${state.shift?'pauses from 14:00 to 16:00':'continues during the grid event'}, finishes at ${m.finishHour}:00, and ${m.meetsDeadline?'meets':'misses'} its deadline.`;
 const chart=graph(label,small=>{
  const width=small?410:1100,left=small?52:80,right=small?384:1060,top=55,bottom=255,x=hour=>left+(hour-13)*(right-left)/8,y=power=>bottom-(power-18)/8*(bottom-top);
  let body=`<rect x="${x(14)}" y="${top-15}" width="${x(16)-x(14)}" height="${bottom-top+15}" class="heat-area"/>${text(x(15),top-25,'Grid event','event-label')}`;
  for(const power of [20,24])body+=`${line(left,y(power),right,y(power),'grid')}${text(left-12,y(power)+6,String(power),'tick','end')}`;
  body+=text(left-12,top,'MW','tick','end');
  const breaks=[...new Set([13,21,...m.segments.flatMap(segment=>[segment.start,segment.end])])].sort((a,b)=>a-b),points=[];
  for(let i=0;i<breaks.length-1;i++){const start=breaks[i],end=breaks[i+1],on=m.segments.some(segment=>start>=segment.start&&start<segment.end);points.push(`${x(start)},${y(on?24:20)}`,`${x(end)},${y(on?24:20)}`);}
  body+=`<polyline points="${points.join(' ')}" class="capacity-line"/>${line(x(state.deadline),top-10,x(state.deadline),bottom+7,'ready-line')}${text(x(state.deadline),bottom+66,'Deadline','deadline-label')}`;
  for(let hour=13;hour<=21;hour+=small?2:1)body+=text(x(hour),bottom+30,`${hour}:00`,'tick');
  return body;
 });
 return `<div class="o-stack o-schedule"><div class="o-schedule-inputs"><span>20 MW base + 4 MW job</span><span>3 hours of work</span><span>Progress retained during pause</span></div>${chart}<div class="o-three o-schedule-results">${result(`${m.finishHour}:00`,'Job completes',m.meetsDeadline?'':'warning')}${result(`${m.eventPeakMW} MW`,'Peak during grid event')}${result(`${m.jobMWh} MWh`,'Job energy in either plan')}</div><div class="o-schedule-verdict ${m.meetsDeadline?'':'warning'}" role="status">${!m.meetsDeadline?'The shifted job misses its deadline. Continue through the event or change the accepted plan.':state.shift?'The job finishes on time; 24 MW must be available after the event.':'The job finishes early; its 4 MW demand overlaps the grid event.'}</div></div>`;
}
function boundaries(state){const local=state.sensor==='branch';return `<div class="o-stack"><div class="o-loop"><section class="o-plant"><h2>Cooling plant</h2><div class="o-plant-icon" aria-hidden="true"><i></i><i></i></div><div class="o-tag ${local?'':'warning'}">Supply 30 °C<br><small>Observed 10:00</small></div></section><div class="o-pipes"><div class="o-supply">Supply →</div><div class="o-mixing">Mixing junction</div><div class="o-return">← Return</div></div><section class="o-rack-zone"><h2>Row B · 20 racks</h2>${rack()}<div class="o-tag warning">Device temperature ↑</div></section></div>${local?`<div class="o-three">${card('At the branch','Current flow + supply / return temperatures','positive')}${card('At the row','Electrical input + device temperatures','positive')}${card('At the service','Output speed + workload state','positive')}</div>`:strip('A normal upstream temperature does not establish current flow through Row B.')}</div>`;}
function clocks(state){const old=state.clock==='old',m=sampleQuality({observedAt:old?0:595,receivedAt:599,now:600,maxAge:60});return `<div class="o-stack"><div class="o-clock-now">Now <b>10:10:00</b></div><div class="o-three">${card('Observed',old?'10:00:00':'10:09:55',old?'warning':'positive')}${card('Received','10:09:59')}${card('Displayed','30 °C')}</div><div class="o-two o-spaced">${result(old?'10 minutes':'5 seconds','Age of the measurement',old?'warning':'')}${result(m.quality,'Required age ≤ 60 seconds',old?'warning':'')}</div></div>`;}
function balance(state){const measured=state.flowEvidence==='measured',flow=measured?50:100,m=heatBalance({flow});return `<div class="o-stack"><div class="o-balance-boundary"><span>Row B · steady state · all heat enters water</span><strong>Electrical input: 2.09 MW</strong></div><div class="o-three o-readings">${result(`${flow} kg/s`,measured?'Independent current flow':'Displayed flow · 10 minutes old',measured?'':'warning')}${result('30 → 40 °C','Current row-branch temperatures')}${result('4.18 kJ/(kg·K)','Specific heat of water')}</div><div class="o-equation">${flow} × 4.18 × 10 = <b>${(m.heatMW*1000).toLocaleString('en-US')} kW</b></div>${strip(measured?'The heat balance closes. The cause of reduced flow is still unresolved.':'The readings disagree with the electrical input. Check their time and location.')}</div>`;}
function prove(state){const stage=state.readiness,m=readiness({command:true,acknowledged:stage!=='command',flowProven:stage==='proven',temperatureProven:stage==='proven'});return `<div class="o-stack"><div class="o-status-chain">${card('Request sent','Start unit C','positive')}${arrow}${card('Controller reply',stage==='command'?'Waiting for acknowledgment':'Command received',stage==='command'?'':'positive')}${arrow}${card('Process measured',m.available?'Flow + temperature in range':'Not yet proven',m.available?'positive':'warning')}</div><div class="o-two o-spaced">${result('6 MW','Proposed workload')}${result(m.available?'Ready':'Hold new work',m.available?'Required cooling state demonstrated':'Available capacity is not confirmed',m.available?'':'warning')}</div></div>`;}
function delay(state,policy=false){const minutes=policy?3:state.delayMinutes,m=transition({delayMinutes:minutes,admit:policy?state.admit:'now'});return `<div class="o-stack">${graph('Heat input and active removal during the standby delay',small=>{const left=small?43:90,right=small?380:1045,top=50,bottom=268,width=right-left,end=left+width*.75,y=v=>bottom-v*31;const newLoad=policy&&state.admit==='ready'?4:6;return `${line(left,bottom,right,bottom,'axis')}${line(left,top,left,bottom,'axis')}${[4,5,6,7].map(v=>`${text(left-12,y(v)+6,String(v),'tick','end')}${line(left,y(v),right,y(v),'grid')}`).join('')}${text(left,27,'MW','tick','start')}${newLoad>5?`<rect x="${left}" y="${y(6)}" width="${end-left}" height="31" class="heat-area"/>`:''}<path d="M${left} ${y(newLoad)}H${end}V${y(6)}H${right}" class="load-line"/><path d="M${left} ${y(5)}H${end}V${y(7)}H${right}" class="capacity-line"/>${text(left,306,'0','tick')}${text(end,306,`${minutes} min`,'tick')}${line(end,50,end,278,'ready-line')}${text(right-4,39,'Standby +2 MW','tick','end')}`;})}<div class="o-legend"><span><i class="load"></i>Heat input</span><span><i class="capacity"></i>Heat removal available</span></div><div class="o-three o-transition-result">${result(`${m.imbalanceMW} MW`,'Temporary excess heat')}${result(`${(m.consumedMWh*1000).toFixed(1)} kWh`,'Accumulated before readiness',m.withinBudget?'':'warning')}${result('40 kWh','Validated transition allowance')}</div>${strip(policy?(state.admit==='ready'?'The extra workload waits three minutes for measured readiness.':'Starting on the command exceeds this tested energy allowance.'):(m.withinBudget?'Within the supplied energy allowance; confirm local operating limits.':'The unchanged final capacity does not cover this longer transition.'))}</div>`;}
function maintenance(state){const m=maintenanceState({sharedControl:state.sharedControl});return `<div class="o-stack"><div class="o-control-supply ${state.sharedControl?'off':''}">Shared 24 V control supply <b>${state.sharedControl?'ISOLATED':'AVAILABLE'}</b></div><div class="o-branch-lines" aria-hidden="true"><span>↓</span><span>↓</span><span>↓</span></div><div class="o-three">${card('Unit A · 3 MW',state.sharedControl?'Control unavailable':'Operating',state.sharedControl?'warning':'positive')}${card('Unit B · 3 MW',state.sharedControl?'Control unavailable':'Operating',state.sharedControl?'warning':'positive')}${card('Unit C · 3 MW','Under maintenance','warning')}</div><div class="o-two o-spaced">${result('5 MW','Current heat load')}${result(`${m.availableMW} MW`,'Cooling that can operate',m.capacityMeetsLoad?'':'warning')}</div></div>`;}
function mapping(state){const checked=state.mapping==='checked';return `<div class="o-stack"><div class="o-map-row"><span>Physical connection</span><b>Cooling branch C2</b>${arrow}<b>Row B</b></div><div class="o-map-row ${checked?'positive':'warning'}"><span>Control configuration</span><b>Cooling branch C2</b>${arrow}<b>${checked?'Row B':'Row A'}</b></div><div class="o-mapping-action">A C2 alarm requests a load reduction on <strong>${checked?'Row B ✓':'Row A ✕'}</strong></div>${strip(checked?'Verify the actual response before removing the operating restriction.':'A successful command to the wrong row does not protect Row B.')}</div>`;}
function common(state){return `<div class="o-stack"><div class="o-two"><div class="o-path off">Full-capacity path A <span>Unavailable</span></div><div class="o-path ${state.commonCause?'off':''}">Full-capacity path B <span>${state.commonCause?'Unavailable':'Carries the load'}</span></div></div>${state.commonCause?`<div class="o-common-event">One flawed revision reaches both controllers <b>A common cause defeats both paths together</b></div>`:`<div class="o-independence">A component fault in A leaves B operating.</div>`}${strip('Multiplying path failure probabilities assumes independent failures and recovery.')}</div>`;}
function overlap(){const m=unavailableUnion([[0,12],[8,26]]);return `<div class="o-stack">${graph('Service incidents overlap for four minutes, so unavailable time is twenty-six minutes',small=>{const left=small?45:80,right=small?385:1040,unit=(right-left)/30;const rows=[['Incident A',0,12,70,'incident-a'],['Incident B',8,26,160,'incident-b'],['Service unavailable',0,26,250,'incident-union']];return rows.map(([label,start,end,y,cls])=>`${text(left,y-15,label,'tick','start')}<rect x="${left+start*unit}" y="${y}" width="${(end-start)*unit}" height="30" rx="5" class="${cls}"/>${text(left+start*unit,y+56,String(start),'tick')}${text(left+end*unit,y+56,`${end} min`,'tick')}`).join('');})}<div class="o-two">${result('12 + 18 − 4 = 26 min','Union of service-impact intervals')}${result(`${(m.availability*100).toFixed(4)}%`,'30-day window · 43,200 minutes')}</div></div>`;}
const evidenceOptions=[['plant','Fresh plant average','Confirms the upstream temperature'],['branch','Current row branch','Flow, supply and return temperatures'],['load','Aligned row electrical input','Power and workload history'],['mapping','Current configuration record','Physical row IDs, commands and changes'],['pumps','Installed pump inventory','Rated capacities and spare units']];
function diagnosis(state){const selected=state.evidence||[],m=diagnosticEvidence(selected);return `<div class="o-diagnosis"><section class="o-problem"><h2>Row B after maintenance</h2><p>Device temperature is rising.</p><p>A new training job has started.</p><p>The plant supply display is ten minutes old.</p><strong>Choose the evidence that separates the causes.</strong><div class="o-evidence-findings">${selected.includes('branch')?'<p><b>Branch:</b> flow halved; temperature rise doubled.</p>':''}${selected.includes('load')?'<p><b>Load:</b> electrical input stayed at 2.09 MW.</p>':''}${selected.includes('mapping')?'<p><b>Mapping:</b> branch C2 still targets row A.</p>':''}${selected.includes('plant')?'<p><b>Plant:</b> supply remains at 30 °C upstream.</p>':''}${selected.includes('pumps')?'<p><b>Inventory:</b> three pumps remain installed.</p>':''}</div></section><section class="o-evidence-choices">${evidenceOptions.map(([key,label,description])=>`<button data-evidence="${key}" aria-pressed="${selected.includes(key)}"><span>${selected.includes(key)?'✓':'+'}</span><div><b>${label}</b><small>${description}</small></div></button>`).join('')}<p class="o-check-status" role="status">${m.sufficient?'You can distinguish the load change from the row flow problem—and see the control mismatch.':'Choose observations before selecting an intervention.'}</p></section></div>`;}
function decision(state){const responses={restart:'A command acknowledgment still cannot establish which physical row responded or whether its cooling recovered.',hold:'Yes. Keep the extra workload restricted under the approved policy. Restore the correct mapping, establish current local flow and temperature, then verify the required service before admitting it.',plant:'Normal upstream temperature leaves the local flow and wrong-row command unresolved.'};return `<div class="o-diagnosis"><section class="o-problem"><h2>What the evidence establishes</h2><p>Same electrical input</p><p>Half the branch flow</p><p>Load-reduction command mapped to the wrong row</p><strong>The physical cause of low flow still needs confirmation.</strong></section><section class="o-answer"><div class="o-answer-choices">${[['restart','Admit work when the controller acknowledges the corrected command.'],['hold','Hold extra work until local conditions and service are proven.'],['plant','Admit work because the plant temperature is normal.']].map(([key,label])=>`<button data-diagnosis="${key}" aria-pressed="${state.diagnosis===key}">${label}</button>`).join('')}</div><button id="diagnosis-reveal" ${state.diagnosis?'':'disabled'} aria-expanded="${state.showDiagnosis}">${state.showDiagnosis?'Hide reasoning':'Check the decision'}</button><p class="o-feedback" role="status">${state.showDiagnosis?responses[state.diagnosis]:''}</p></section></div>`;}
export function operationsVisual(id,state){switch(id){
 case 'operations-purpose':return `<div class="o-opening"><section><div class="o-screen"><span>PLANT SUPPLY</span><b>30 °C</b><small>Last observation 10:00</small><i>● Normal</i></div><h2>The plant dashboard</h2></section><div class="o-question">?</div><section>${rack()}<h2>Row B · 10:10</h2><p class="o-hot">Device temperature rising</p></section></div>`;
 case 'measurement-boundaries':return boundaries(state);
 case 'measurement-time':return clocks(state);
 case 'heat-balance':return balance(state);
 case 'diagnostic-observations':return `<div class="o-evidence-table"><div><b>Possible explanation</b><b>Observation that separates it</b></div><div><h2>More heat input</h2><p>Aligned row power and job history</p></div><div><h2>Less coolant flow</h2><p>Independent branch flow and pressure</p></div><div><h2>Misleading measurements</h2><p>Sensor location, sample time and quality</p></div><div><h2>Heat still accumulating</h2><p>Time history before a steady plateau</p></div></div>`;
 case 'google-cooling':return `<div class="o-case">${photo('operations-google-cooling-facility.jpg','Google data center cooling infrastructure.','Google data center · Google DeepMind, August 2018','https://deepmind.google/blog/safety-first-ai-for-autonomous-data-centre-cooling-and-industrial-control/')}<div class="o-case-copy"><h2>Google / DeepMind</h2><div class="o-case-step"><b>Every 5 minutes</b><span>Propose cooling actions</span></div><div class="o-case-step"><b>Two checks</b><span>AI constraints + local control limits</span></div><div class="o-case-step"><b>Operator authority</b><span>Override and return to existing controls</span></div></div></div>`;
 case 'control-layers':return `<div class="o-stack"><div class="o-three o-control-layers">${card('Device controller','Keep the measured branch condition near its setpoint.')}${card('Facility sequence','Enable equipment and confirm usable capacity.')}${card('Workload scheduler','Choose which work starts, waits or moves.')}</div><div class="o-authority-loop"><span>Process measurements</span><b>⇄</b><span>Capacity and readiness</span><b>⇄</b><span>Load request</span></div>${strip('The scheduler requests capacity; it does not redefine a pump’s operating limits.')}</div>`;
 case 'google-verification':return `<div class="o-full-figure">${photo('operations-google-local-verification.jpg','Google DeepMind original diagram showing the local control system independently verifying the AI recommendations against its constraints before applying them.','Local verification before implementation · Google DeepMind, 2018','https://deepmind.google/blog/safety-first-ai-for-autonomous-data-centre-cooling-and-industrial-control/')}</div>`;
 case 'prove-readiness':return prove(state);
 case 'control-delay':return delay(state);
 case 'admit-work':return delay(state,true);
 case 'google-demand-response':return demandResponse();
 case 'deadline-scheduling':return schedule(state);
 case 'cloudflare-pdx':return `<div class="o-stack"><div class="o-case-date">Cloudflare · Portland · November 2023</div><div class="o-failure-boundaries"><section class="o-tested-boundary"><span>Previously tested</span><h2>HA portion of PDX-04</h2><div class="o-server-pair"><i></i><i></i><i></i></div></section><section class="o-facility-boundary"><span>Actual failure scope</span><h2>Entire PDX-04 facility</h2><div class="o-dependency-tags"><b>Cluster</b><b>Other dependencies</b><b>Management services</b></div></section></div><div class="o-two">${card('Distributed edge traffic','Mostly continued','positive')}${card('Dashboard, API and analytics','Disrupted by facility dependencies','warning')}</div><p class="o-credit"><a href="https://blog.cloudflare.com/post-mortem-on-cloudflare-control-plane-and-analytics-outage/" target="_blank" rel="noreferrer">Cloudflare · November 2023 incident report</a></p></div>`;
 case 'maintenance-scope':return maintenance(state);
 case 'configuration-mapping':return mapping(state);
 case 'return-to-service':return `<div class="o-stack"><div class="o-three">${card('Before work','Scope · surviving paths · qualified team · parts · rollback')}${card('Before restoration','Current asset IDs · approved settings · closed work record')}${card('Before removing restrictions','Measured process response · required service · authorized release','positive')}</div><div class="o-restoration-path"><span>Work complete</span>${arrow}<span>Configuration verified</span>${arrow}<span>Response measured</span>${arrow}<span>Service restored</span></div></div>`;
 case 'common-cause':return common(state);
 case 'replication-and-backup':return replication(state);
 case 'london-recovery':return `<div class="o-stack"><div class="o-case-date">Google Cloud · London · July 2022</div><ol class="o-timeline o-dated-timeline"><li class="service"><time>19 July<br>10:05 PDT</time><span>Servers powered down during cooling failure</span></li><li class="physical"><time>19 July<br>14:13 PDT</time><span>Cooling repaired</span></li><li class="service"><time>20 July<br>04:28 PDT</time><span>Initial cloud-service restoration milestone</span></li></ol><div class="o-two">${result('14 h 15 min','Recovery continued after cooling returned')}<div class="o-case-consequence">A physical repair and a restored computing service have different endpoints.</div></div><p class="o-credit"><a href="https://status.cloud.google.com/incidents/fmEL9i2fArADKawkZAa2" target="_blank" rel="noreferrer">Google Cloud · final July 29 incident summary · residual issues lasted longer</a></p></div>`;
 case 'overlap-outages':return overlap();
 case 'llama-recovery':return llama();
 case 'causal-evidence':return `<div class="o-stack"><div class="o-record-type">${state.incidentView==='observed'?'Observation':state.incidentView==='hypothesis'?'Hypothesis':'Evidence to test it'}</div>${state.incidentView==='observed'?`<div class="o-two">${card('10:00','Configuration revision changed.')}${card('10:02','A rack temperature alarm appeared.')}</div>`:state.incidentView==='hypothesis'?`<div class="o-hypothesis">The new mapping sent a command to the wrong row.</div>`:`<div class="o-three">${card('Revision diff','Which identities or actions changed?')}${card('Command log','Which target acknowledged the action?')}${card('Process trace','Which physical flow and temperature changed?')}</div>`}${strip('Keep unresolved causes visible until the observations distinguish them.')}</div>`;
 case 'cloudflare-retest':return `<div class="o-stack"><div class="o-case-date">Cloudflare · repeat Portland power failure · 26 March 2024</div><div class="o-improvement-chain">${card('After November','Expanded capacity + revised failover')}${arrow}${card('February','Tested an entire-facility cut')}${arrow}${card('26 March','Repeat facility power loss','warning')}</div><div class="o-recovery-milestones"><div><time>14:58 UTC</time><b>Facility power fails</b></div>${arrow}<div><time>15:05 UTC</time><b>API + dashboard normal</b></div></div><div class="o-two">${result('7 minutes','API/dashboard endpoint · no human intervention')}<div class="o-case-consequence">Analytics recovered later that day.</div></div><p class="o-credit"><a href="https://blog.cloudflare.com/major-data-center-power-failure-again-cloudflare-code-orange-tested/" target="_blank" rel="noreferrer">Cloudflare · April 2024 follow-up report</a></p></div>`;
 case 'diagnosis-check':return diagnosis(state);
 case 'operating-decision':return decision(state);
 default:throw new Error(`Unknown operations scene: ${id}`);
}}
