const staging='https://docs.johnsoncontrols.com/bas/r/Metasys/en-US/Chilled-Water-Plant-for-Guideline-36-Application-Note/1.0/Chiller-sequence-of-operations/Chiller-and-waterside-economizer-staging-determination-5.20.1-15/Stage-Up-Part-Load-Ratio-SPLRUP';
const intel='https://www.intel.com/content/dam/doc/white-paper/intel-it-thermal-storage-system-provides-emergency-data-center-cooling-paper.pdf';
export const reserveScenes=[
 {id:'chiller-staging',label:'How much cooling headroom?',title:'When should the next chiller start?',reference:'d14-coordinating-control-and-work',objective:'D14.2',pedagogical_role:'mechanism',sources:[staging],explanation:['The preceding 1 MW headroom and three-minute startup are teaching inputs, not a standard operating margin. This Johnson Controls Metasys implementation of Guideline 36 uses different stage-up loading thresholds: 80% for stages containing only positive-displacement chillers; 90% when the current plant and next stage include constant-speed centrifugal chillers. Variable-speed centrifugal thresholds also vary with lift. These are efficiency-staging thresholds with time and trend conditions, not guaranteed spare-capacity percentages or a data-center-wide rule. Temperature and pressure failsafes can also trigger staging. Operators set the reserve from three distinct questions: demand (expected load and ramp), usable capacity (weather, local coolant flow, and the required failure case), and response time (how long new equipment takes to start versus the thermal storage that can bridge that delay). Spare heat-removal capacity in MW is usable capacity minus demand; stored thermal energy instead buys time. These categories separate the load to serve, the cooling that can reach it, and the transition before additional equipment is ready. See the linked sequence and its Stage up efficiency condition and Failsafe condition sections.']},
 {id:'intel-cooling-reserve',label:'Intel: stored cooling',title:'Intel stored chilled water to outlast the server UPS.',reference:'d14-coordinating-control-and-work',objective:'D14.2',pedagogical_role:'case-study',sources:[intel],explanation:['Intel’s 2007 report describes two 24,000-US-gallon tanks held at 42°F (5.6°C), supplementing a 55°F (12.8°C) supply. The tanks were sized for seven minutes beyond five minutes of full-load UPS runtime: twelve minutes by design. During the 2006 outage, lightly loaded servers ran over fifteen minutes; stored water maintained cooling throughout and removed residual heat afterward. Backed-up pumps and air-handler fans kept moving heat. This is stored thermal energy with finite duration, distinct from spare heat-removal capacity in MW. The original Figure 2 is reproduced; the report does not name the facility.']}
];
const credit=(label,url)=>`<p class="o-credit"><a href="${url}" target="_blank" rel="noreferrer">${label}</a></p>`;
export function reserveVisual(id){
 if(id==='chiller-staging')return `<div class="or-staging"><p class="or-kicker">Johnson Controls · manufacturer control sequence</p><div class="or-thresholds">${[['Positive-displacement chillers',80],['Constant-speed centrifugal chillers',90]].map(([label,value])=>`<section><h2>${label}</h2><div class="or-gauge" role="img" aria-label="Stage-up loading threshold ${value} percent"><span style="width:${value}%"></span><b style="left:${value}%">${value}%</b></div><div class="or-gauge-scale"><span>0%</span><span>100% load</span></div></section>`).join('')}</div><p class="or-action">Sustained load above the threshold → start the next stage</p><ul class="or-margin-factors" aria-label="Factors that set the cooling reserve"><li><b>Demand</b> — expected load and ramp</li><li><b>Usable capacity</b> — weather, local flow, required failure case</li><li><b>Response time</b> — startup delay versus thermal-buffer duration</li></ul>${credit('Johnson Controls · Metasys / Guideline 36 · 2025',staging)}</div>`;
 if(id==='intel-cooling-reserve')return `<div class="or-storage"><div class="or-storage-body"><figure><a href="../assets/references/operations-intel-thermal-storage.png" target="_blank" rel="noreferrer" aria-label="Open Intel’s original thermal storage diagram"><img src="../assets/references/operations-intel-thermal-storage.png" alt="Intel Figure 2: two tanks of 42°F water connect to the 55°F chilled-water supply through thermal-storage control valves, with backed-up pumps maintaining circulation." width="1134" height="618"></a></figure><div class="or-storage-facts"><div><strong>2 × 24,000 gal</strong><span>Stored at 5.6°C</span></div><div><strong>12 minutes</strong><span>Designed to cover 5-minute UPS + 7 minutes</span></div><div><strong>&gt;15 minutes</strong><span>Cooling maintained during the 2006 outage, at light IT load</span></div></div></div><p class="or-action">Pumps and air-handler fans remained on backed-up power.</p>${credit('Intel IT · September 2007 · original Figure 2',intel)}</div>`;
 return null;
}
