const telemetry='d14-telemetry-and-observability',control='d14-coordinating-control-and-work',reliability='d14-maintenance-and-service-reliability';
const c=(key,label,options)=>({key,label,options});
const s=(id,label,title,reference,objective,explanation,extra={})=>({id,label,title,reference,objective,pedagogical_role:'mechanism',explanation:[explanation],...extra});
export const learningContract=Object.freeze({driving_question:'How do you keep an operating campus within its service limits?',fixed_boundary:'One 2.09 MW rack row and its cooling branch; a separate plant-start example coordinates a 6 MW load.',changed_variable:'Measurement age, readiness delay, maintenance scope and configuration.',primary_payoff:'Choose an intervention from current local evidence and verify service recovery.',misconception:'A green component dashboard establishes that the service has what it needs.',closing_question:'What evidence separates a cooling restriction from a workload change, and what releases the next workload?'});
export const initialState={sensor:'plant',clock:'old',flowEvidence:'display',readiness:'command',delayMinutes:2,admit:'now',shift:true,deadline:20,sharedControl:false,mapping:'old',commonCause:false,replicaFault:'device',incidentView:'observed',evidence:[],diagnosis:'',showDiagnosis:false};
export const scenes=[
 s('operations-purpose','Controls, operations and reliability','The racks are hot. The dashboard is green.',telemetry,'D14.1','The opening alarm concerns rack row B while the reassuring value is a ten-minute-old plant supply temperature. Location and measurement time decide whether observations describe the same condition. Rack row B contains twenty racks; its current electrical heat input totals 2.09 MW.',{pedagogical_role:'problem'}),
 s('measurement-boundaries','Locate the measurements','Measure the branch that has the problem.',telemetry,'D14.1','Plant supply temperature does not establish row branch flow or the temperature after a mixing point. Electrical input, branch flow, supply/return and device temperatures describe different boundaries.',{controls:[c('sensor','Inspect',[['plant','Plant dashboard'],['branch','Row branch']])]}),
 s('measurement-time','Check the observation time','A new message can contain an old measurement.',telemetry,'D14.1','At 10:10:00, the plant value was observed at 10:00:00 but delivered at 10:09:59. For this exercise the freshness requirement is at most sixty seconds. Compare with a new sample observed at 10:09:55.',{controls:[c('clock','Measurement',[['old','Held value'],['fresh','Fresh sample']])]}),
 s('heat-balance','Reconcile the evidence','Did the heat double—or did the flow reading freeze?',telemetry,'D14.1','Rack row B at a steady plateau, with all of its heat entering this water branch: electrical heat 2.09 MW; cp 4.18 kJ/(kg K); supply 30 C, return 40 C. A stale 100 kg/s gives 4.18 MW; independent current flow 50 kg/s gives 2.09 MW. The corrected balance establishes reduced flow, not its cause.',{controls:[c('flowEvidence','Flow evidence',[['display','Displayed 100 kg/s'],['measured','Independent 50 kg/s']])]}),
 s('diagnostic-observations','Separate the causes','Each possible cause needs a different observation.',telemetry,'D14.1','Compare aligned row electrical input, independently measured branch flow, and sensor placement/quality. A balance helps discriminate hypotheses; it cannot identify a failed valve from a temperature alarm alone.'),
 s('google-cooling','Google cooling controls','An optimizer still needs an operating boundary.',control,'D14.2','Google DeepMind reported in August 2018 that its supervisory AI proposed cooling actions every five minutes. It excluded low-confidence actions and applied operator-defined constraints. Local controls checked instructions independently. Operators could leave autonomous mode for existing rules. Five minutes is the optimization cadence, not protective response latency. The real facility photo does not identify an exact campus.',{pedagogical_role:'case-study',sources:['https://deepmind.google/blog/safety-first-ai-for-autonomous-data-centre-cooling-and-industrial-control/']}),
 s('control-layers','Three control layers','Three decisions act on the same rack.',control,'D14.2','A device controller regulates a local variable; the facility sequence stages the available equipment; the workload scheduler admits work. Authority, measurements and limits need a defined interface.'),
 s('google-verification','Independent local verification','The local controller checks the proposed action again.',control,'D14.2','Original Google DeepMind 2018 diagram shows independent local verification of AI actions before implementation. The visual documents the actual supervisory/local boundary in the source account.',{pedagogical_role:'case-study',sources:['https://deepmind.google/blog/safety-first-ai-for-autonomous-data-centre-cooling-and-industrial-control/']}),
 s('prove-readiness','Command and confirmation','“Start” is a request. Available capacity needs proof.',control,'D14.2','Follow a requested standby unit through acknowledgment, measured flow and acceptable temperature. Fresh process feedback establishes the exercise readiness state; a communication acknowledgment alone does not.',{controls:[c('readiness','Standby state',[['command','Start requested'],['ack','Acknowledged'],['proven','Flow + temperature proven']])]}),
 s('control-delay','A delayed response','One extra minute changes the load decision.',control,'D14.2','Active heat removal is 5 MW; a new workload would produce 6 MW. The standby unit adds 2 MW when proven ready. A separately validated usable thermal allowance of .04 MWh is supplied for the exercise. A two-minute delay consumes .0333 MWh; three consumes .05. The scalar check is not a local-temperature or control-stability certification.',{controls:[c('delayMinutes','Standby ready in',[[2,'2 minutes'],[3,'3 minutes']])]}),
 s('admit-work','Coordinate the workload','Wait for readiness, or use a tested transition envelope.',control,'D14.2','Compare immediate admission with admission after measured readiness. Waiting avoids this extra-workload imbalance; immediate admission depends on a supported transition. Both still require actual operating limits and confirmed process measurements.',{controls:[c('admit','Admit the extra workload',[['now','On the start command'],['ready','After readiness is proven']])]}),
 s('google-demand-response','Google demand response','Google deferred work to help the grid',control,'D14.2','Google’s October 2023 account describes a day-ahead demand-response pilot with Northern Wasco County PUD at The Dalles, Oregon. A grid event notice prompts hourly limits on non-urgent work, which can be rescheduled after the event or moved to another grid when feasible.',{pedagogical_role:'case-study',sources:['https://cloud.google.com/blog/products/infrastructure/using-demand-response-to-reduce-data-center-power-consumption']}),
 s('deadline-scheduling','Move the work. Meet the deadline.','Can we reduce demand and still finish on time?',control,'D14.2','A 4 MW job needs three hours of execution above a 20 MW base load, starting at 13:00. Retaining its progress across a 14:00–16:00 grid event moves completion from 16:00 to 18:00 without changing its 12 MWh of execution energy. The plan needs sufficient deadline slack and available capacity after the event.',{pedagogical_role:'balance',controls:[c('shift','Execution plan',[[false,'Continue through event'],[true,'Pause for grid event']]),c('deadline','Completion deadline',[[20,'20:00'],[17,'17:00']])]}),
 s('cloudflare-pdx','Cloudflare PDX outage','The test covered only part of this facility.',reliability,'D14.4','Cloudflare’s November 2023 postmortem describes previously undiscovered facility dependencies: earlier tests at PDX-04 covered its high-availability portion, not the entire facility. The high-availability cluster spanned three sites; the other two facilities had been removed in previous tests. Edge network traffic mostly continued while dashboard, API and analytics were disrupted. This is a test-scope and service-boundary case; uncertain reconstruction of the power-failure cause is omitted.',{pedagogical_role:'case-study',sources:['https://blog.cloudflare.com/post-mortem-on-cloudflare-control-plane-and-analytics-outage/']}),
 s('maintenance-scope','Maintenance in the real configuration','The equipment left running still needs its control supply.',reliability,'D14.3','Original topology: 5 MW duty; two operating 3 MW units plus a third 3 MW unit under maintenance. The chosen isolation either removes only C or also a shared 24 V control supply required by A and B. We evaluate scope, not a switching procedure.',{controls:[c('sharedControl','Approved isolation scope',[[false,'Unit C only'],[true,'C + shared control supply']])]}),
 s('configuration-mapping','Changed rack mappings','An old mapping can target the wrong row.',reliability,'D14.3','After a row reconfiguration, row B (B01–B20) is on branch C2; the old configuration maps C2 to row A (A01–A20). Verify as-built IDs, sensor points and action targets before restoring automatic control.',{controls:[c('mapping','Control mapping',[['old','Old revision'],['checked','Verified revision']])]}),
 s('return-to-service','Restore the operating state','Finishing the work is only the first return-to-service step.',reliability,'D14.3','Restoration closes the approved work record, verifies configuration and measured behavior, then removes the service restriction through the authorized process. Spare parts, staff, escalation and rollback must exist before work starts.'),
 s('common-cause','Correlated failures','Two paths can share one failure.',reliability,'D14.4','Both paths individually carry the full load. A local component fault affects only A. A flawed configuration deployed to both controllers disables A and B together. Multiplying individual failure probabilities requires independent failures and restoration; shared power, software, configuration or recovery staff can violate the model.',{controls:[c('commonCause','Failure',[[false,'Local component fault'],[true,'Shared configuration failure']])]}),
 s('replication-and-backup','Gmail: replicas and backups','A replica can copy the mistake, too',reliability,'D14.4','A replica can preserve availability after one device fails, but it can also receive a bad application write. A retained earlier valid version provides a different recovery path. In Gmail’s February 2011 incident, a storage software bug affected replicated copies; offline tape preserved data, and restoring it took hours.',{pedagogical_role:'case-study',controls:[c('replicaFault','What failed',[['device','One storage device'],['write','A bad application write']])],sources:['https://gmail.googleblog.com/2011/02/gmail-back-soon-for-everyone.html']}),
 s('london-recovery','Google London recovery','Cooling returned. Cloud recovery continued.',reliability,'D14.4','Google Cloud final July 29 2022 incident summary for europe-west2: July 19 10:05 PDT servers powered down, cooling repaired at 14:13, initial cloud-service restoration milestone July 20 04:28. That is 14 hours 15 minutes after cooling repair. Residual issues lasted longer. These are reported milestones, not uniform customer downtime. The mitigation routing change initially avoided all three zones rather than only the affected zone.',{pedagogical_role:'case-study',sources:['https://status.cloud.google.com/incidents/fmEL9i2fArADKawkZAa2']}),
 s('llama-recovery','Llama 3: automated recovery','Llama 3 kept training through 466 interruptions',reliability,'D14.4','Meta reports 466 interruptions in a 54-day Llama 3 training snapshot: 47 planned and 419 unexpected. About 78% of unexpected interruptions involved confirmed or suspected hardware issues. Automation handled all but three incidents requiring significant manual intervention; reduced startup and checkpoint overhead helped keep effective training time above 90%.',{pedagogical_role:'case-study',sources:['https://arxiv.org/html/2407.21783v3#S3.SS3.SSS4']}),
 s('overlap-outages','Overlapping incidents','Count the unavailable time once.',reliability,'D14.4','Two service-impact intervals last twelve and eighteen minutes with four overlapping. Their union is twenty-six minutes in a thirty-day, 43,200-minute observation period. Availability about 99.9398%. The time boundary and service condition stay fixed.'),
 s('causal-evidence','Find the cause','A preceding change is a lead, not a proven cause.',reliability,'D14.5','Configuration revision, controller event logs, branch pressure/flow and sensor quality support a causal account. Time order alone cannot prove the change caused reduced flow. Separate observations, hypotheses and missing evidence.',{controls:[c('incidentView','Incident record',[['observed','Observed'],['hypothesis','Hypothesis'],['verify','Verification']])]}),
 s('cloudflare-retest','Cloudflare tests the changes','A second facility failure tested the improvements.',reliability,'D14.5','After capacity expansion and failover changes, Cloudflare ran a facility cut test in February 2024. On March 26, a repeat facility power failure began at 14:58 UTC; APIs and dashboards operated normally by 15:05 without human intervention. Analytics recovered later that day. The seven-minute endpoint is not all-service or facility cold-start recovery.',{pedagogical_role:'case-study',sources:['https://blog.cloudflare.com/major-data-center-power-failure-again-cloudflare-code-orange-tested/']}),
 s('diagnosis-check','Chapter 14 diagnosis','Hot racks, a new job and a maintenance change. What next?',telemetry,'D14.1','Choose three discriminating evidence sets: current branch flow/temperatures, aligned row power/workload, and the current mapping/change record. A fresh remote plant average or the number of installed pumps cannot establish the local cause. Selecting evidence reveals supplied findings.',{pedagogical_role:'transfer'}),
 s('operating-decision','Chapter 14 operating decision','The cause is clearer. What releases the next workload?',reliability,'D14.5','Evidence shows unchanged electrical input, half branch flow, and old control mapping after maintenance. Restrict the new load under the approved policy while the team verifies the physical cause and restores the mapping. Release extra work only after current row-branch flow, temperatures and correct service are demonstrated. Do not infer that a configuration edit alone restored cooling.',{pedagogical_role:'transfer'}),
];
