import {deliverySchedule, modularSchedule, rackInterfaces, releaseHolds, acceptedPaths} from './procurement-model.js';
const arrow='<span class="p-arrow" aria-hidden="true">→</span>';
const card=(title,detail,cls='')=>`<section class="p-card ${cls}"><h2>${title}</h2><p>${detail}</p></section>`;
const flow=(items)=>`<div class="p-flow">${items.map((item,i)=>(i?arrow:'')+card(...item)).join('')}</div>`;
const note=text=>`<p class="p-condition">${text}</p>`;
const result=(value,label,cls='')=>`<div class="p-result ${cls}"><strong>${value}</strong><span>${label}</span></div>`;
const strip=text=>`<div class="p-strip">${text}</div>`;
const photo=(file,alt,credit,url)=>`<figure class="p-photo"><img src="../assets/references/${file}" alt="${alt}"><figcaption>${url?`<a href="${url}" target="_blank" rel="noreferrer">${credit}</a>`:credit}</figcaption></figure>`;
const rack=(large=false)=>`<span class="p-rack ${large?'large':''}" aria-hidden="true"><i></i><i></i><i></i><i></i></span>`;
const racks=(count,large=false)=>`<div class="p-rack-row" aria-hidden="true">${Array.from({length:count},()=>rack(large)).join('')}</div>`;
const decision=(ok,pass='Released',hold='Held')=>`<b class="p-decision ${ok?'pass':'hold'}">${ok?'✓':'○'} ${ok?pass:hold}</b>`;
const sourceCEI='https://www.cei.com/core-markets/modular';
const sourceCompass='https://www.siemens.com/en-us/company/insights/compass-datacenters-case-study/';

function lane(name, detail, segments, end, scale=36, critical=false) {
 return `<div class="p-lane ${critical?'critical':''}"><div class="p-lane-label"><b>${name}</b><span>${detail}</span></div><div class="p-track" style="--scale:${scale}" aria-label="${name}: ${detail}; complete week ${end}">${segments.map(([start,duration,label,color])=>`<span class="p-bar ${color||''}" style="left:${start/scale*100}%;width:${duration/scale*100}%" title="${label}: weeks ${start}–${start+duration}"><span>${label}</span></span>`).join('')}</div><b class="p-lane-end">${end}</b></div>`;
}
function axis(scale=36){return `<div class="p-axis"><span>Week</span><div>${[0,.25,.5,.75,1].map(r=>`<span>${Number((scale*r).toFixed(1))}</span>`).join('')}</div><span>Ready</span></div>`;}
function dependency(state, interactive=false) {
 const inputs={electricalProcurement:18,coolingProcurement:10,utilityReady:16};
 if(interactive){if(state.intervention==='cooling-fast')inputs.coolingProcurement=6;if(state.intervention==='electrical-fast')inputs.electricalProcurement=14;if(state.intervention==='cooling-late')inputs.coolingProcurement=18;if(state.intervention==='utility-late')inputs.utilityReady=30;}
 const m=deliverySchedule(inputs);
 return `<div class="p-stack"><div class="p-schedule">${axis(36)}${lane('Electrical',`Requirements 2 + buy ${inputs.electricalProcurement} + install 3`,[[0,2,'Req.','muted'],[2,inputs.electricalProcurement,'Procurement','power'],[2+inputs.electricalProcurement,3,'Fit','power']],m.electrical,36,m.critical.includes('electrical'))}${lane('Cooling',`Requirements 2 + buy ${inputs.coolingProcurement} + install 4`,[[0,2,'Req.','muted'],[2,inputs.coolingProcurement,'Procurement','water'],[2+inputs.coolingProcurement,4,'Fit','water']],m.cooling,36,m.critical.includes('cooling'))}${lane('Utility',`${inputs.utilityReady} weeks from start`,[[0,inputs.utilityReady,'Utility work','muted']],m.utility,36,m.critical.includes('utility'))}${lane('Acceptance',`4 weeks after every path is ready`,[[m.join,4,'Test','accept']],m.finish,36,true)}</div><div class="p-schedule-answer">${result(`Week ${m.finish}`,'Earliest accepted service')}<div><div class="p-equation">max(${m.electrical}, ${m.cooling}, ${m.utility}) + 4 = <b>${m.finish}</b></div><p>${interactive?(m.critical.includes('utility')?'Utility readiness now sets the testing start.':m.critical.includes('cooling')?'Cooling now sets the testing start.':`Cooling has ${m.slack.cooling} weeks before it delays testing.`):'The critical path includes design, procurement, installation and testing.'}</p></div></div></div>`;
}
function modularChart(m,factoryWeeks=6){
 const scale=20;
 return `<div class="p-schedule p-modular">${axis(scale)}${lane('Factory + travel',`${factoryWeeks} weeks assembly/checks + 1 transport`,[[m.factoryStart,factoryWeeks,'Factory','power'],[m.factoryFinish,1,'','muted']],m.arrival,scale)}${lane('Site',`8 weeks of independent work`,[[0,8,'Site enabling','water']],8,scale)}${lane('Connections','2 weeks after site + arrival',[[m.connectionStart,2,'','power']],m.connectionsFinish,scale)}${lane('Acceptance','2 weeks after connections',[[m.connectionsFinish,2,'','accept']],m.finish,scale,true)}</div>`;
}
function modular(state,late=false){
 const factoryWeeks=late?6:state.factoryWeeks;
 const m=modularSchedule({factoryWeeks,approvalWeek:late?state.approvalWeek:0,factorySlotWeek:late?state.factorySlotWeek:0});
 return `<div class="p-stack">${late?strip(`Interfaces approved: <b>week ${state.approvalWeek}</b> &nbsp; · &nbsp; Factory starts: <b>week ${m.factoryStart}</b>`):note('Week 0: approved interfaces + available components')}${modularChart(m,factoryWeeks)}<div class="p-route-results">${result(`Week ${m.finish}`,'Prefabricated route')}<div class="p-route-calculation"><span>max(${m.factoryStart} + ${factoryWeeks} + 1, 8) + 2 + 2</span><p>${late?`${m.arrivalFloat} week${m.arrivalFloat===1?'':'s'} of arrival float remains.`:(m.saving>0?`${m.saving} weeks earlier through overlap.`:m.saving===0?'Both routes finish together.':`${-m.saving} week later than site assembly.`)}</p></div>${result(`Week ${m.siteBuiltFinish}`,'Site-built route')}<div class="p-route-calculation"><span>${m.siteAssemblyStart} + 6 + 2</span><p>Site ready + assembly + acceptance</p></div></div></div>`;
}
const boundaries={
 electrical:{left:'Site electrical contractor',right:'Module electrical supplier',port:'Incoming terminals',fields:[['Duty','Voltage, current and failure load'],['Protection','Fault duty, settings and selectivity'],['Geometry','Terminations, cable route and access']],owner:'Electrical design lead'},
 coolant:{left:'Facility cooling contractor',right:'Module piping supplier',port:'Coolant flanges',fields:[['Duty','Temperatures, flow and pressure'],['Compatibility','Fluid specification and cleanliness'],['Geometry','Flange locations, isolation and access']],owner:'Mechanical design lead'},
 structure:{left:'Site structural contractor',right:'Module frame supplier',port:'Base and module joints',fields:[['Loads','Support reactions and anchorage'],['Geometry','Datums, dimensions and tolerances'],['Access','Placement and maintenance clearances']],owner:'Structural / layout lead'},
 controls:{left:'Site controls team',right:'Module controller supplier',port:'Control gateway',fields:[['Meaning','Units, timestamps and rack IDs'],['Authority','Who requests and enforces an action'],['Failure','Stale data and lost communication']],owner:'Controls design lead'},
};
function interfaceOwner(state){const b=boundaries[state.boundary];return `<div class="p-stack"><div class="p-boundary">${card(b.left,'Field connection')}<div class="p-port"><span>⇄</span><b>${b.port}</b></div>${card(b.right,'Internal assembly')}</div><div class="p-three">${b.fields.map(x=>card(...x)).join('')}</div>${strip(`<b>EPC interface manager</b> closes the joint · <b>${b.owner}</b> approves · both sides sign the same revision`)}</div>`;}
function meter(value,limit,max,unit){return `<div class="p-meter"><div class="p-meter-track"><span style="width:${value/max*100}%" class="${value>limit?'over':''}"></span><i style="left:${limit/max*100}%"></i></div><div class="p-meter-labels"><span>0</span><b style="left:${limit/max*100}%">${limit} ${unit} limit</b><span>${max}</span></div></div>`;}
function electrical(state){const m=rackInterfaces({rackKW:state.rackKW});return `<div class="p-stack"><div class="p-electrical-path">${card('480 V AC','Balanced three-phase · PF 1')}<span class="p-wire" aria-hidden="true"></span>${card('Existing branch','160 A allowable continuous',m.electricalPass?'':'warning')}<span class="p-wire" aria-hidden="true"></span><div class="p-rack-duty">${rack(true)}<b>${state.rackKW} kW</b></div></div><div class="p-two p-calculation"><section><div class="p-equation">I = ${state.rackKW.toLocaleString()} × 1,000 / (√3 × 480)</div>${meter(m.amps,160,300,'A')}</section><section class="p-readout">${result(`${m.amps.toFixed(1)} A`,'One path carries the full rack duty',m.electricalPass?'':'warning')}${decision(m.electricalPass,'Within old limit','Branch redesign required')}</section></div>${strip('Release: revised input + rated branch + protection/failure review + coordinated terminals')}</div>`;}
function hydraulic(state){const m=rackInterfaces({rackKW:state.rackKW});return `<div class="p-stack">${note('All IT heat enters water · cₚ = 4.18 kJ/(kg·K) · maximum temperature rise = 10 K')}<div class="p-two p-hydraulic"><section><h2>Flow through one rack branch</h2><div class="p-equation">${state.rackKW} / (4.18 × 10) = <b>${m.flow.toFixed(2)} kg/s</b></div>${meter(m.flow,3,6,'kg/s')}${decision(m.flowPass,'Within old flow limit','Above old flow limit')}</section><section><h2>Pressure across reused hardware</h2><div class="p-equation">20 × (${state.rackKW}/100)² = <b>${m.pressure.toFixed(0)} kPa</b></div>${meter(m.pressure,60,100,'kPa')}${decision(m.pressurePass,'Within available pressure','More pressure than available')}</section></div><div class="p-three p-total-flow">${result(`${m.racks} racks`,`${state.rackKW} kW each`)}${result(`${m.phaseFlow.toFixed(1)} kg/s`,'Total phase flow stays fixed')}${result('20 MW','IT heat stays fixed')}</div>${strip('Release: component and pump curves + balancing + rated connections at the revised duty')}</div>`;}
function approvals(state){const releases=releaseHolds(state);const rows=[['electrical','Electrical','Revised branch ratings + protection','electricalFabrication'],['hydraulic','Hydraulic','Flow/pressure curves + components','hydraulicFabrication'],['geometry','Geometry','Local loads + coordinates + access','frameFabrication'],['logistics','Logistics','Shipping envelope + route + placement','transportPlan'],['controls','Controls','Rack mappings + actions + test scope','configuration'],['resources','Resources','Factory slot + transport + test teams','scheduleCommitment']];return `<div class="p-stack"><div class="p-approval-grid">${rows.map(([key,label,evidence,release])=>`<button class="p-approval" data-evidence="${key}" aria-pressed="${state[key]}"><span class="p-check">${state[key]?'✓':'+'}</span><span><b>${label} evidence</b><small>${evidence}</small></span></button>`).join('')}</div><div class="p-release-grid">${[['Independent site',true],['Branch fabrication',releases.electricalFabrication],['Manifold fabrication',releases.hydraulicFabrication],['Frame fabrication',releases.frameFabrication],['Transport plan',releases.transportPlan],['Service date',releases.scheduleCommitment]].map(([label,ready])=>`<section><span>${label}</span>${decision(ready,'Can proceed','Held')}</section>`).join('')}</div>${note('Fabrication needs coordinated geometry. Shipment also needs factory release. Service still needs integrated acceptance.')}</div>`;}
const testCases={
 normal:{start:'Ten 2 MW zones at the declared rack duty',measure:'Rack input power, coolant flow/temperatures and application output',pass:'Every declared rack stays in its agreed envelope; required work completes',stop:'Any project temperature, pressure or electrical stop limit is reached'},
 failure:{start:'One specified cooling path unavailable',measure:'Affected rack IDs, fault timestamps, measured power and temperatures',pass:'The intended racks reach the required safe load within the allowed response time',stop:'A required action fails or any stop limit is approached'},
 maintenance:{start:'One agreed service path isolated for maintenance',measure:'Surviving current, branch flow and the workload result',pass:'Surviving paths support the declared duty; isolation boundaries remain correct',stop:'A surviving path exceeds its approved limit'},
 recovery:{start:'Failed path restored under the approved sequence',measure:'State transitions, temperatures, alarms and correct new output',pass:'Required service resumes with the tested configuration and cleared issues',stop:'Unstable transfer, stale state or repeated protective action'},
};
function integrated(state){const t=testCases[state.test];return `<div class="p-stack"><div class="p-test-start"><span>Starting configuration</span><b>${t.start}</b></div><div class="p-three p-test-evidence">${card('Measure',t.measure)}${card('Accept when',t.pass,'positive')}${card('Stop when',t.stop,'warning')}</div>${strip('Before the test: agree numerical limits, measurement locations, duration, authority and evidence record')}${note('Test loads establish facility behavior. Application checks establish the required computing service.')}</div>`;}
function accepted(state){const m=acceptedPaths({coolingStart:state.coolingStart});const row=(label,start,end,cls)=>`<div class="p-acceptance-lane"><b>${label}</b><div>${[1,21,41,61,81].map(from=>`<span class="${from>=start&&from+19<=end?cls:''}">${String(from).padStart(2,'0')}–${String(from+19).padStart(2,'0')}</span>`).join('')}</div></div>`;return `<div class="p-stack"><div class="p-acceptance-map">${row('Electrical',1,80,'power')}${row('Cooling',state.coolingStart,100,'water')}${row('Network',1,60,'network')}${row('All three',state.coolingStart,60,'complete')}</div><div class="p-schedule-answer">${result(`${m.count} racks`,m.count===40?'A21–A60':'A01–A60')}<div><div class="p-equation">${m.count} × 100 kW = <b>${m.envelopeMW} MW</b></div><p>Accepted envelope for these rack identities.</p></div></div>${note('Separate 100-position exercise · 100 kW per rack · all other acceptance criteria met')}${strip(m.count===40?'min(80, 80, 60) = 60 misses that the records cover different racks.':'New cooling evidence completes A01–A20. A61–A100 still lack network evidence.')}</div>`;}
function diagnosis(state){const responses={all:'The missing geometry can still invalidate frames, connections and supports. Approved current and flow alone cannot release them.',independent:'Yes. Continue approved independent site work. Release other packages only where their boundaries are independent; hold affected frames, joints, shipment and dates until the missing evidence closes.',stop:'Hold affected packages, but the approved independent site work can continue. Stopping it discards useful overlap.'};return `<div class="p-diagnosis"><section class="p-evidence"><h2>200 × 100 kW → 100 × 200 kW</h2><div>${decision(true,'Electrical design approved')}<p>Revised normal and failure duties</p></div><div>${decision(true,'Hydraulic design approved')}<p>Revised flow and pressure</p></div><div>${decision(false,'','Missing evidence')}<p>Geometry · transport plan · factory slot</p></div></section><section class="p-answer"><div class="p-answer-options">${[['all','Release all fabrication: total MW is unchanged.'],['independent','Continue independent work; hold the affected interfaces.'],['stop','Stop all site and factory work.']].map(([value,label])=>`<button data-diagnosis="${value}" aria-pressed="${state.diagnosis===value}">${label}</button>`).join('')}</div><button id="diagnosis-reveal" class="p-reveal" ${state.diagnosis?'':'disabled'} aria-expanded="${state.showDiagnosis}">${state.showDiagnosis?'Hide reasoning':'Check the decision'}</button><p class="p-feedback" role="status">${state.showDiagnosis?responses[state.diagnosis]:''}</p></section></div>`;}

export function procurementVisual(id,state){
 switch(id){
 case 'delivery-purpose':return `<div class="p-opener"><div class="p-opener-route"><section><div class="p-drawing" aria-hidden="true"><i></i><i></i><i></i></div><h2>Design</h2><p>Define the interfaces</p></section>${arrow}<section><div class="p-module-icon" aria-hidden="true"><i></i><i></i><i></i></div><h2>Delivery</h2><p>Join factory and site work</p></section>${arrow}<section><div class="p-service-icon" aria-hidden="true">✓</div><h2>Acceptance</h2><p>Demonstrate the complete path</p></section></div></div>`;
 case 'service-requirements':return `<div class="p-stack">${strip('<b>20 MW IT phase</b> · ten 2 MW zones · power, cooling and information reach the same racks')}${flow([['Owner requirements','What service must work, and in which conditions?'],['Design basis','Which paths, ratings and controls provide it?'],['Acceptance evidence','Which measured results demonstrate it?']])}<div class="p-requirement-example"><span>“Provide sufficient cooling”</span>${arrow}<strong>Declared rack heat + inlet conditions + allowable temperatures + measured response</strong></div></div>`;
 case 'delivery-paths':return dependency(state);
 case 'critical-path':return dependency(state,true);
 case 'epc-and-prefab':return `<div class="p-stack"><div class="p-epc"><h2>EPC · Engineering, procurement and construction</h2><div><span>Coordinate the design</span><span>Purchase equipment</span><span>Deliver and integrate</span></div></div><div class="p-strategy-label">The same delivery responsibility can use either route</div><div class="p-two">${card('Site-built services','Install factory-made components; assemble distribution and piping in the building.')}${card('Prefabricated services','Assemble components into modules off-site; connect and integrate them at the building.')}</div>${note('The EPC contract assigns the responsibilities.')}</div>`;
 case 'factory-and-site':return `<div class="p-stack"><div class="p-scope-columns"><section><h2>Factory</h2><div class="p-frame"><span>Electrical distribution</span><span>Coolant manifolds</span><span>Internal wiring + controls</span></div><p>Assemble and test the module</p></section><span class="p-arrow" aria-hidden="true">⇄</span><section><h2>Site</h2><div class="p-site-scope"><span>Access + foundations</span><span>Utility + cooling plant</span><span>Placement + field joints</span><span>IT racks + integrated tests</span></div><p>Build and accept the joined system</p></section></div>${strip('Factories make components in both routes. Prefabrication changes where those components are assembled.')}</div>`;
 case 'aws-houdini-prefab':return `<div class="p-case">${photo('cei-modular-factory-edgerton.jpg','Cupertino Electric’s Edgerton factory with electrical equipment and modular infrastructure assemblies.','Cupertino Electric’s modular factory · Edgerton, Wisconsin',sourceCEI)}<div class="p-case-copy"><h2>AWS prefabricated data-hall skids</h2><p>SemiAnalysis identifies Cupertino Electric as a partner.</p><div class="p-parallel-pair"><section><b>Factory</b><span>Assemble + test</span></section><section><b>Site</b><span>Prepare + connect</span></section></div><p class="p-photo-scope">Photo: CEI’s factory; the equipment is not identified as a Houdini unit.</p><p class="p-credit"><a href="https://newsletter.semianalysis.com/p/the-wild-wild-west-of-lego-datacenters" target="_blank" rel="noreferrer">SemiAnalysis · July 29, 2026</a></p></div></div>`;
 case 'parallel-schedules':return modular(state);
 case 'manufacturing-release':return `<div class="p-stack"><div class="p-release-chain">${card('Approved interface','Ratings · dimensions · signals')}<div class="p-gate"><b>Release</b><span>Revision + owner</span></div>${card('Fabrication','Cut · drill · assemble')}</div><div class="p-three p-revision-fields">${card('What freezes?','The inputs this package consumes.')}${card('What may continue?','Separately released, independent work.')}${card('What still needs booking?','Components, factory slot and logistics.')}</div>${strip('An unresolved connector location can stop a frame before the site is ready.')}</div>`;
 case 'module-transport':return `<div class="p-stack"><div class="p-transport-route"><div class="p-shipping-module"><div class="p-module-icon"><i></i><i></i><i></i></div><b>As-shipped module</b><span>Envelope · mass · center of gravity</span></div>${arrow}${card('Route','Clearances · loads · permits')}${arrow}${card('Placement','Lift · access · sequence')}</div><div class="p-two">${card('Before shipment','Protect connections and record the factory configuration.')}${card('At receipt','Inspect transport condition and verify the installation revision.')}</div>${note('Here, IT racks are installed on site. Installed rack mass and shipping payload are separate inputs.')}</div>`;
 case 'compass-package':return `<div class="p-case">${photo('distribution-compass-switchgear.jpg','Factory photograph of Siemens medium-voltage switchgear for the Compass skid; transformer is outside the view.','Siemens × Compass · switchgear portion of the skid',sourceCompass)}<div class="p-case-copy"><h2>Switchgear + transformer</h2><p>Co-developed as a prefabricated medium-voltage package.</p><div class="p-interface-list"><div><b>Factory boundary</b><span>Internal assembly and agreed checks</span></div><div><b>Site boundary</b><span>Cables, supports, placement and controls</span></div><div><b>The handoff</b><span>Who approves both sides of each joint?</span></div></div></div></div>`;
 case 'interface-owner':return interfaceOwner(state);
 case 'rack-change':return `<div class="p-stack">${strip('<b>10 zones × 2 MW = 20 MW IT</b> · changed just before fabrication')}<div class="p-two p-rack-comparison"><section><h2>One zone before</h2>${racks(20)}${result('20 × 100 kW','200 racks across the phase')}</section><section><h2>One zone after</h2>${racks(10,true)}${result('10 × 200 kW','100 racks across the phase')}</section></div><div class="p-interface-tags"><span>Current per branch</span><span>Flow + pressure</span><span>Local supports</span><span>Connection geometry</span></div>${note('The IT duty is fixed. Changes in pumps, losses and other auxiliary loads need a separate check.')}</div>`;
 case 'electrical-interface':return electrical(state);
 case 'hydraulic-interface':return hydraulic(state);
 case 'spatial-interface':return `<div class="p-stack">${note('Vendor drawing: new rack has twice the mass, on the same four feet · equal static sharing')}<div class="p-two p-supports"><section><h2>20 racks · mass M each</h2><div class="p-supported-rack">${rack(true)}<div class="p-feet"><span>¼ M</span><span>¼ M</span><span>¼ M</span><span>¼ M</span></div></div>${result('20 M','Total zone mass')}</section><section><h2>10 racks · mass 2M each</h2><div class="p-supported-rack heavy">${rack(true)}<div class="p-feet"><span>½ M</span><span>½ M</span><span>½ M</span><span>½ M</span></div></div>${result('20 M','Same total; twice the mass on each foot')}</section></div>${strip('Release: local support reactions + anchorage + coordinated connectors + service and replacement access')}</div>`;
 case 'release-holds':return approvals(state);
 case 'approval-delay':return modular(state,true);
 case 'controls-interface':return `<div class="p-stack">${flow([['Cooling fault','Sensor + affected rack ID'],['Authorized command','Correct rack group + defined action'],[state.action==='confirmed'?'Response measured':'No response confirmed',state.action==='confirmed'?'Power and temperature meet the agreed response':'A request has not established protection',state.action==='confirmed'?'positive':'warning']])}<div class="p-controls-return"><span>${state.action==='confirmed'?'← Observed outcome closes the path':'← Missing evidence leaves the path open'}</span></div><div class="p-three">${card('Meaning','Measured or commanded? Units and timestamps?')}${card('Mapping','Which new rack does this old circuit name reach?')}${card('Failure','What happens if the target is unreachable?')}</div></div>`;
 case 'factory-acceptance':return `<div class="p-stack"><div class="p-fat-boundary"><section class="p-tested"><span class="p-overline">Factory acceptance test · FAT</span><h2>The assembled module</h2><div class="p-frame"><span>Internal electrical checks</span><span>Piping / fluid checks</span><span>Controls in the test setup</span></div><b>Record scope, conditions and results</b></section><section class="p-site-unproven"><h2>Still to join on site</h2><div class="p-site-scope"><span>Incoming cables</span><span>Field coolant joints</span><span>Site controls + actual racks</span></div><b>Verify the completed service path</b></section></div>${strip('A shipment release does not establish integrated service acceptance.')}</div>`;
 case 'site-checks':return `<div class="p-stack"><div class="p-three p-site-checks">${card('Electrical','Asset and circuit IDs<br>Connections and installation records<br>Protection settings')} ${card('Cooling','Fluid specification and cleanliness<br>Leak / pressure integrity<br>Measured flow at each branch')} ${card('Controls','Sensor identity and units<br>Point-to-point commands<br>Rack and action mapping')}</div><div class="p-check-sequence"><span>Received</span>${arrow}<span>Installed</span>${arrow}<span>Pre-functional checks</span>${arrow}<span>Subsystem functions</span></div></div>`;
 case 'integrated-tests':return integrated(state);
 case 'accepted-paths':return accepted(state);
 case 'phase-boundary':return `<div class="p-stack"><div class="p-shared-plant">Shared upstream plant + controls</div><div class="p-phase-links" aria-hidden="true"><span>↓</span><span>↓</span></div><div class="p-two">${card('Phase A · operating','Preserve its accepted service and configuration.','positive')}${card('Phase B · construction','Check the shared capacity, settings and new connections.','warning')}</div><div class="p-phase-gate"><b>Before the connection</b><span>Agree isolation ownership</span><span>Review changed failure paths</span><span>Retest affected shared functions</span></div></div>`;
 case 'handover-records':return `<div class="p-stack"><div class="p-handover"><section class="p-record"><span>Accepted phase</span><h2>Configuration revision 7</h2><div>Named assets + topology</div><div>Protection + controls versions</div><div>Tests + limits + issue dispositions</div></section>${arrow}<section><h2>Operating team</h2><div class="p-interface-list"><div><b>Operate</b><span>Procedures and limits match the records</span></div><div><b>Maintain</b><span>Named responsibilities and trained people</span></div><div><b>Change</b><span>Trace each revision to the affected tests</span></div></div></section></div>${strip('Every unresolved issue names the affected path, operating limitation and decision owner.')}</div>`;
 case 'release-decision':return diagnosis(state);
 default:throw new Error(`Unknown procurement scene: ${id}`);
 }
}
