import {procurementCommissioningVisual} from './procurement-commissioning.js';
import {deliverySchedule, modularSchedule, rackInterfaces, releaseHolds} from './procurement-model.js';
const arrow='<span class="p-arrow" aria-hidden="true">→</span>';
const card=(title,detail,cls='')=>`<section class="p-card ${cls}"><h2>${title}</h2><p>${detail}</p></section>`;
const flow=(items)=>`<div class="p-flow">${items.map((item,i)=>(i?arrow:'')+card(...item)).join('')}</div>`;
const note=text=>`<p class="p-condition">${text}</p>`;
const result=(value,label,cls='')=>`<div class="p-result ${cls}"><strong>${value}</strong><span>${label}</span></div>`;
const strip=text=>`<div class="p-strip">${text}</div>`;
const photo=(file,alt,credit,url)=>`<figure class="p-photo"><img src="../assets/references/${file}" alt="${alt}"><figcaption>${url?`<a href="${url}" target="_blank" rel="noreferrer">${credit}</a>`:credit}</figcaption></figure>`;
const rack=(large=false)=>`<span class="p-rack ${large?'large':''}" aria-hidden="true"><i></i><i></i><i></i><i></i></span>`;
const racks=(count,large=false)=>`<div class="p-rack-row" aria-hidden="true">${Array.from({length:count},()=>rack(large)).join('')}</div>`;
const decision=(ok,pass='Released',hold='Held')=>`<b class="p-decision ${ok?'pass':'hold'}">${ok?'✓':'○'} ${ok?pass:hold}</b>`;
const sourceCEI='https://www.cei.com/core-markets/modular';
const sourceCompass='https://www.siemens.com/en-us/company/insights/compass-datacenters-case-study/';

function lane(name, detail, segments, end, scale=36, critical=false) {
 return `<div class="p-lane ${critical?'critical':''}"><div class="p-lane-label"><b>${name}</b><span>${detail}</span></div><div class="p-track" style="--scale:${scale}" aria-label="${name}: ${detail}; complete week ${end}">${segments.map(([start,duration,label,color])=>`<span class="p-bar ${color||''}" style="left:${start/scale*100}%;width:${duration/scale*100}%" title="${label}: weeks ${start}–${start+duration}"><span>${label}</span></span>`).join('')}</div><b class="p-lane-end">${end}</b></div>`;
}
function axis(scale=36){return `<div class="p-axis"><span>Week</span><div>${[0,.25,.5,.75,1].map(r=>`<span>${Number((scale*r).toFixed(1))}</span>`).join('')}</div><span>Ready</span></div>`;}
function dependency(state, interactive=false) {
 const inputs={electricalProcurement:18,coolingProcurement:10,utilityReady:16};
 if(interactive){if(state.intervention==='cooling-fast')inputs.coolingProcurement=6;if(state.intervention==='electrical-fast')inputs.electricalProcurement=14;if(state.intervention==='cooling-late')inputs.coolingProcurement=18;if(state.intervention==='utility-late')inputs.utilityReady=30;}
 const m=deliverySchedule(inputs);
 return `<div class="p-stack">${note("Whole-project example: week 0 starts requirements and procurement") }<div class="p-schedule">${axis(36)}${lane('Electrical',`Requirements 2 + buy ${inputs.electricalProcurement} + install 3`,[[0,2,'Req.','muted'],[2,inputs.electricalProcurement,'Procurement','power'],[2+inputs.electricalProcurement,3,'Fit','power']],m.electrical,36,m.critical.includes('electrical'))}${lane('Cooling',`Requirements 2 + buy ${inputs.coolingProcurement} + install 4`,[[0,2,'Req.','muted'],[2,inputs.coolingProcurement,'Procurement','water'],[2+inputs.coolingProcurement,4,'Fit','water']],m.cooling,36,m.critical.includes('cooling'))}${lane('Utility',`${inputs.utilityReady} weeks from start`,[[0,inputs.utilityReady,'Utility work','muted']],m.utility,36,m.critical.includes('utility'))}${lane('Acceptance',`4 weeks after every path is ready`,[[m.join,4,'Test','accept']],m.finish,36,true)}</div><div class="p-schedule-answer">${result(`Week ${m.finish}`,'Earliest accepted service')}<div><h2>${m.critical.map(key=>({electrical:"Electrical",cooling:"Cooling",utility:"Utility"})[key]).join(" and ")} sets the testing start</h2><p>${interactive?(m.critical.includes('utility')?'Utility readiness now sets the testing start.':m.critical.includes('cooling')?'Cooling now sets the testing start.':`Cooling can arrive ${m.slack.cooling} weeks later before it delays testing.`):'The critical path includes design, procurement, installation and testing.'}</p></div></div></div>`;
}
function modularChart(m,factoryWeeks=6){
 const scale=20;
 return `<div class="p-schedule p-modular">${axis(scale)}${lane('Factory + travel',`${factoryWeeks} weeks assembly/checks + 1 transport`,[[m.factoryStart,factoryWeeks,'Factory','power'],[m.factoryFinish,1,'','muted']],m.arrival,scale)}${lane('Site',`8 weeks of independent work`,[[0,8,'Site enabling','water']],8,scale)}${lane('Connections','2 weeks after site + arrival',[[m.connectionStart,2,'','power']],m.connectionsFinish,scale)}${lane('Acceptance','2 weeks after connections',[[m.connectionsFinish,2,'','accept']],m.finish,scale,true)}</div>`;
}
function modular(state,late=false){
 const factoryWeeks=late?6:state.factoryWeeks;
 const m=modularSchedule({factoryWeeks,approvalWeek:late?state.approvalWeek:0,factorySlotWeek:late?state.factorySlotWeek:0});
 const timing=m.arrivalFloat>0?`The module can arrive ${m.arrivalFloat} week later before the site must wait.`:m.arrival>8?`The prepared site waits ${m.arrival-8} weeks for the module.`:'The module arrives just as the site is ready.';
 return `<div class="p-stack">${note(late?'Same factory/site example. Components are available.':'Factory/site example: restart the clock with approved drawings and available components.')}${late?strip(`Drawing approved in week <b>${state.approvalWeek}</b>. Factory starts in week <b>${m.factoryStart}</b>.`):''}${modularChart(m,factoryWeeks)}<div class="p-route-results p-route-simple">${result(`Week ${m.finish}`,'Factory assembly')}${result(`Week ${m.siteBuiltFinish}`,'Assembly after site preparation')}<div class="p-route-calculation"><span>${m.saving>0?`${m.saving} weeks saved by overlapping work`:m.saving===0?'Both routes finish together':`Factory route finishes ${-m.saving} week${m.saving===-1?'':'s'} later`}</span><p>${timing}</p></div></div></div>`;
}
const boundaries={
 electrical:{left:'Site electrical contractor',right:'Module electrical supplier',port:'Incoming terminals',fields:[['Duty','Voltage, current and failure load'],['Protection','Fault duty, settings and selectivity'],['Geometry','Terminations, cable route and access']],owner:'Electrical design lead'},
 coolant:{left:'Facility cooling contractor',right:'Module piping supplier',port:'Coolant flanges',fields:[['Match the duty','Same fluid, temperature, flow and pressure'],['Match the connection','Same flange and the same location'],['Verify the joint','Access for installation, isolation and service']],owner:'Mechanical design lead'},
 structure:{left:'Site structural contractor',right:'Module frame supplier',port:'Base and module joints',fields:[['Loads','Support reactions and anchorage'],['Geometry','Datums, dimensions and tolerances'],['Access','Placement and maintenance clearances']],owner:'Structural / layout lead'},
 controls:{left:'Site controls team',right:'Module controller supplier',port:'Control gateway',fields:[['Meaning','Units, timestamps and rack IDs'],['Authority','Who requests and enforces an action'],['Failure','Stale data and lost communication']],owner:'Controls design lead'},
};
function interfaceOwner(state){const b=boundaries[state.boundary];return `<div class="p-stack"><div class="p-boundary">${card(b.left,'Builds the site side')}<div class="p-port"><span>⇄</span><b>${b.port}</b></div>${card(b.right,'Builds the module side')}</div><div class="p-three">${b.fields.map(x=>card(...x)).join('')}</div>${strip(`The <b>EPC interface manager</b> brings both sides onto one drawing. The <b>${b.owner.toLowerCase()}</b> approves the design.`)}${note('These are assigned roles in the teaching example. Actual contracts name the responsible parties.')}</div>`;}

function meter(value,limit,max,unit){return `<div class="p-meter"><div class="p-meter-track"><span style="width:${value/max*100}%" class="${value>limit?'over':''}"></span><i style="left:${limit/max*100}%"></i></div><div class="p-meter-labels"><span>0</span><b style="left:${limit/max*100}%">${limit} ${unit} limit</b><span>${max}</span></div></div>`;}
function electrical(){
 const before=rackInterfaces({rackKW:100}),after=rackInterfaces({rackKW:200});
 return `<div class="p-stack">${note('Same 480 V three-phase supply and power factor 1. One branch carries the full rack load.')}<div class="p-two p-compare">${[[before,'Before'],[after,'After']].map(([m,label])=>`<section><h2>${label}: ${m.rackKW} kW per rack</h2><div class="p-branch-load">${rack(true)}${result(`${Math.round(m.amps)} A`,'Current through one branch',m.electricalPass?'':'warning')}</div>${meter(m.amps,160,300,'A')}${decision(m.electricalPass,'Fits the existing branch','Exceeds the existing branch')}</section>`).join('')}</div>${strip('The old 160 A branch cannot carry the new rack. Its cable, terminals and protection need review.')}</div>`;
}
function hydraulic(){
 const before=rackInterfaces({rackKW:100}),after=rackInterfaces({rackKW:200});
 return `<div class="p-stack">${note('Same water temperature rise of 10°C. All rack heat enters the water.')}<div class="p-two p-compare"><section><h2>Flow through one branch</h2><div class="p-compare-values"><span>Before <b>${before.flow.toFixed(1)} kg/s</b></span><span>After <b>${after.flow.toFixed(1)} kg/s</b></span></div>${meter(after.flow,3,6,'kg/s')}<p>Twice the heat needs twice the water flow.</p></section><section><h2>Pressure needed by the same hardware</h2><div class="p-compare-values"><span>Before <b>${before.pressure} kPa</b></span><span>After <b>${after.pressure} kPa</b></span></div>${meter(after.pressure,60,100,'kPa')}<p>In this example, twice the flow needs four times the pressure drop.</p></section></div>${strip('The plant moves the same total flow, but each rack connection must carry more.')}${note('The pressure example assumes the same hardware with quadratic resistance. Real redesigns need pump and component curves.')}</div>`;
}
function approvals(state){const releases=releaseHolds(state);const rows=[['electrical','Electrical','Revised branch ratings + protection','electricalFabrication'],['hydraulic','Hydraulic','Flow/pressure curves + components','hydraulicFabrication'],['geometry','Geometry','Local loads + coordinates + access','frameFabrication'],['logistics','Logistics','Shipping envelope + route + placement','transportPlan'],['controls','Controls','Rack mappings + actions + test scope','configuration'],['resources','Resources','Factory slot + transport + test teams','scheduleCommitment']];return `<div class="p-stack"><div class="p-approval-grid">${rows.map(([key,label,evidence,release])=>`<button class="p-approval" data-evidence="${key}" aria-pressed="${state[key]}"><span class="p-check">${state[key]?'✓':'+'}</span><span><b>${state[key]?`${label} approved`:`Approve ${label.toLowerCase()}`}</b><small>${evidence}</small></span></button>`).join('')}</div><div class="p-release-grid">${[['Independent site',true],['Branch fabrication',releases.electricalFabrication],['Manifold fabrication',releases.hydraulicFabrication],['Frame fabrication',releases.frameFabrication],['Transport plan',releases.transportPlan],['Control configuration',releases.configuration],['Schedule commitment',releases.scheduleCommitment]].map(([label,ready])=>`<section><span>${label}</span>${decision(ready,'Can proceed','Held')}</section>`).join('')}</div>${note('Connection positions must match before drilling or fabrication. A booked date still requires successful service tests.')}</div>`;}
export function procurementVisual(id,state){
 const commissioning=procurementCommissioningVisual(id,state);
 if(commissioning!==null)return commissioning;
 switch(id){
 case 'hardware-prices-meme':return `<figure class="procurement-meme"><img src="../assets/references/storage-hardware-prices-meme.png" alt="Grim Reaper AI meme: RAM, GPU and SSD prices rise, with CPU prices next."></figure>`;
 case 'delivery-purpose':return `<div class="p-opener"><div class="p-opener-route"><section><div class="p-drawing" aria-hidden="true"><i></i><i></i><i></i></div><h2>Design</h2><p>Define the interfaces</p></section>${arrow}<section><div class="p-module-icon" aria-hidden="true"><i></i><i></i><i></i></div><h2>Delivery</h2><p>Join factory and site work</p></section>${arrow}<section><div class="p-service-icon" aria-hidden="true">✓</div><h2>Acceptance</h2><p>Demonstrate the complete path</p></section></div></div>`;
 case 'service-requirements':return `<div class="p-stack"><div class="p-requirement-story"><h2>One revised rack: 200 kW</h2><p>Power and cooling support its normal workload.</p><p>If its cooling path fails, the correct rack reaches the agreed safe load in time.</p></div>${flow([['Specify','Agree the load, response time and operating limits.'],['Design','Connect the power, cooling and controls to that rack.'],['Prove','Measure the rack response against those limits.']])}${note('Plan these tests during design. The owner’s requirements define the pass criteria.')}</div>`;
 case 'critical-path':return dependency(state,true);
 case 'epc-and-prefab':return `<div class="p-stack"><div class="p-epc"><h2>EPC · Engineering, procurement and construction</h2><div><span>Coordinate the design</span><span>Purchase equipment</span><span>Deliver and integrate</span></div></div><div class="p-strategy-label">The same delivery responsibility can use either route</div><div class="p-two">${card('Site-built services','Install factory-made components; assemble distribution and piping in the building.')}${card('Prefabricated services','Assemble components into modules off-site; connect and integrate them at the building.')}</div>${note('The EPC contract assigns the responsibilities.')}</div>`;
 case 'factory-and-site':return `<div class="p-stack"><div class="p-scope-columns"><section><h2>Factory</h2><div class="p-frame"><span>Electrical distribution</span><span>Coolant manifolds</span><span>Internal wiring + controls</span></div><p>Assemble and test the module</p></section><span class="p-arrow" aria-hidden="true">⇄</span><section><h2>Site</h2><div class="p-site-scope"><span>Access + foundations</span><span>Utility + cooling plant</span><span>Placement + field joints</span><span>IT racks + integrated tests</span></div><p>Build and accept the joined system</p></section></div>${strip('Factories make components in both routes. Prefabrication changes where those components are assembled.')}</div>`;
 case 'aws-houdini-prefab':return `<div class="p-case">${photo('cei-modular-factory-edgerton.jpg','Cupertino Electric’s Edgerton factory with electrical equipment and modular infrastructure assemblies.','Cupertino Electric’s modular factory · Edgerton, Wisconsin',sourceCEI)}<div class="p-case-copy"><h2>AWS prefabricated data-hall skids</h2><p>SemiAnalysis identifies Cupertino Electric as a partner.</p><div class="p-parallel-pair"><section><b>Factory</b><span>Assemble + test</span></section><section><b>Site</b><span>Prepare + connect</span></section></div><p class="p-photo-scope">Photo: CEI’s factory; the equipment is not identified as a Houdini unit.</p><p class="p-credit"><a href="https://newsletter.semianalysis.com/p/the-wild-wild-west-of-lego-datacenters" target="_blank" rel="noreferrer">SemiAnalysis · July 29, 2026</a></p></div></div>`;
 case 'parallel-schedules':return modular(state);
 case 'manufacturing-release':return `<div class="p-stack"><div class="p-two p-connection-example"><section><h2>Drawing still changing</h2><div class="p-flange-demo misaligned" role="img" aria-label="Site pipe and module inlet do not line up"><span>Site pipe</span><i></i><i></i><span>Module inlet</span></div><p>Moving the inlet later can mean new holes, piping or supports.</p></section><section><h2>Both sides approve one drawing</h2><div class="p-flange-demo" role="img" aria-label="Site pipe and module inlet align"><span>Site pipe</span><i></i><i></i><span>Module inlet</span></div><p>The factory can build the agreed connection.</p></section></div>${strip('Freeze the dimensions and ratings used by this package. Independent site work can continue.')}${note('Drawing approval does not reserve a factory slot. Signals and drawing revisions also belong in the release.')}</div>`;
 case 'module-transport':return `<div class="p-stack"><div class="p-transport-route"><div class="p-shipping-module"><div class="p-module-icon"><i></i><i></i><i></i></div><b>As-shipped module</b><span>Envelope · mass · center of gravity</span></div>${arrow}${card('Route','Clearances · loads · permits')}${arrow}${card('Placement','Lift · access · sequence')}</div><div class="p-two">${card('Before shipment','Protect connections and record the factory configuration.')}${card('At receipt','Inspect transport condition and verify the installation revision.')}</div>${note('Here, IT racks are installed on site. Installed rack mass and shipping payload are separate inputs.')}</div>`;
 case 'compass-package':return `<div class="p-case">${photo('distribution-compass-switchgear.jpg','Factory photograph of Siemens medium-voltage switchgear for the Compass skid; transformer is outside the view.','Siemens × Compass · switchgear portion of the skid',sourceCompass)}<div class="p-case-copy"><h2>Switchgear + transformer</h2><p>Co-developed as a prefabricated medium-voltage package.</p><div class="p-interface-list"><div><b>Factory boundary</b><span>Internal assembly and agreed checks</span></div><div><b>Site boundary</b><span>Cables, supports, placement and controls</span></div><div><b>The handoff</b><span>Who approves both sides of each joint?</span></div></div></div></div>`;
 case 'interface-owner':return interfaceOwner(state);
 case 'rack-change':return `<div class="p-stack">${strip('<b>10 zones × 2 MW = 20 MW IT</b> · changed just before fabrication')}<div class="p-two p-rack-comparison"><section><h2>One zone before</h2>${racks(20)}${result('20 × 100 kW','200 racks across the phase')}</section><section><h2>One zone after</h2>${racks(10,true)}${result('10 × 200 kW','100 racks across the phase')}</section></div><div class="p-interface-tags"><span>Current per branch</span><span>Flow + pressure</span><span>Local supports</span><span>Connection geometry</span></div>${note('The IT duty is fixed. Changes in pumps, losses and other auxiliary loads need a separate check.')}</div>`;
 case 'electrical-interface':return electrical(state);
 case 'hydraulic-interface':return hydraulic(state);
 case 'spatial-interface':return `<div class="p-stack">${note('Vendor drawing: each new rack has twice the mass on the same four feet. Assume equal static sharing.')}<div class="p-two p-supports"><section><h2>Before: 20 racks in one zone</h2><div class="p-supported-rack">${rack(true)}<div class="p-feet">${Array.from({length:4},()=>'<span class="p-load-blocks"><i></i></span>').join('')}</div></div>${result('One load per foot','Reference load for the original rack')}</section><section><h2>After: 10 heavier racks</h2><div class="p-supported-rack heavy">${rack(true)}<div class="p-feet">${Array.from({length:4},()=>'<span class="p-load-blocks"><i></i><i></i></span>').join('')}</div></div>${result('Twice the load per foot','The zone’s total weight stays the same')}</section></div>${strip('The floor and supports must carry the load where each foot actually lands.')}</div>`;
 case 'release-holds':return approvals(state);
 case 'approval-delay':return modular(state,true);
 default:throw new Error(`Unknown procurement scene: ${id}`);
 }
}
