const photo = (name, alt, credit, contain = false) => `<figure class="case-photo${contain ? " case-contain" : ""}"><img src="../assets/references/${name}" alt="${alt}"><figcaption>${credit}</figcaption></figure>`;
const result = (markup, description) => ({ markup, description, format: "html" });
const svg = (label, body, view = "0 0 720 350") => `<svg class="case-diagram" viewBox="${view}" role="img" aria-label="${label}">${body}</svg>`;

export function renderSiteCase(id, state = {}) {
  if (id === "mineral-project") return result(
    `<div class="case-status"><div class="case-heading"><h2>Texas Critical Data Centers</h2><p>New Era · Odessa area, Texas · 14 August 2026</p></div><div class="case-status-pair"><article><b>493 acres</b><h3>Development land secured</h3><p>The campus parcel and corridor had been assembled.</p></article><article><b>1 operator</b><h3>Surface waiver still pending</h3><p>An existing leaseholder’s surface rights remained to be resolved.</p></article></div><div class="case-takeaway">Resolve the rights to use the surface before fixing the layout.</div></div>`,
    "New Era's August 14, 2026 update reported all 493 acres secured for Texas Critical Data Centers and a final surface waiver still pending from one leasehold operator. Land assembly and surface-use agreements were separate milestones; the release establishes no quantified mineral-caused delay."
  );
  if (id === "mineral-accommodation") return result(
    `<div class="case-law"><div class="case-heading"><h2>Getty Oil v. Jones · Texas Supreme Court, 1971</h2></div>${svg("Getty pumpjacks conflicted with an existing irrigation system needing seven feet of clearance. Lower-profile alternatives were relevant to accommodation.", `<path d="M30 280H690" stroke="var(--text)" stroke-width="3"/><path d="M75 220H640" stroke="var(--power)" stroke-width="7"/><circle cx="100" cy="263" r="17" fill="none" stroke="var(--power)" stroke-width="5"/><path d="M100 220V245M610 220V267" stroke="var(--power)" stroke-width="4"/><path d="M278 277L315 120L353 277M292 210H340M303 161H330M250 115L392 151M384 148V276" fill="none" stroke="var(--heat)" stroke-width="9"/><circle cx="368" cy="219" r="27" fill="var(--heat)" opacity=".18"/><text x="38" y="55">Pumpjacks reached 17 and 34 ft</text><text x="428" y="162">Lower-profile pump</text><text x="428" y="193">Below the 7 ft clearance</text><rect x="514" y="249" width="70" height="28" rx="4" fill="var(--power)"/><path d="M548 249V232H575M575 232V277" fill="none" stroke="var(--power)" stroke-width="6"/><text x="85" y="324">Conflicting uses</text><text x="428" y="324">Both can continue</text>`)}<div class="case-takeaway">Lower pumps could let oil production and irrigation coexist.</div></div>`,
    "In Getty Oil v. Jones, an existing irrigation system needed seven feet of clearance while Getty's pumpjacks reached 17 and 34 feet. The Texas Supreme Court considered feasible lower-profile alternatives and affirmed a remand under what became the accommodation doctrine. This is a farming case, not a data-center judgment."
  );
  if (id === "ground-and-foundations") return result(
    `<div class="case-split">${photo("menard-ada-docklands-groundworks.webp", "Menard drilling rigs at ADA Infrastructure's London Docklands data-center site.", "Menard · ADA Infrastructure, London Docklands")}<div class="case-details"><h2>Former industrial ground</h2><div class="case-soil"><span>Up to 6 m of fill</span><span>Soft river deposits below</span></div><dl><div><dt>Buildings</dt><dd>Deep piles cast into the ground</dd></div><div><dt>External areas & utilities</dt><dd>≈7,000 ground-improvement columns</dd></div></dl><p>Column positions and utility depths had to fit together.</p></div></div>`,
    "ADA Infrastructure's London Docklands site had up to six metres of fill over soft alluvium and buried industrial obstructions. Menard installed about 7,000 ground-improvement columns across 40,000 square metres of external areas; CFA piles support the buildings. Utility depths and columns required coordination."
  );
  if (id === "outside-flood") return result(
    `<div class="case-status"><div class="case-heading"><h2>Equinix HO1 · Houston</h2><p>Hurricane Harvey · 28 August 2017</p></div><div class="case-status-pair"><article><b>Online</b><h3>Data center staffed and operating</h3><p>Equinix reported no interruption at HO1.</p></article><article><b>Roads closed</b><h3>Customers could not reach it</h3><p>Flooding blocked the surrounding streets.</p></article></div><div class="case-takeaway">The team stayed for days, pumping out water and keeping power on.</div></div>`,
    "Equinix reported that Houston HO1 remained staffed and operating on August 28, 2017 while surrounding streets were closed by flooding and customers could not reach it. Its later employee account describes staff staying for days and pumping water out while keeping power on. This is not a dry-campus claim or a reported bridge failure."
  );
  if (id === "qts-suwanee") return result(
    `<div class="case-split">${photo("qts-suwanee-campus.png", "QTS's campus plan showing its two Suwanee data-center buildings.", "QTS · campus plan", true)}<div class="case-details"><h2>QTS Suwanee</h2><p>Suwanee, Georgia · north of Atlanta</p><dl><div><dt>53 acres</dt><dd>Two data-center buildings</dd></div><div><dt>Colocation</dt><dd>Customers place IT equipment here and connect it to their networks.</dd></div></dl><p>Fiber must enter the buildings as well as reach the campus.</p></div></div>`,
    "QTS operates a 53-acre colocation campus in Suwanee, Georgia, north of Atlanta. The operator's campus plan identifies the buildings at 300 and 120 Satellite Boulevard. Colocation customers house IT equipment in the facilities and require physical network connections into them."
  );
  if (id === "neighbors-and-permits") return result(
    `<div class="case-split">${photo("parklane-rogers-rooftop-acoustic-barrier.jpg", "Actual acoustic screen around Rogers' rooftop data-center chillers, with neighboring residences beside it.", "Parklane · Rogers headquarters, Toronto")}<div class="case-details"><h2>Chillers opposite residences</h2><dl><div><dt>15 ft high</dt><dd>Screen around the rooftop plant</dd></div><div><dt>16 sections</dt><dd>Factory-built, then lifted into place</dd></div></dl><p>The wall interrupts the direct sound path while the open top allows airflow.</p></div></div>`,
    "Parklane's Rogers headquarters data-center retrofit in Toronto placed a 15-foot acoustic barrier around rooftop chillers facing residences. Sixteen factory-built wall sections were installed in one ten-hour day. The actual photo shows the screen and neighboring buildings; its sound reduction is not quantified here."
  );
  if (id === "hot-swap") return result(
    `<div class="case-hotswap">${photo("lenovo-gb300-power-shelf.png", "Lenovo GB300 power shelf showing six front-access 5.5 kW hot-swap power supply modules.", "Lenovo · GB300 NVL72 product guide", true)}<div class="case-hotswap-pair"><article><h2>Power-supply module</h2><p>Replace one while the remaining qualified supplies carry the load.</p><strong>The rack can stay powered.</strong></article><article><h2>Compute tray</h2><p>Lenovo requires that tray to be powered off before removal.</p><strong>Its workload must stop or move.</strong></article></div></div>`,
    "Lenovo's GB300 shelf contains six 5.5 kW hot-swappable PSU modules. A supported module replacement can keep the rack powered when the remaining supplies and configuration support the load. The compute tray has a different service boundary: Lenovo requires it powered off before removal, so its workload must stop or move."
  );
  if (id === "service-check") {
    const shown = state.serviceAnswer === "shown";
    return result(`<div class="case-check"><div class="case-heading"><h2>A failed power module and a failed compute tray</h2><p>The rack is running production work. Both replacement parts are on site.</p></div><div class="case-check-grid"><article><b>Power module</b><p>What evidence lets the rack stay powered?</p></article><article><b>Compute tray</b><p>What must happen before it moves?</p></article><article><b>Replacement route</b><p>Is a wide doorway enough?</p></article></div>${shown ? `<div class="case-answers"><p><b>Power:</b> supported hot-swap procedure and enough remaining qualified capacity.</p><p><b>Tray:</b> move or stop its workload, power off that tray, and use the specified handling method.</p><p><b>Route:</b> check tray + lift clearance, turns and concentrated floor loads along the whole path.</p></div>` : `<div class="case-prompt">Choose the service boundary, then identify the evidence you would check.</div>`}</div>`,
      shown ? "Check-in answer: supported hot-swap and surviving capacity can preserve rack power during PSU replacement. A compute tray requires workload handling and tray power-off. Its full replacement route must accommodate the tray and lift, turns and concentrated floor loads." : "Check-in: a running production rack needs a power module and a compute tray replaced. Identify what evidence allows rack power to remain on, what must happen before the tray moves, and whether a wide doorway alone establishes a usable replacement route.");
  }
  return null;
}
