import {eligibleGroups,flexibleSchedule,recoveryChoices} from './storage-model.js';
import {renderRepairRecovery,renderCheckpointPolicy} from './storage-review-visuals.js';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const n=(v,d=0)=>v.toLocaleString('en-US',{maximumFractionDigits:d});
const arrow='<span class="flow-arrow" aria-hidden="true">→</span>';
const credit=(name,url)=>`<figcaption class="figure-credit"><a href="${url}" target="_blank" rel="noopener">${name}</a></figcaption>`;
const box=(title,detail='',className='')=>`<div class="flow-box ${className}"><b>${title}</b>${detail?`<span>${detail}</span>`:''}</div>`;
const fact=(value,label,className='')=>`<div class="fact ${className}"><strong>${value}</strong><span>${label}</span></div>`;
const condition=text=>`<p class="condition">${text}</p>`;
const photo=(src,alt,label,url)=>`<figure class="case-photo"><img src="../assets/references/${src}" alt="${alt}">${credit(label,url)}</figure>`;
const rack=()=>`<div class="rack-icon" aria-hidden="true">${'<i></i>'.repeat(6)}</div>`;
const disk=()=>`<div class="disk-icon" aria-hidden="true">${'<i></i>'.repeat(3)}</div>`;
const T=(x,y,text,size=23,color='ink',anchor='middle')=>`<text x="${x}" y="${y}" font-size="${size}" fill="var(--${color})" text-anchor="${anchor}">${text}</text>`;
const R=(x,y,w,h,color='teal')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="5" fill="var(--${color})"/>`;
const svg=(body,label,w=1100,h=420)=>`<svg class="storage-diagram" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
function roles(){return `<div class="three-roles"><section>${disk()}<h2>Dataset</h2><p>The source data used for training.</p><b>Keep it available.</b></section><section><div class="cache-icon" aria-hidden="true">COPY</div><h2>Training data cache</h2><p>A nearby copy for repeated reads.</p><b>Avoid fetching it again.</b></section><section><div class="saved-state" aria-hidden="true">✓<span>Progress</span></div><h2>Checkpoint</h2><p>Saved training state used to resume a run.</p><b>Protect it from the failure.</b></section></div>`;}
function rsc(){return `<div class="case-split rsc-case">${photo('storage-meta-rsc.jpg','Rows of racks in Meta’s Research SuperCluster.','Meta · Research SuperCluster · January 2022','https://ai.meta.com/blog/ai-rsc/')}<div class="case-content"><div class="tier-row"><strong>175 PB</strong><div><b>Bulk storage</b><span>Large dataset collection</span></div></div><div class="tier-row"><strong>46 PB</strong><div><b>Cache</b><span>Copies for repeated training access</span></div></div><div class="tier-row"><strong>10 PB</strong><div><b>NFS storage</b><span>Shared file access</span></div></div><p class="case-payoff">AIRStore preprocesses data once and reuses it across training runs until expiration.</p></div></div>`;}
function durability(state){const remote=state.durability==='remote',partial=state.durability==='incomplete';return `<div class="durability-layout"><div class="failed-node"><h2>Worker node fails</h2><div class="failure-cross" aria-hidden="true">×</div>${box('Local disk',partial?'Worker unavailable':remote?'Worker unavailable':'Complete checkpoint 42 lost')}</div><div class="durability-link"><span>${remote?'Complete copy survives →':partial?'Copy 42 was still being written':'Copy 42 stayed on the worker'}</span></div><div class="surviving-store">${disk()}<h2>Independent shared store</h2><div class="stored-versions"><span>Checkpoint 41 · complete ✓</span>${remote?'<span class="new-version">Checkpoint 42 · complete ✓</span>':partial?'<span class="warning">Checkpoint 42 · incomplete</span>':''}</div><p>This store survives the worker failure.</p></div></div><div class="recovery-selection">Restart from checkpoint <b>${remote?'42':'41'}</b><span>${remote?'The complete saved state is still available.':partial?'An incomplete new save cannot replace the last complete one.':'A complete save on the failed worker is unavailable too.'}</span></div>`;}
function replication(state){const bad=state.replicaFault==='write';return `<div class="replica-layout"><section><h2>Live storage copies</h2><div class="replica-pair">${box('Copy A',bad?'Bad write applied':'Device failed','bottleneck')}${bad?arrow:'<span class="flow-arrow" aria-label="Failed device unavailable">×</span>'}${box('Copy B',bad?'Bad write replicated':'Healthy surviving copy',bad?'bottleneck':'selected')}</div><p>${bad?'Replicating a write can faithfully copy the application’s mistake.':'An independent replica keeps the data available after this one-device failure.'}</p></section><section><h2>Retained prior version</h2><div class="retained-version"><span class="version-seal">✓</span><b>Earlier valid version</b><span>Separate retention and recovery path</span></div><p>${bad?'Restore the earlier valid data, then reconcile changes made since it was saved.':'Restore remains an option if the live copies cannot supply valid data.'}</p></section></div><div class="gmail-case"><b>Gmail · 2011</b><span>A storage software bug affected replicated copies. Offline tape held a recovery copy; restoring the service still took hours.</span></div>${credit('Google · Gmail back soon for everyone · February 2011','https://gmail.googleblog.com/2011/02/gmail-back-soon-for-everyone.html')}`;}
function placement(state){const together=state.placement==='together',groups=together?[[true,true,true,true],[false,false,false,false]]:[[true,true,false,false],[true,true,false,false]];const b=eligibleGroups({groups});return `<div class="placement-request">Job needs <b>4 nodes × 8 GPUs</b> in one validated group, at the same time.</div><div class="placement-groups">${groups.map((g,i)=>`<section class="${b.eligible.includes(i)?'eligible':''}"><h2>Group ${i===0?'A':'B'}</h2><div class="placement-nodes">${g.map(free=>`<div class="${free?'free':'occupied'}">${rack()}<b>${free?'Free':'Busy'}</b><span>8 GPUs</span></div>`).join('')}</div></section>`).join('')}</div><div class="placement-result">${fact(`${b.freeGPUs} GPUs`,'Free hardware')}${fact(`${b.eligible.length}`,'Eligible four-node allocations',b.eligible.length?'':'warning')}<p>${b.eligible.length?'Reserve the group so all workers can launch together.':'Two partial groups cannot launch this job. A successful distributed restart needs the whole allocation.'}</p></div>`;}
function llama(){return `<div class="llama-story"><div class="llama-metrics">${fact('54 days','Llama 3 training snapshot')}${fact('466','Training interruptions')}${fact('>90%','Effective training time')}</div><div class="interruption-breakdown"><div><strong>47</strong><span>Planned interruptions</span></div><div><strong>419</strong><span>Unexpected interruptions</span></div></div><div class="recovery-loop"><span>Automated diagnosis</span>${arrow}<span>Restart + restore</span>${arrow}<span>Training advances</span></div><p class="llama-payoff">Meta reduced startup and checkpoint overhead; only three incidents required major manual intervention.</p>${credit('Meta · The Llama 3 Herd of Models · §3.3.4','https://arxiv.org/html/2407.21783v3#S3.SS3.SSS4')}</div>`;}
function google(){return `<div class="case-split google-case">${photo('storage-google-dalles-repair.jpg','A Google technician replaces a motherboard at The Dalles data center.','Google · The Dalles, Oregon · facility operations','https://www.datacenters.google/discover-more/photo-gallery/')}<div class="case-content"><h2>The Dalles, Oregon</h2><p>Google’s 2023 account describes a day-ahead pilot with Northern Wasco County PUD.</p><div class="google-event-path">${box('Grid event notice','Identify the constrained hours')}<span aria-hidden="true">↓</span>${box('Limit non-urgent work','Global planner assigns hourly budgets')}<span aria-hidden="true">↓</span>${box('Reschedule eligible jobs','Deadline slack · capacity later')}</div></div></div>${credit('Google Cloud · Supporting power grids with demand response · October 2023','https://cloud.google.com/blog/products/infrastructure/using-demand-response-to-reduce-data-center-power-consumption')}`;}
function schedule(state,compact){const b=flexibleSchedule({deadlineHour:state.deadline,shift:state.shift}),w=compact?420:1100,h=compact?350:330,left=compact?70:80,right=30,top=50,bottom=h-75,scale=(w-left-right)/8,py=p=>bottom-(p-18)/(26-18)*(bottom-top),x=t=>left+(t-13)*scale;let body=`<rect x="${x(14)}" y="${top-15}" width="${2*scale}" height="${bottom-top+15}" fill="var(--warning-surface)"/>`+T(x(15),top-25,'Grid event',compact?18:23,'amber');for(const p of[20,24])body+=`<path d="M${left} ${py(p)}H${w-right}" stroke="var(--line)" stroke-width="1"/>`+T(left-12,py(p)+6,`${p}`,compact?17:20,'muted','end');body+=T(15,top+15,'MW',compact?18:21,'muted','start');const breaks=[...new Set([13,21,...b.segments.flatMap(s=>[s.start,s.end])])].sort((a,b)=>a-b);let points=[];for(let i=0;i<breaks.length-1;i++){const start=breaks[i],end=breaks[i+1],on=b.segments.some(s=>start>=s.start&&start<s.end);points.push(`${x(start)},${py(on?24:20)}`,`${x(end)},${py(on?24:20)}`);}body+=`<polyline points="${points.join(' ')}" fill="none" stroke="var(--teal)" stroke-width="4"/>`+`<path d="M${x(state.deadline)} ${top-10}V${bottom+7}" stroke="var(--ink)" stroke-width="2" stroke-dasharray="6 5"/>`+T(x(state.deadline),bottom+52,'Deadline',compact?15:18);for(let t=13;t<=21;t+=compact?2:1)body+=T(x(t),bottom+30,`${t}:00`,compact?16:17,'muted');return `<div class="schedule-layout">${svg(body,`Power from 13:00 to 21:00. The job ${state.shift?'pauses from 14:00 to 16:00':'continues during the grid event'}, finishes at ${b.finishHour}:00, and ${b.meetsDeadline?'meets':'misses'} its deadline.`,w,h)}<div class="schedule-results">${fact(`${b.finishHour}:00`,'Job completes',b.meetsDeadline?'':'warning')}${fact(`${b.eventPeakMW} MW`,'Peak during grid event')}${fact(`${b.jobMWh} MWh`,'Job energy in either plan')}</div><div class="schedule-verdict ${b.meetsDeadline?'':'warning'}">${!b.meetsDeadline?'This shifted schedule misses the deadline. Keep capacity during the event or change the accepted plan.':state.shift?'The job finishes on time. Demand returns to 24 MW afterward; that capacity must remain available.':'The job finishes early, while its 4 MW demand overlaps the grid event.'}</div></div>${condition('20 MW base + 4 MW job · 3 hours of work · progress retained during the pause')}`;}
function diagnosis(state){const choice=recoveryChoices[state.diagnosis];return `<div class="diagnosis-grid"><section class="diagnosis-evidence"><h2>One worker has failed</h2><dl><dt>Saved state</dt><dd>42 complete; shared store survives.<br>43 incomplete.</dd><dt>Failed node</dt><dd>Node and local cache unavailable.</dd><dt>Required allocation</dt><dd>4 nodes in one validated group.</dd><dt>Free now</dt><dd>2 nodes in A + 2 nodes in B.</dd><dt>In 30 seconds</dt><dd>All 4 nodes in A become free.</dd><dt>Recovery target</dt><dd>First correct new output within 5 minutes.</dd></dl></section><div class="diagnosis-options">${[['newest','Restart from checkpoint 43: it is newer.'],['split','Use checkpoint 42 on the four nodes free now.'],['restore','Reserve Group A, then restore complete checkpoint 42.'],['cache','Recover 43 from the failed node’s cache.']].map(([key,label])=>`<button data-diagnosis="${key}" aria-pressed="${state.diagnosis===key}">${label}</button>`).join('')}</div></div><button id="diagnosis-reveal" ${!choice?'disabled':''}>${state.showDiagnosis?'Hide reasoning':'Check the recovery plan'}</button><div class="diagnosis-response" role="status">${state.showDiagnosis&&choice?`<p><b>${choice.correct?'A feasible recovery plan.':'One required condition is missing.'}</b> ${choice.text}${choice.correct?' Time the full recovery path against the five-minute target; allocation alone does not prove it.':''}</p>`:''}</div>`;}
export function storageVisual(id,state,compact=false){switch(id){
 case'llama-recovery':return llama();
 case'hardware-prices-meme':return `<figure class="meme-figure"><img src="../assets/references/storage-hardware-prices-meme.png" alt="A post titled CPU, you're next. The Grim Reaper, labeled AI, passes doors marked RAM prices, GPU prices and SSD prices, and knocks on CPU prices."></figure>`;
 case'meta-rsc':return rsc();
 case'storage-roles':return roles();
 case'durability-boundary':return durability(state);
 case'replication-and-backup':return replication(state);
 case'tray-repair':return renderRepairRecovery();
 case'recovery-placement':return placement(state);
 case'checkpoint-policy':return renderCheckpointPolicy(state,compact);
 case'google-demand-response':return google();
 case'deadline-scheduling':return schedule(state,compact);
 case'recovery-diagnosis':return diagnosis(state);
 default:throw new Error(`No storage visual for ${id}`);
}}
