export const learningContract = Object.freeze({
  driving_question: 'How does an LLM workload turn a rack of GPUs into memory, service and power requirements?',
  fixed_boundary: 'One GB300 NVL72 is the hardware anchor. Llama 3.1 70B memory estimates, chosen service targets, production H100 evidence and original timing models are explicitly separate.',
  changed_variable: 'The response-speed or session target, context length, request membership, runtime and phase alignment each expose a resource consequence.',
  primary_payoff: 'Translate model state and token delivery into a measured workload brief for electrical supply and cooling.',
  misconception: 'Rated FLOPS, fitted weights or average power establish delivered tokens or a suitable power supply.',
  closing_question: 'What must be measured at the intended workload and meter before choosing supply and buffering?',
});
export const initialState = Object.freeze({ tokensPerSecond:40, minInteractivity:100, reuseTokens:1 });
const brief='d02-workload-brief', productive='d02-productive-utilization', phases='d02-phases-and-envelopes';
const choice=(key,label,options)=>({key,label,options});
export const scenes = [
 {id:'workload-purpose',label:'Why the workload comes first',title:'The model and its users determine what the data center must deliver.',reference:brief,pedagogical_role:'orientation',boundary:'Chapter route: model state → token service → power over time.',explanation:['The previous chapter located power, heat and network paths. This chapter gives those systems a job. First compare learning a model with serving it. Then turn model state and request length into a memory account, explain how requests share accelerators, and inspect the resulting power trace.','The output is a workload brief for the next supply chapter: the named hardware and software, input/output lengths, traffic and response objectives, plus time-resolved power at a declared meter. These requirements cannot be recovered from accelerator count or peak FLOPS alone.']},
 {id:'model-work',label:'Training beside inference',title:'',reference:brief,pedagogical_role:'comparison',boundary:'Training and serving the same model.',explanation:['Training computes gradients and optimizer updates; inference retains request state and generates answers. Those operations create different memory and communication demands.','Training compute can be counted in floating-point operations (FLOPs); FLOP/s measures how fast those operations execute. Neither the operation count nor its rate establishes the trained model’s quality. For inference, throughput counts output tokens across all users, while first-token latency and inter-token latency describe the response experienced by an individual user.']},
 {id:'interactivity',label:'Interactivity: tokens per second per user',title:'Interactivity is tokens per second per user.',reference:brief,pedagogical_role:'mechanism',boundary:'Output generation after the first token.',controls:[choice('tokensPerSecond','Interactivity',[[20,'20 tokens/s/user'],[40,'40 tokens/s/user'],[80,'80 tokens/s/user']])],explanation:['Interactivity measures the speed of one user’s generated answer: output tokens per second per user. At 40 tokens per second, the average interval between output tokens is 25 milliseconds. At 80 it is 12.5 milliseconds. A token is a piece of text, such as a word or part of a word.','Total throughput counts output tokens across the whole system. Serving more requests together can improve aggregate throughput while reducing each user’s speed. Choose a minimum interactivity and measure throughput while meeting it. Time to first token is the separate initial wait before streaming starts.']},
 {id:'serving-frontier',label:'Interactivity versus throughput',title:'Faster answers leave less throughput for the same hardware.',reference:brief,pedagogical_role:'evidence',boundary:'NVIDIA GB300 NVL72 · Qwen3.8 FP8 · TensorRT-LLM · 8k input / 1k output.',controls:[choice('minInteractivity','Minimum interactivity',[[100,'100 tokens/s/user'],[200,'200 tokens/s/user'],[300,'300 tokens/s/user']])],explanation:['NVIDIA’s published GB300 NVL72 curve places interactivity on the horizontal axis and total throughput normalized per GPU on the vertical axis. Select the minimum acceptable speed per user. Only the portion to the right of that threshold qualifies; the curve shows the throughput available at those speeds. Hardware, model, precision and workload conditions are named in the original figure.','This figure supplies an observed tradeoff rather than a fixed-capacity division. It does not report a concurrency table, so exact supported-session counts require the corresponding serving benchmark. Peak throughput and peak interactivity occur at different operating points.']},
 {id:'memory-comparison',label:'One model, two state budgets',title:'The same 70B model needs much more state when its parameters are trained.',reference:brief,pedagogical_role:'balance',boundary:'Rounded 70 billion parameters · decimal GB · BF16 serving weights versus a classic mixed-precision Adam training ledger.',explanation:['For inference, two bytes per parameter gives approximately 140 GB of weights. A classic mixed-precision Adam account includes 2-byte weights, 2-byte gradients, 4-byte master weights and two 4-byte optimizer moments: 16 bytes per parameter, or approximately 1,120 GB of training state.','Neither number is total runtime memory. Add request KV cache and workspace for inference, or activations and communication buffers for training. Optimizer, precision, recomputation, sharding and offload change the account. This is why a model that fits for serving can require distribution for training. It is not a universal 70B training minimum or a GB300 board allocation.']},
 {id:'kv-cache',label:'What a context stores',title:'Longer contexts retain more key and value state for every active request.',reference:brief,pedagogical_role:'mechanism',boundary:'Llama 3.1 70B geometry · BF16 KV · no prefix sharing, cache quantization or block overhead.',explanation:['During inference, the attention implementation can retain key and value vectors for prior tokens so they are available to subsequent decode steps. Meta’s configuration gives 80 layers, eight KV heads and head dimension 128. At two bytes per element, each cached token needs 2 × 80 × 8 × 128 × 2 = 327,680 bytes, or 320 KiB.','This is full-context cache accounting for this particular model and precision, not a universal bytes-per-token constant. Prompt and generated tokens both occupy context. Prefix caching can reuse the KV blocks for initial tokens shared by requests; the arithmetic here counts each request independently. Quantization, sliding windows, model structure and allocation overhead can also change memory use.']},
 {id:'context-capacity',label:'Context changes concurrency',title:'Context length and model design change the KV-cache budget.',reference:brief,pedagogical_role:'comparison',boundary:'64 GiB allocated to KV cache · 320 KiB per cached token · equal full contexts.',explanation:['At 8,192 cached tokens, one request uses 2.5 GiB. At 32,768 it uses 10 GiB. Floor division of the chosen 64 GiB cache pool gives 25 or six complete requests. The 64 GiB is an explicit allocation decision, not all memory on a named GPU. Weights and other runtime state occupy separate allocations.','Keeping 100 sessions resident at those full lengths would require at least four or seventeen such independent cache pools under this arithmetic model. That is not a GPU count: replication, tensor parallelism and implementation determine which devices own a pool. The connection to facility design is context → resident concurrency → serving replicas and their measured power. Memory fit alone does not establish token speed.','The DeepSeek V4 technical-report figure compares compressed-attention KV state in V4-Pro and V4-Flash with V3.2. Their attention architecture and storage formats differ from the preceding Llama example, so its 320 KiB per token should not be applied to this chart.']},
 {id:'prefill-decode',label:'Prompt processing and generation',title:'Prefill needs compute; decode needs memory bandwidth.',reference:phases,pedagogical_role:'mechanism',boundary:'Autoregressive serving · typical prefill and low-batch decode behavior.',explanation:['Prefill processes the prompt and creates the initial request state. Decode repeatedly extends the sequence, commonly producing one new token per active request per iteration. Each new token depends on previous context; batching multiple requests creates more work to perform together.','Time to first token includes queueing, prompt processing and first-token work. Inter-token latency concerns the stream after that point. Prefill often offers more parallel matrix work; low-batch decode can be constrained by memory bandwidth. Neither phase has a universal power level, and speculative decoding or other implementations change execution. Peak FLOPS alone is therefore insufficient to predict delivered token throughput.']},
 {id:'operand-reuse',label:'Reuse a weight read',title:'One weight read can serve several tokens.',reference:phases,pedagogical_role:'mechanism',boundary:'One matrix-operation tile, retained in GPU on-chip memory.',controls:[choice('reuseTokens','Token vectors using this tile',[[1,'One'],[8,'Eight']])],explanation:['GPU memory, or HBM, stores the model weights. A matrix operation brings a small block of those weights—a tile—into the GPU’s on-chip memory. One token vector can use it, or several token vectors can reuse it before the tile is replaced. Switch from one to eight: the weight tile stays the same while the arithmetic it supports grows.','Prefill supplies many prompt-token vectors together. Batching decode requests can also supply several token vectors at once. Reusing weights reduces the weight bytes fetched per token, helping explain why prefill can use compute heavily while low-batch decode spends more time moving weights. On-chip storage is much smaller than HBM, so this reuse happens a tile at a time; it does not mean the whole model remains on-chip.']},
 {id:'disaggregated-serving',label:'Different hardware for each phase',title:'Prefill and decode can use different hardware.',reference:phases,pedagogical_role:'architecture',boundary:'Vera Rubin NVL72 and NVIDIA Groq 3 LPX · separate rack platforms.',explanation:['NVIDIA describes a standard prefill–decode configuration that runs prefill on Vera Rubin NVL72 and hands the KV cache to Groq 3 LPX for decode. Rubin handles the parallel prompt computation; the LPX platform uses SRAM-based LPUs to deliver output tokens with low latency. The platforms occupy separate racks.','NVIDIA also describes other ways to split the workload. This slide follows its August 2026 standard prefill–decode configuration, rather than treating LPX as a Blackwell rack or implying that every serving installation uses this separation. The original NVIDIA product render is shown unchanged.']},
 {id:'continuous-batching',label:'Continuous batching',title:'Batching',reference:phases,pedagogical_role:'mechanism',boundary:'Two decode slots · A needs 2 steps, B needs 5, C needs 3 · C already waiting · prefill costs omitted.',explanation:['A fixed batch can leave a slot unused after one sequence finishes while a longer sequence continues. In this illustration, A finishes after two decode steps. Continuous batching admits queued request C into that slot while B continues, instead of waiting for B’s whole response. vLLM documents iteration-level request scheduling and continuous batching.','This is a scheduler mechanism, not a measured speedup. The numbered cells are decode iterations, not equal wall-clock durations guaranteed under both policies. Prefill, KV capacity, token budgets and implementation determine which new work can be admitted. It matters here because request membership changes active compute and memory; continuous batching does not guarantee a flat electrical load.']},
 {id:'energy-per-result',label:'Compare the same completed work',title:"Interactivity isn’t the only important metric.",reference:productive,pedagogical_role:'comparison',boundary:'Same completed tokens and quality · complete-run mean power.',explanation:['Hold completed useful work fixed. Run A averages 100 kW for ten minutes: 16.7 kWh. Run B averages 80 kW but takes fifteen minutes: 20 kWh. Five extra minutes outweigh the lower power, increasing energy for the same accepted token workload by 20 percent.','The power and duration are explicit teaching inputs. Include waiting and supporting equipment within the same meter boundary; a sample of the compute phase cannot substitute for whole-run energy.']},
 {id:'resource-paths',label:'Locate the stalled training step',title:'GPU power falls while a training step waits for an exchange.',reference:productive,pedagogical_role:'diagnosis',boundary:'Illustrative synchronous training dependency · no measured delay or power magnitude.',explanation:['A data-parallel training iteration may require gradient synchronization before an update can complete. If a required exchange is late, the next dependent work waits even while the workers remain allocated and powered. The visual connects the delay to a specific dependency, rather than equating allocation with useful output.','Correlate GPU activity and power with collective timings, network counters and storage events. That observation distinguishes an exposed communication wait from input starvation or checkpoint work; it does not prove a root cause from one utilization number. Communication and compute can overlap in real implementations. The following production trace shows why synchronized work also matters to electrical supply.']},
 {id:'training-power-evidence',label:'A measured training trace',title:'Production training racks show repeated power swings as their work synchronizes.',reference:phases,pedagogical_role:'evidence',boundary:'DGX-H100 production training trace · Choukse et al., 2025, Figure 1 · normalized power, not GB300 wattage.',explanation:['The Microsoft, OpenAI and NVIDIA authors publish power readings from an at-scale training job on DGX-H100 racks. Their discussion connects high compute activity and lower-power communication/checkpoint phases to synchronized power variation. This source figure establishes that the concern is observed in practice.','The figure is normalized and does not supply a GB300 power specification. Memory access is not inherently maximum-power work, and lower arithmetic activity does not mean the network or GPUs use zero power. Later figures evaluating storage in this paper are simulations; they are not being presented as production storage measurements.']},
 {id:'job-phases',label:'Explain one training rhythm',title:'Compute and exchange phases create a time-varying electrical load.',reference:phases,pedagogical_role:'mechanism',boundary:'30 s at 120 kW compute · 15 s at 40 kW exchange · 15 s at 60 kW save.',explanation:['This simplified training cycle isolates three activities: compute, an exposed exchange interval and checkpoint save. Its powers and durations are declared assumptions chosen for legible arithmetic, not a digitization of the previous production trace. The phases explain the shape that electrical equipment sees.','Over 60 seconds, energy is 120 × 30 + 40 × 15 + 60 × 15 = 5,100 kJ, giving 85 kW mean. The 120 kW plateau and each transition remain separate requirements. Data centers need the power trace at the relevant shared electrical boundary, with enough resolution to retain those events.']},
 {id:'synchronized-jobs',label:'Sum coincident activity',title:'When four groups enter compute together, their shared supply sees a 480 kW peak.',reference:phases,pedagogical_role:'mechanism',boundary:'Four copies of the original 60 s trace · shared meter · simultaneous phases · workload independence not yet assumed.',explanation:['Sum four identical power traces at the same timestamps: 480 kW during compute, 160 during exchange and 240 during save. Their shared mean is 340 kW. This is the link between distributed workload timing and the upstream supply that serves the groups.','Coincident groups could be independent jobs or participants in a coupled training job. That distinction does not change the sum, but it changes whether moving their start times is a legitimate remedy. The next comparison uses separate jobs whose starts can move.']},
 {id:'staggering-jobs',label:'Start independent jobs 15 seconds apart',title:'Start independent jobs 15 seconds apart to spread their power demand.',reference:phases,pedagogical_role:'comparison',boundary:'Four independent jobs · phase durations unchanged · periodic operation.',explanation:['Offset four independent copies by 0, 15, 30 and 45 seconds. At every point in the repeating cycle, two compute, one exchanges and one saves: 340 kW. Each retains the same phase durations, so the 5.667 kWh cycle energy is preserved.','These are separate jobs whose start times can move while still meeting their deadlines. Workers in one synchronous training job must meet at exchanges; delaying one can make the others wait. Shared-resource contention, startup and completion need separate analysis. The reader carries those dependency and power-response details.']},
 {id:'next-brief',label:'Carry the workload into supply design',title:'Size the supply from the workload’s measured power trace.',reference:brief,pedagogical_role:'handoff',boundary:'A design brief, not a pass/fail quiz · service target chosen; measured rack performance remains to be established.',explanation:['Carry the named hardware, model and software; prompt/output lengths, simultaneous sessions, output-token target, time-to-first-token target and quality conditions. Then benchmark that workload and record complete-run energy alongside peak demand, transition speed and recovery behavior at the relevant IT or facility meter.','The next chapter can use those requirements to reason about deliverable supply, redundancy and buffering. What remains unknown must remain visible. Use the throughput attained at the required interactivity, together with its measured power, to size that service.']},
];
export const legacySceneAliases = Object.freeze({
 'success-brief':'interactivity','service-checkin':'next-brief',
 'independence':'staggering-jobs','demand-transition':'job-phases','power-response':'next-brief',
 'inference-memory':'memory-comparison','training-memory':'memory-comparison','partition-fit':'context-capacity',
 'measured-progress':'interactivity','occupied-waiting':'resource-paths','batching-throughput':'continuous-batching',
 'gathering-latency':'continuous-batching','arrival-capacity':'continuous-batching','acceptance-envelope':'next-brief',
});
