import { phaseSchedule, transitionRate, llamaMemory, sameWorkEnergy, decodeSlots } from './workload-model.js';
const C={ink:'var(--text)',muted:'var(--muted)',line:'var(--line)',panel:'var(--panel)',paper:'var(--paper)',face:'var(--surface)',compute:'var(--power)',communication:'var(--data)',checkpoint:'var(--heat)',wait:'var(--heat)',idle:'var(--muted)'};
const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const n=(v,d=0)=>v.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const t=(x,y,s,size=22,color=C.ink,anchor='start')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${color}" text-anchor="${anchor}">${esc(s)}</text>`;
const lines=(x,y,a,size=22,color=C.ink,anchor='start',step=size*1.4)=>a.map((s,i)=>t(x,y+i*step,s,size,color,anchor)).join('');
const r=(x,y,w,h,fill=C.panel,stroke=C.line,rx=9)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}"/>`;
const line=(x,y,xx,yy,color=C.line,width=2,dash='')=>`<path d="M${x} ${y}L${xx} ${yy}" fill="none" stroke="${color}" stroke-width="${width}" ${dash?'stroke-dasharray="'+dash+'"':''}/>`;
const arrow=(x,y,xx,yy,color=C.compute)=>`${line(x,y,xx,yy,color,3)}<path d="M${xx-9} ${yy-6}L${xx} ${yy}L${xx-9} ${yy+6}" transform="rotate(${Math.atan2(yy-y,xx-x)*180/Math.PI} ${xx} ${yy})" fill="none" stroke="${color}" stroke-width="3"/>`;
const result=(markup,description)=>({markup,description});
const photo='https://docs.nvidia.com/enterprise-reference-architectures/nvl72-ai-factory/latest/_images/nvl72-ai-factory-01.png';
const split=(m)=>m?line(25,334,365,334):line(600,55,600,505);
const panel=(i,m)=>({x:m?28:60+i*600,y:m?40+i*335:70,w:m?334:480});
function purpose(s,m){let o='';
 const concepts=[['01','MODEL STATE','Weights, context and training updates'],['02','TOKEN SERVICE','Requests, batching and response time'],['03','ELECTRICAL DEMAND','Energy, peaks and fast transitions']];
 concepts.forEach(([num,a,b],i)=>{const x=m?28:70,y=m?72+i*178:82+i*142;o+=t(x,y,num,m?25:37,C.compute)+t(x+(m?52:80),y,a,m?18:27,C.ink)+t(x+(m?52:80),y+39,b,m?14:24,C.muted)+line(x,y+70,m?362:1110,y+70);});
 return result(o,'First account for model state, then define token service, then measure its electrical demand. These dependencies become the workload brief used to design supply and cooling.');}
function brief(s,m){let o='';
 o+=`<image href="${photo}" x="${m?22:42}" y="${m?20:15}" width="${m?126:360}" height="${m?248:495}" preserveAspectRatio="xMidYMid meet"><title>NVIDIA GB300 NVL72 manufacturer image</title></image>`;
 o+=t(m?173:468,m?80:80,'GB300 NVL72',m?23:34)+t(m?173:468,m?125:135,'72 B300 GPUs',m?22:39,C.compute)+t(m?173:468,m?167:185,'Llama 3.1 70B',m?18:27);
 const x=m?30:468,y=m?328:269;o+=t(x,y,'CHOSEN SERVING REQUIREMENT',m?17:20,C.muted)+t(x,y+58,'100 sessions × 40 tokens/s',m?25:40)+t(x,y+117,'4,000 output tokens/s',m?29:46,C.compute)+t(x,y+156,'After the first token · quality held fixed',m?16:23,C.muted);
 o+=t(m?195:600,m?603:540,'Requirement ≠ measured rack throughput · Image: NVIDIA',m?13:19,C.muted,'middle');
 return result(o,'One GB300 NVL72 has 72 B300 GPUs. The chosen Llama 3.1 70B service asks for 100 simultaneous active sessions at 40 output tokens per second after the first token: 4,000 output tokens per second required. This is not a rack benchmark.');}
function modelWork(s,m){let o=split(m);
 [['TRAINING','Learn parameters',['Forward pass → loss','Backward pass → gradients','Optimizer → updated weights'],'Useful model progress by a deadline'],['INFERENCE','Produce tokens',['Prompt → prefill + KV cache','Decode → next output token','Scheduler → active requests'],'Throughput + first/inter-token latency']].forEach(([name,sub,steps,payoff],i)=>{const {x,y}=panel(i,m);o+=t(x,y,name,m?21:30,i?C.communication:C.compute)+t(x,y+42,sub,m?24:34);steps.forEach((v,j)=>o+=t(x,y+99+j*(m?38:54),v,m?18:25));o+=t(x,y+(m?244:300),payoff,m?15:22,C.muted);});
 return result(o,'Training learns parameters through forward, backward and optimizer work. Inference uses configured parameters to prefill prompts and decode output tokens. Training needs a progress target and deadline; inference needs token throughput and response-time targets.');}
function memoryCompare(s,m){let o=split(m);
 [['SERVING WEIGHTS','2 bytes / parameter','≈140 GB',['BF16 weights','Add KV cache + runtime workspace']],['ADAM STATE · EXAMPLE','16 bytes / parameter','≈1,120 GB',['FP16/FP32 · 2 weights + 2 gradients','+ 4 master + 8 moments; add activations']]].forEach(([a,b,c,d],i)=>{const {x,y}=panel(i,m);o+=t(x,y,a,m?20:27,i?C.checkpoint:C.compute)+t(x,y+44,'70B × '+b,m?18:27)+t(x,y+(m?115:145),c,m?45:64,i?C.checkpoint:C.compute)+lines(x,y+(m?166:219),d,m?15:22,C.muted,'start',m?30:37);});
 return result(o,'Rounded 70 billion parameters: serving BF16 weights use about 140 GB. A classic mixed-precision Adam account at 16 bytes per parameter uses about 1,120 GB of training state before activations and buffers. Optimizer, precision and partition choices can change it. Decimal GB.');}
function kv(s,m){let o='';
 o+=t(m?195:600,m?53:53,'One cached token in Llama 3.1 70B',m?22:31,C.ink,'middle');
 const cols=m?2:5,items=[['2','K + V'],['80','layers'],['8','KV heads'],['128','head width'],['2 B','BF16 element']];
 items.forEach(([a,b],i)=>{const x=m?35+(i%2)*174:74+i*219,y=m?99+Math.floor(i/2)*121:130;o+=t(x,y,a,m?39:56,C.compute)+t(x,y+36,b,m?17:22,C.muted);if(!m&&i<4)o+=t(x+151,y,'×',30,C.muted);});
 o+=t(m?195:600,m?494:314,'327,680 bytes = 320 KiB / token',m?22:40,C.compute,'middle')+t(m?195:600,m?563:399,'KV memory = cached tokens × 320 KiB',m?18:28,C.ink,'middle')+t(m?195:600,m?623:482,'BF16 · no cache sharing, quantization or block overhead',m?12:20,C.muted,'middle');
 return result(o,'Two K and V vectors times 80 layers times eight KV heads times 128 elements times two bytes equals 327,680 bytes, or 320 KiB, per cached token. Multiply by all cached context tokens in every active request.');}
function context(s,m){let o=split(m);[8192,32768].forEach((tokens,i)=>{const a=llamaMemory({contextTokens:tokens}),{x,y,w}=panel(i,m);o+=t(x,y,n(tokens)+' cached tokens',m?22:32)+t(x,y+54,`${a.requestGiB} GiB / request`,m?27:39,C.communication);const ww=m?10:14,gap=m?2:4;for(let j=0;j<a.concurrentRequests;j++)o+=r(x+j*(ww+gap),y+95,ww,43,C.communication,C.communication,2);o+=t(x,y+190,`${a.concurrentRequests} resident requests`,m?28:41,C.compute)+t(x,y+230,'In a chosen 64 GiB KV pool',m?17:23,C.muted);});return result(o,'A chosen 64 GiB KV pool holds at most 25 requests with 8,192 cached tokens each, or six with 32,768. Each request uses 2.5 GiB or 10 GiB respectively. This is cache capacity, not token throughput or a GPU count.');}
function prefill(s,m){let o=split(m);[['PREFILL','Process the prompt',['All prompt positions','Build the initial KV cache'],'Time to first token'],['DECODE','Extend the answer',['Step 1     Step 2     Step 3','token      token      token'],'Time between output tokens']].forEach(([a,b,c,d],i)=>{const {x,y}=panel(i,m);o+=t(x,y,a,m?23:31,i?C.communication:C.compute)+t(x,y+49,b,m?26:38)+lines(x,y+110,c,m?20:28,C.ink,'start',m?42:63)+t(x,y+(m?240:300),d,m?19:27,C.muted);});return result(o,'Prefill processes the prompt and builds initial key/value state. Decode repeatedly extends the answer. Time to first token and time between output tokens measure different phases; their compute and memory demands differ.');}
function continuous(s,m){let o=split(m);[false,true].forEach((policy,i)=>{const a=decodeSlots(policy),{x,y}=panel(i,m),gx=x+(m?52:58),cell=m?33:47; o+=t(x,y,policy?'CONTINUOUS BATCH':'FIXED BATCH',m?21:28,policy?C.communication:C.compute)+t(x,y+37,policy?'C fills A’s released slot':'C waits for the batch',m?18:24,C.muted);a.rows.forEach((row,j)=>{o+=t(x,y+101+j*55,`Slot ${j+1}`,m?13:17,C.muted);row.forEach((job,k)=>{const xx=gx+k*cell,yy=y+74+j*55,col=job==='A'?C.compute:job==='B'?C.communication:job==='C'?C.checkpoint:C.panel;o+=r(xx,yy,cell-4,42,col,col,4);if(job)o+=t(xx+(cell-4)/2,yy+28,job,m?18:23,C.paper,'middle');});});for(let k=0;k<8;k++)o+=t(gx+k*cell+(cell-4)/2,y+208,k+1,m?12:16,C.muted,'middle');o+=t(x,y+255,'Decode iterations · no wall-clock claim',m?15:22,C.muted);});return result(o,'Two decode slots. A needs two steps, B five and queued C three. The fixed batch starts C only after B finishes. Continuous batching starts C in the released slot while B continues. Prefill and implementation timing are omitted; this is not a claimed speedup.');}
function energy(s,m){const a=sameWorkEnergy();let o='';const x=m?25:92,w=m?340:1016,col1=x+(m?177:556),col2=x+(m?267:826);o+=t(x,m?43:53,'Same completed tokens and quality',m?22:32)+t(col1,m?115:135,'Run A',m?22:29,C.compute,'middle')+t(col2,m?115:135,'Run B',m?22:29,C.communication,'middle');[['Mean power','100%','80%'],['Duration','100%','150%'],['Total energy','100%','120%']].forEach(([name,a,b],i)=>{const y=(m?181:211)+i*(m?91:91);o+=line(x,y+30,x+w,y+30)+t(x,y,name,m?18:28)+t(col1,y,a,m?28:43,C.compute,'middle')+t(col2,y,b,m?28:43,i===2?C.checkpoint:C.communication,'middle');});o+=t(m?195:600,m?513:492,'0.8 × 1.5 = 1.2 × the energy',m?25:32,C.checkpoint,'middle')+t(m?195:600,m?586:540,'At 80% power, break-even runtime is 125%.',m?17:23,C.muted,'middle');return result(o,'For identical accepted output, run B uses 80 percent of A’s mean power for 150 percent of the duration. Its total energy is 120 percent. At 80 percent power, break-even duration is 125 percent. Relative teaching comparison, not measured hardware performance.');}
function resource(s,m){let o=''; const x=m?77:240,w=m?280:870,top=m?113:120,row=m?107:96;
 ['GPU group A','GPU group B','GPU group C'].forEach((name,i)=>{const y=top+i*row;o+=t(m?24:66,y-18,name,m?17:25);o+=r(x,y,w*.48,42,C.compute,C.compute,0)+r(x+w*.48,y,w*.28,42,C.checkpoint,C.checkpoint,0)+r(x+w*.76,y,w*.24,42,C.communication,C.communication,0);});
 o+=t(x+w*.24,m?485:443,'Compute',m?16:23,C.compute,'middle')+t(x+w*.62,m?522:443,'Exchange / wait',m?16:23,C.checkpoint,'middle')+t(x+w*.88,m?559:443,'Next step',m?15:23,C.communication,'middle')+line(x+w*.76,top-36,x+w*.76,top+2*row+52,C.muted,2,'5 5');o+=t(m?195:600,m?635:521,'Inspect collective timings alongside GPU activity and power.',m?13:23,C.muted,'middle');return result(o,'Three training groups compute, participate in or wait for a required exchange, then begin the next dependent step. The shared dependency can expose a low-compute period. Align collective timings, GPU activity, storage events and power to diagnose the stall.');}
function evidence(s,m){let o='';const src='https://arxiv.org/html/2508.14318v1/Fig1.svg';o+=r(m?14:40,m?94:79,m?362:1120,m?234:374,'white','white',0)+`<image href="${src}" x="${m?14:40}" y="${m?94:79}" width="${m?362:1120}" height="${m?234:374}" preserveAspectRatio="xMidYMid meet"><title>Figure 1: power readings from an at-scale training job on DGX-H100 racks, Choukse et al., 2025</title></image>`;o+=t(m?195:600,m?420:494,'DGX-H100 production training · normalized power',m?16:25,C.ink,'middle')+t(m?195:600,m?479:535,'Choukse et al. (2025), Fig. 1 · Microsoft / OpenAI / NVIDIA',m?11:18,C.muted,'middle')+t(195,m?549:580,m?'Read peaks, cycle rhythm and transition speed.':'',m?14:19,C.muted,'middle');return result(o,'Published Figure 1 shows normalized production training power from DGX-H100 racks over time. It is real source telemetry, distinct from the following illustrative kW traces and from GB300 product ratings.');}
function phaseVisual(id,s,m){
 const single=id==='job-phases',staggered=id==='staggering-jobs'&&s.schedule==='staggered',offsets=single?[0]:staggered?[0,15,30,45]:[0,0,0,0],a=phaseSchedule({offsetsSeconds:offsets});let o='';
 const x=m?62:157,w=m?296:960,sc=w/60,top=m?104:85,row=single?(m?99:78):(m?49:47);
 const names={compute:'compute',communication:'exchange',checkpoint:'save'};
 for(let j=0;j<offsets.length;j++){
 const y=top+j*row;o+=t(m?8:35,y+25,single?'Group':`G${j+1}`,m?17:23,C.ink);
 for(const seg of a.segments){const ph=seg.jobPhases[j],xx=x+seg.startSeconds*sc,ww=(seg.endSeconds-seg.startSeconds)*sc;o+=r(xx,y,ww,row-8,C[ph.kind],C[ph.kind],0);if(ww>(m?65:100))o+=t(xx+ww/2,y+(row-8)/2+6,m?(ph.kind==='compute'?'C':ph.kind==='communication'?'↔':'S'):names[ph.kind],m?16:21,C.paper,'middle');}
 }
 const gy=single?(m?272:233):(m?370:322),gh=single?(m?196:184):(m?130:143),max=single?140:520,py=power=>gy+gh-power/max*gh;
 o+=t(m?20:x,m?gy-20:gy-36,m?'kW':single?'Illustrative training power (kW)':'Power at the shared meter (kW)',m?16:21,C.muted)+line(x,gy+gh,x+w,gy+gh);
 let d='';for(const seg of a.segments){const xx=x+seg.startSeconds*sc,xe=x+seg.endSeconds*sc,yy=py(seg.powerKW);d+=(d?'L':'M')+xx+' '+yy+'H'+xe;}
 o+=`<path d="${d}" fill="none" stroke="${C.compute}" stroke-width="5"/>`;
 const avgY=py(a.averageKW);o+=line(x,avgY,x+w,avgY,C.muted,2,'6 5');
 a.segments.forEach(seg=>{const yy=py(seg.powerKW),xx=x+(seg.startSeconds+seg.endSeconds)/2*sc;o+=t(xx,yy-12,String(seg.powerKW),m?20:28,C.compute,'middle');});
 [0,30,45,60].forEach(v=>o+=t(x+v*sc,gy+gh+29,`${v}${v===60?' s':''}`,m?15:21,C.muted,'middle'));
 o+=t(x+w,avgY+(staggered?28:-25),`${n(a.averageKW)} kW mean`,m?16:22,C.muted,'end');
 if(!staggered)o+=line(x+w,avgY-18,x+w,avgY,C.muted,1);
 if(m)o+=t(195,single?232:317,'C compute · ↔ exchange · S checkpoint',16,C.muted,'middle');
 if(single)o+=t(x+w,m?584:515,'Original teaching trace · not product telemetry',m?14:20,C.muted,'end');
 if(!single)o+=t(x+w,m?574:530,`${n(a.energyKWh,3)} kWh / 60 s cycle`,m?19:25,C.ink,'end');
 if(id==='staggering-jobs')o+=lines(m?62:157,m?38:25,m?['Conditional independent-job example','No contention or added waiting']:['Conditional example · independent jobs · no contention or added waiting'],m?15:18,C.muted);
 return {markup:`<g data-peak-kw="${a.peakKW}" data-average-kw="${a.averageKW}" data-energy-kwh="${a.energyKWh}" data-schedule="${staggered?'staggered':'sync'}">${o}</g>`,description:`${single?'One job':'Four '+(staggered?'independent jobs offset by fifteen seconds':'synchronized jobs')} has power plateaus ${a.segments.map(seg=>seg.powerKW).join(', ')} kW; peak ${a.peakKW} kW and mean ${n(a.averageKW)} kW. Energy is ${n(a.energyKWh,3)} kWh per sixty-second cycle. ${staggered?'At every instant two compute, one exchanges and one checkpoints. This requires independence, no contention and periodic steady operation.':''}`};
}
function independence(s,m){
 const coupled=s.relation==='coupled',x=m?72:205,w=m?278:790,top=m?146:135,row=m?84:71;let o='';
 const barrier=x+w*.75;
 for(let i=0;i<4;i++){
 const y=top+i*row,delay=i===3?45:0,computeW=coupled?w*.46:w*(.30+(i%2)*.13),start=coupled?x+(i===3?w*.26:0):x+i*w*.06;
 o+=t(m?20:67,y+24,coupled?`W${i+1}`:`J${i+1}`,m?18:24,C.ink)+r(start,y,computeW,42,C.compute,C.compute,0);
 if(coupled){const end=start+computeW;if(i<3)o+=r(end,y,barrier-end,42,C.checkpoint,C.checkpoint,0)+t(end+(barrier-end)/2,y+26,'wait',m?15:22,C.paper,'middle');o+=arrow(barrier+7,y+21,x+w,y+21,C.communication);}else o+=r(start+computeW,y,w*.18,42,C.communication,C.communication,0);
 }
 if(coupled)o+=line(barrier,top-36,barrier,top+3*row+53,C.communication,3,'5 5')+t(barrier,top-53,'exchange',m?17:25,C.communication,'middle');
 o+=arrow(x,m?516:451,x+w,m?516:451,C.muted)+t(x+w,m?554:486,'Time',m?19:25,C.muted,'end');
 return {markup:o,description:coupled?'Four workers belong to one distributed job. Worker four starts late. The other three wait at a shared exchange point until worker four arrives. This is not the independent-job staggering model; completion time and energy would need to be measured again.':'Four jobs progress separately and each reaches its own exchange phase. Offsetting them can be considered only if deadlines, storage and network contention still allow the required accepted service.'};
}
function demand(s,m){const duration=s.transitionSeconds??2,rate=transitionRate({durationSeconds:duration}),x=m?51:120,w=m?290:600,y=m?96:89,h=m?235:286,p=v=>y+h-v/550*h;let o='';o+=line(x,y+h,x+w,y+h)+line(x,y,x,y+h);const xa=x+w*.3,xb=x+w*.7;o+=`<path d="M${x} ${p(480)}H${xa}L${xb} ${p(160)}H${x+w}" fill="none" stroke="${C.compute}" stroke-width="5"/>`+t(x,p(480)-18,'480 kW',m?24:30,C.compute)+t(x+w,p(160)-18,'160 kW',m?24:30,C.compute,'end')+line(xa,y+h+15,xb,y+h+15)+t((xa+xb)/2,y+h+49,`${duration} s`,m?23:31,C.ink,'middle');const xx=m?33:800,yy=m?457:143;o+=t(xx,yy,'READ THE TRACE',m?18:22,C.muted)+t(xx,yy+45,'Peak: 480 kW',m?25:34)+t(xx,yy+93,'Change: 320 kW',m?25:31)+t(xx,yy+141,`Rate: ${n(Math.abs(rate))} kW/s`,m?25:31,C.communication)+t(m?195:600,m?652:501,'The 340 kW cycle mean describes energy, not these limits.',m?12:22,C.muted,'middle');return result(o,`Power falls from 480 to 160 kW across an assumed ${duration} seconds: magnitude ${Math.abs(rate)} kW per second. Read the peak, amplitude, duration and repetition rate at the intended meter. A 340 kW cycle average does not establish those limits.`);}
function response(s,m){let o='';[['WHEN WORK RUNS','Scheduler','Eligibility, dependencies and deadlines'],['WHAT GPUs DRAW','Supported power controls','Runtime and energy may change'],['WHAT THE SOURCE SEES','Local buffer','Power, usable energy and recharge limits']].forEach(([tag,name,detail],i)=>{const x=m?25:73,y=m?60+i*192:71+i*160;o+=t(x,y,tag,m?16:19,C.muted)+t(x,y+49,name,m?29:37,i===0?C.compute:i===1?C.communication:C.checkpoint)+t(x,y+91,detail,m?16:24)+line(x,y+124,m?365:1125,y+124);});return result(o,'Scheduling changes eligible work timing; supported GPU controls change device behavior; local storage changes the source-facing trace by charging and discharging. Each has different limits and costs. A request load balancer and an electrical buffer are not interchangeable.');}
function nextBrief(s,m){let o='';[['DEFINE THE SERVICE','GB300 NVL72 · Llama 3.1 70B',['100 active sessions × 40 output tokens/s','Prompt/output lengths · quality · first-token target']],['MEASURE THE ACTUAL WORKLOAD','At the intended IT or facility meter',['Token delivery + complete-run energy','Peak · transition duration · recovery behavior']],['DESIGN THE SUPPLY','Choose a response from the trace',['Sustained source capacity + usable buffer','Cooling + supported failures and maintenance']]].forEach(([a,b,c],i)=>{const x=m?25:65,y=m?42+i*215:52+i*167;o+=t(x,y,a,m?16:20,C.muted)+t(x,y+45,b,m?21:31,i===1?C.communication:C.compute)+lines(x,y+86,c,m?15:23,C.ink,'start',m?29:31);if(i<2)o+=line(x,y+158,m?365:1130,y+158);});return result(o,'Carry the defined hardware, model, inputs, output quality, concurrent sessions, token-speed and first-token targets. Benchmark complete-run energy and time-resolved power at the intended meter, including recovery. Those measurements inform sustained capacity, local buffering, cooling and continuity design. No pass/fail performance claim has been made for the rack.');}
export function renderWorkload(id,state,compact=false){
 const f={'workload-purpose':purpose,'success-brief':brief,'model-work':modelWork,'memory-comparison':memoryCompare,'kv-cache':kv,'context-capacity':context,'prefill-decode':prefill,'continuous-batching':continuous,'energy-per-result':energy,'resource-paths':resource,'training-power-evidence':evidence,'independence':independence,'demand-transition':demand,'power-response':response,'next-brief':nextBrief}[id];
 const rendered=f?f(state,compact):['job-phases','synchronized-jobs','staggering-jobs'].includes(id)?phaseVisual(id,state,compact):null;
 if(!rendered)throw new RangeError(`Unknown workload scene: ${id}`);return rendered;
}
